### ISSUE TITLE
Time series: tooltip max width not work.

### ISSUE THREAD

**Issue by guidao** [grafana/grafana#105517]
### What happened?

Example:
<img width="520" alt="Image" src="https://github.com/user-attachments/assets/dc54f25d-d87f-4736-94c9-16f928f62a44" />

### What did you expect to happen?

Expect "testaaaaaa" to be truncated

### Did this work before?

Before grafana version is 8.5, not such config.

### How do we reproduce it?

No

### Environment (with versions)?

Grafana: 11.6.1
OS: Macos
Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

graphite

**Comment by jdmarshall** [comment]
It looks like the parent div is not growing to fit the child.  Which is odd because on mine I can get the popup to be about half my screen width and no problems, even without a whitespace character to break on.

But my grafana dashboard defaults to black. What changes did you make to get yours to look like that?

**Comment by guidao** [comment]
> I am unable to reproduce this on HEAD. What theme are you using?

Light. Dark also has a similar issue. I will try the latest version.

**Comment by jdmarshall** [comment]
I’m not at my desk, but this is on mobile safari. I even tried increasing the font size, because I know a bunch of sites that break when you do that. 

[Edit panel - Graphite Carbon Metrics - Demo Graphite - Dashboards - Grafana.pdf](https://github.com/user-attachments/files/20350812/Edit.panel.-.Graphite.Carbon.Metrics.-.Demo.Graphite.-.Dashboards.-.Grafana.pdf)

**Comment by guidao** [comment]
> I’m not at my desk, but this is on mobile safari. I even tried increasing the font size, because I know a bunch of sites that break when you do that.
> 
> Are you running addons? Something for ad blocking or accessibility?
> 
> ![Image](https://github.com/user-attachments/assets/e85bf0f4-56ff-4e2e-8bc5-d19bfd0b4de9)

Do you have a max width setting for tooltips?

**Comment by jdmarshall** [comment]
I do not. I don’t even recall that being an option. Might want to add that repro step to the report.

**Comment by guidao** [comment]
> I do not. I don’t even recall that being an option. Might want to add that repro step to the report.

I'm sorry for that. I've already updated it.

**Comment by jdmarshall** [comment]
Aah, I think this is a flexbox bug.

**Comment by jesdavpet** [comment]
Thanks for reporting this bug @guidao , and for the bug fix @jdmarshall ! 🏆

We have merged this bug fix in today, and it will be included in the next Grafana `v12.1.x` release.

**Comment by jesdavpet** [comment]
❌ Unfortunately this bug fix caused a regression by cutting off very long labels in tool tips with an ellipsis `...` for users _without_ a max-width set for their tool tips.

Re-opening this issue since a revert PR https://github.com/grafana/grafana/pull/107261 will need to be merged for this today.

I will revisit this issue as soon as possible, taking a _slightly_ different approach.

**Comment by jdmarshall** [comment]
There is a new PR out for this that addresses the concerns in the revert.

**Comment by jdmarshall** [comment]
There is still a PR to fix this issue.  No activity from the team.

**Comment by jdmarshall** [comment]
@guidao Can you still reproduce this bug? I just tried on trunk and could not, but it's also possible I have some detritus leftover from my branch.

**Comment by leeoniya** [comment]
i think the fix landed in https://github.com/grafana/grafana/pull/112240 ?
