### ISSUE TITLE
issues with stacked bar and $__timeGroup macro and Mysql

### ISSUE THREAD

**Issue by sandcoffin** [grafana/grafana#10785]
I wanna report some issues, tested with latest version 5 (nightly build), run with 
Linux  2.6.32-431.11.2.el6.x86_64 #1 SMP Tue Mar 25 19:59:55 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Data source used is Mysql latest version
I have two issues to report:
1. timeGroup macros:
       - cannot use '1d' in the macro $__timeGroup(SubmissionTime, '1d') 
       - help section is wrong (AS time does not work, must be time_sec) with the usage $__timeGroup(timestamp_col, '1h') AS time 
       - date displayed wrongly using macro timeGroup ( one day mismatch), I doubt that it's because of '/' operator used in the macro, i tried DIV keyword and dates display correctly

Basically i wanna plot metric taken from Mysql db, with kind of 3 columns (time, instance_id, status)

select
    cast(cast(UNIX_TIMESTAMP(time) DIV 86400 as signed)*86400 as signed) as time_sec, 
    count(*) as value,
    status as metric
from wq.as 
where time > now() - interval 60 day 
group by 1, status
;

time_sec|value|metric
1512691200 | 106 | SUCCESS
1512864000 | 11 | FAIL
1512864000 | 3027 | SUCCESS
1513468800 | 494 | FAIL
1513641600 | 3912 | FAIL
1513641600 | 92 | SUCCESS
1513900800 | 218 | FAIL
1514073600 | 10514 | FAIL
1514073600 | 2883 | SUCCESS
1514678400 | 1088 | FAIL

![image](https://user-images.githubusercontent.com/16156136/35840765-cffd5a18-0b2a-11e8-8a3d-eb5f0e4cf1f7.png)

If I use $__timeGroup(SubmissionTime, '24h') as time_sec, the date displayed is wrong (one day mismatch from 17/12 -> 18/12)
![image](https://user-images.githubusercontent.com/16156136/35840838-1c5f6824-0b2b-11e8-84d1-2a4f8afb80ac.png)

2. fill (0) data points:
in previous query result, due to sql group by, e.g. it misses data point on date 1513900800, there is no data for SUCCESS instance, so it displays weird on the graph
I tried searching for solutions but not succeed yet, if i fix it by sql query, the query will be fairly complicated. Can grafana add a feature like fill(0), similar to the one supported in influxDB 

we had a similar graph (using this query) running on Metabase dashboard and it displays well (think it has sth like fill(0) on missing data point)

**Comment by sandcoffin** [comment]
hi, can anyone look into this please

**Comment by marefr** [comment]
@sandcoffin First, question are better suited for our [community site](https://community.grafana.com/) since you're probably get better attention/help there. So please use the community site in the future for questions.

Second, docs for mysql should be updated. I'll create an issue for this. Thanks for reporting.

Third, let's see if I can answer some of your questions before closing.

1) You're correctly using '24h' instead of '1d'. One day mismatch question is better suited in community site. 
2) Use the Null value field *null as zero* in the display tab of the panel. Should fix it.

Closing this and suggest that we continue the discussion on the community site if there should be any other questions.

**Comment by sandcoffin** [comment]
hi @marefr 
FYI, the example in help section, when u chose mysql as main data source is wrong
![image](https://user-images.githubusercontent.com/16156136/35856192-d02dea06-0b67-11e8-8928-bd63e095dd1c.png)

I posted my questions here
https://community.grafana.com/t/issues-with-stacked-bar-and-timegroup-macro-and-mysql/5272
and:
>>Use the Null value field null as zero in the display tab of the panel
this does not fix the issue unfortunately, can u help me on this, it took me quite a while already

**Comment by marefr** [comment]
@sandcoffin oh that documentation. Thanks for reporting. Will create an issue for it.

**Comment by sandcoffin** [comment]
and sorry one more question, i cant seem to reply here, is my post not approved yet or sth ?
https://community.grafana.com/t/issues-with-stacked-bar-and-timegroup-macro-and-mysql/5272/2

**Comment by marefr** [comment]
Maybe you need to verify your email address?
