### ISSUE TITLE
Intermittent alert "Could not find datasource Data source not found"

### ISSUE THREAD

**Issue by retzkek** [grafana/grafana#10843]
- What Grafana version are you using? 5.0.0-beta1
- What datasource are you using? Prometheus
- What OS are you running grafana on? CentOS 7

I upgraded our test server to v5 beta yesterday, and since then I've been getting intermittent alerts triggered with the error "Data source not found." The alert then clears on the next run.

```t=2018-02-08T16:39:24+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalHandler ruleId=15 name="RabbitMQ Queue alert" error="Could not find datasource Data source not found" changing state to=alerting```

I've seen this for multiple alerts, but not all, and not at the same time. All the alerts use the same Prometheus data source.

**Comment by bergquist** [comment]
@retzkek any chance you can share your dashboard json?

**Comment by torkelo** [comment]
do think that is related, think this could be some issue with sqlite or multi threading, or maybe it could be related to uid change? Wonder what could cause the intermittent nature.

During the time this was experienced did you update the dasboard? (view dashboard version history to see if it has any updates during the time you got this error)

**Comment by retzkek** [comment]
@bergquist dashboard here: https://gist.github.com/retzkek/ee68e5b949b5b5bb4ed28ec8e16c9a9a
both the "exchange rate" and "queue" alerts had the "datasource not found" error.

@torkelo This dashboard has not been changed since the upgrade. Also, I should have mentioned that we're using MariaDB, so I had to manually change dashboard.title to varchar(190) for the migration to work (as suggested in #10779). I guess that also means there could have been a connection problem, but I don't see any errors to that effect.

Also, this hasn't reoccured since I opened this... the only relevant change I can think of is I did save *another* dashboard that had alerts not long after.

**Comment by bergquist** [comment]
I've been spelunking in the code for a while. 

The error is created at 
https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/datasource.go#L32
then bubble up to.
https://github.com/grafana/grafana/blob/master/pkg/services/alerting/conditions/query.go#L109

The error handling in https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/datasource.go#L32 is broken since we always return `m.ErrDataSourceNotFound` if the sql query fails. (I just fixed this in master) Kinda hard to investigate this issue further. @retzkek Any chance you could try our master build (available in ~30min) and see if you get a new error?

**Comment by retzkek** [comment]
@bergquist thanks for looking into it! I've upgraded to the latest master build (from beta1) and will let you know what we see, although we haven't seen the "datasource not found" error in a while. I'll try to find some time to try another upgrade from 4.X to master in case that can trigger it again.

**Comment by torkelo** [comment]
closing this, for now, we added more error logging, if it happens again in v5 we can see what caused it.

**Comment by retzkek** [comment]
@torkelo @bergquist thanks, the improved logging shows that we do have an intermittent issue connecting to the database. I appreciate the help!

`Could not find datasource dial tcp xxx: getsockopt: connection refused`

**Comment by Nacer-BKRM** [comment]
Hi, 

I'm still facing the alert problem on my side, instead of updating grafana to Version 5.2.0-pre1 (commit: d0753949b). 


The error in logs : 

t=2018-05-07T11:27:15+0200 lvl=eror msg="Failed to test rule" logger=context userId=1 orgId=1 uname=admin error="Data source not found"
t=2018-05-07T11:27:15+0200 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alerts/test status=500 remote_addr=10.xx.yy.zz time_ms=57 size=33 referer="http://grafana-xxxxx.yyyyyy.org/d/d7D99-Giz/elb?refresh=30s&panelId=7&fullscreen&edit&orgId=1&tab=alert"


I replaced confidential information by xxx & yyyy. 

I'm running Grafana Server on Centos 7 server. 

Thanks u in advance for your feedback :)

**Comment by richerve** [comment]
I have the same error. Using Postgres on AWS RDS, no error message related to database connections

```
t=2018-08-15T13:55:20+0000 lvl=eror msg="Failed to test rule" logger=context userId=3 orgId=1 uname=XXX error="Data source not found"
t=2018-08-15T13:55:20+0000 lvl=eror msg="Request Completed" logger=context userId=3 orgId=1 uname=XXX method=POST path=/api/alerts/test status=500 remote_addr=1.2.3.4 time_ms=14 size=33 referer="https://grafana-url/d/E9kZIFImk/kubernetes-capacity-planning?panelId=9&fullscreen&edit&orgId=1&tab=alert&from=now-15m&to=now"
```

**Comment by emedina** [comment]
Also facing this issue lately with `Grafana v5.0.3 (commit: 91162f3)`:

```
ALERTING
Error: Could not find datasource Data source not found
Dec 26, 2018 13:33:24

ALERTING
Error: Could not find datasource Data source not found
Dec 26, 2018 02:02:36
```

**Comment by eaglesbest** [comment]
I also face the same issue with grafana-5.3.0-1 on CentOS6.9

**Comment by agolomoodysaada** [comment]
Also facing this in v5.4.2

**Comment by eaglesbest** [comment]
I tried that; But I didn't find old datasource id in my table alert; 
I just found two alerts whose datasource was not Prometheus, I modified them to Prometheus. 
And I will continue to focus on that the error will happen again.
Thank you!

**Comment by huaphuoctruong** [comment]
@agolomoodysaada perfect. We got the same isse but do you know why the wrong datasourceId in saved alert happen? Is it that related to datasource provisioning?
