### ISSUE TITLE
Alerts missing after upgrade from Grafana 11.2.0 → 12.1.1 when GitSync is enabled

### ISSUE THREAD

**Issue by teo9806** [grafana/grafana#109870]
### What happened?

Hey team,

I recently upgraded Grafana in our staging environment from 11.2.0 to 12.1.1.
All dashboards, alerts, contact points, and notification policies appeared intact immediately after the upgrade.
Once I enabled GitSync, dashboards remained present, but all alerts disappeared.
When navigating to **Alerting → Active Notifications → [selecting an alert rule],** I encountered the following error:
**/api/ruler/grafana/api/v1/rules/... 403 Access Denied**

I was logged in as an Admin during this process. FYI - we are deploying Grafana with a Bitnami Helm chart.

### What did you expect to happen?

I expected not only dashboards to be visible in the Grafana UI but also Alerts.

### Did this work before?

It is a new feature, so no.

### How do we reproduce it?

1. Bump the Grafana to the latest version
2. Enable GitSync
3. No alerts visible after

### Environment (with versions)?

Grafana: 12.1.1
OS:
Browser: Chrome

### Grafana platform?

Kubernetes

**Comment by moustafab** [comment]
Thanks for reporting this issue!

@grafana/grafana-git-ui-sync-team can you have a look at this? Seems like the permissions are being disrupted somehow based on the 403.

**Comment by ghost** [comment]
We are encountering the same exact issue. 

All Grafana-managed rules are gone. It seems the Alert rules folder is missing from the Git Repo.

Could it be that the Folder where Alert rules are saved are somehow not pushed to the repository when enabling Git sync? This would explain why they are not available anymore. 

There is an interesting error in the Logs:

`grafana logger=context userId=47 orgId=1 uname=XXXX t=2025-09-10T11:57:08.535759051Z level=info msg="Request Completed" method=GET path=/api/ruler/P8E80F9AEF21F6940/api/v1/rules status=404 remote_addr=XXX.XXX.XXX.XXX time_ms=46 duration=46.568606ms size=36 referer=https://grafana.XXXX.com/alerting/list handler=/api/ruler/:DatasourceUID/api/v1/rules status_source=server error="no rule groups found\n"`

`grafana logger=ngalert.scheduler t=2025-09-10T11:57:10.001672025Z level=warn msg="Unable to obtain folder titles for some rules" missingFolderUIDToRuleUID="map[bete78wrgx7ggb:[ceuvjqy59rhtsd eeuvc0nhzc934b few9idfg4eznkf feuvcs392du68f eeuvfdcixf4zkc deuvcb5yqi2o0a eeuvfhcs8bda8d deuw2vibv9c00f bevs6nw97dmv4b deuw38w9xhm9sd[] dete77pyfkbuoe:[eew9huh58dszkb few2z7jn3jrb4e cew9hipx67xmoc aeuvw46q4vmkgb aevs2n6f2udxcc ceu9u2bkjz3lsc deurlvxtv5logd cevnv8qkwl5ogf eew9hztwcb9c0b deurkwu6xu29sf feurldbq4rri8f eeurlp7of0j5sf aew9v5lq5o8w0a aeuw0a6kqcoaoe aew9d895bqltsc dew9hem7fdt6ob deurmlp0cu800a bew9hoipoofeof beud4uen4a9s0f few9h5ibt6z28d aeunyh319ebr4e bex1n0fxtzjswb]]"`

EDIT 1:

The rules are still available via the Grafana API:

curl -X GET http://<ADMIN_USER>:<ADMIN_PASS>@127.0.0.1:8080/api/v1/provisioning/alert-rules

This means the only real issue is the missing Alert rules folder, we can modify and update the Rules that are gone, just need to update the folderUID

EDIT 2:

Fixed by GETing the rules with the previous command, then editing the folderUID to a newly created folder, ensuring the folder is pushed to Git before and then modifying the Rule by PUTing with the following command (We used -H "X-Disable-Provenance: true" to not have the alerts marked as Provisioned and as such editable from the Grafana UI):

curl -X PUT http://<ADMIN_USER>:<ADMIN_PASS>@127.0.0.1:8080/api/v1/provisioning/alert-rules/<ALERTRULE_UID> \
-H "Content-Type: application/json" \
-H "X-Disable-Provenance: true" \
-d '<ALERTRULE_JSON>'

Interesting enough the Evaluation group, Dashboard links and Alert evaluation worked, this seems to suggest the Alerts are just hidden in the UI due to the missing folder error.

**Comment by teo9806** [comment]
Hey @moustafab, is this bug fixed in Grafana 12.2.0?

**Comment by ArturWierzbicki** [comment]
hey all, thank you for reporting this bug! indeed this is caused by folder UIDs changing during the full instance migration. as a temporary workaround, I'd recommend setting up per-folder git sync rather than a full instance sync

**Comment by teo9806** [comment]
Hey @ArturWierzbicki, thanks for the info. However, is there a plan for when this issue will be solved?

**Comment by ArturWierzbicki** [comment]
hey @teo9806 - its on the list but unfortunately there is no ETA yet, ill keep you updated

**Comment by benoittgt** [comment]
We had the same issue but on Alert Manager. Contact points were still present but Folders, Alert Rules, Recording Rules, Evaluation Group were dropped during the sync with Github. Hopefully, alert creation is scripted, so we recreated the folders, recording rules, and evaluation groups by hand, updated the UUIDs in our script, and re-ran it.

I find it surprising that this is broken, since those elements aren’t visible inside the Git repository yet — Grafana Git Sync doesn’t synchronize them, it only synchronizes dashboards.
> Git Sync lets you manage Grafana dashboards as code by storing dashboard JSON files and folders in a remote GitHub repository. [[source](https://grafana.com/docs/grafana/latest/observability-as-code/provision-resources/git-sync-setup/)]

**Comment by domleanix** [comment]
We encountered this issue as well. All folders were recreated with new UIDs, which caused all alerts to disappear. Disabling the sync feature then caused the Grafana pods to crash due to OOM errors. In the end, we had to restore the database.

**Comment by MissingRoberto** [comment]
Sorry to hear that, @domleanix @benoittgt @teo9806 

Thanks for reporting this issue and for your patience while we work through it.

Because alerts, dashboards, and library panels can all share folders, full instance-level sync isn’t currently feasible. We need Alerts and Library Panels to be fully supported by Git Sync before we can safely enable instance-level syncing without unexpected side effects. 

To help mitigate the impact in the meantime, we’ve taken the following steps:

- Documented the issue and current feature limitations in our public docs.  
- Marked instance-level sync as unsupported.  
- Updated the onboarding experience so these limitations are clearly communicated.  
- Added an optional setting to export all unmanaged dashboards when using folder sync.

Looking ahead, we will also disable the instance-sync option by default in OSS and Enterprise, matching the behavior already used in Cloud.

Notice the checkbox there — you can try it out **without migrating your existing dashboards**, if you prefer.

**References:**  
- [Known Limitations](https://grafana.com/docs/grafana-cloud/as-code/observability-as-code/provision-resources/intro-git-sync/#known-limitations)  
- [Supported Resources](https://grafana.com/docs/grafana/latest/as-code/observability-as-code/provision-resources/intro-git-sync/#supported-resources)

You should now be able to use Git Sync with **folder sync** — the only difference is that it will create a parent folder — and this approach will not affect any alerts. Note that this only available in latest main for now as we don't back-port fixes for experimental features. 

<img width="967" height="408" alt="Image" src="https://github.com/user-attachments/assets/df70a9bc-3c92-497e-b043-98740214bb62" />

<img width="1059" height="826" alt="Image" src="https://github.com/user-attachments/assets/8d9612d7-e425-4d80-a813-3b4e6bc373d1" />

**Comment by spiro-nitesh-patel** [comment]
I’m facing a consistent issue when trying to use Git Sync / provisioning for dashboards only, while keeping alerts UI-managed.

Setup : 
Grafana OSS v12.3.1 (also seen on earlier 12.x)
Azure AD SSO enabled
Existing UI-managed alerts (not provisioned as code)
Git Sync configured only for dashboards and folders

Problem : 
As soon as I enable:
[feature_toggles]
provisioning = true 

All existing alerts disappear from Alerting → Alert rules
Alerts may still fire, but are not visible/editable in the UI
Disabling provisioning immediately restores alert visibility
This happens even when:
No alert provisioning files are intentionally added
Git Sync is used only for dashboards/folders

What I tried : 
Upgraded Grafana (12.1.x → 12.3.1)
Removed /etc/grafana/provisioning/alerting
Deleted and recreated Git Sync configuration
Restarted Grafana after each change
Confirmed behavior matches issue #109870

Question : 
Is there a supported way to enable Git Sync for dashboards/folders only without forcing alerts into provisioning mode?
Or is the expectation that alerts must be fully migrated to code before enabling provisioning, even if Git Sync doesn’t manage alerts yet?

Any guidance or recommended workaround would be appreciated @MissingRoberto

**Comment by MissingRoberto** [comment]
@spiro-nitesh-patel— See my comment above. You'll need to wait for version 12.3.2+ to get the necessary fixes. Enable Git Sync with folder sync enabled to prevent conflicts with your alerts. Let me know if this still don't work as you expect in that version :)

**Comment by IngmarStein** [comment]
@MissingRoberto 
I've enabled Git Sync with 12.3.2 and ran into this issue (all alerts vanished from the UI but are still contained in the database and continue working). I've since updated to 12.3.3. I do not see the "not fully supported" message from [#115569](https://github.com/grafana/grafana/pull/115569).

**Comment by MissingRoberto** [comment]
reopened to investigate what @IngmarStein is claiming.

**Comment by IngmarStein** [comment]
@MissingRoberto I've since updated to 12.4.0 and was able to successfully set up a folder-based sync (i.e. not full instance sync). Prior to that, I moved all alerts to a separate folder which isn't synced.

**Comment by MissingRoberto** [comment]
ok, perfect. That's how we designed it till we can support alerts :) Closing again as we don't backport during this phase.
