### ISSUE TITLE
Databricks: Azure OBO Auth not working

### ISSUE THREAD

**Issue by ktw4071** [grafana/grafana#110482]
### What happened?

Related to https://github.com/grafana/support-escalations/issues/17867 https://github.com/grafana/support-escalations/issues/18049

Azure OBO Authentication is not working due to a recent backend dependency update.

### What did you expect to happen?

Azure OBO Auth working as expected

### Did this work before?

Yes.
Before updating the pkg of `github.com/grafana/sqlds/v4 v4.2.1`, the Azure OBO Auth was working

### How do we reproduce it?

Configuration fails according to Databricks plugin documentation

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

### Datasource(s)?

Databricks

**Comment by ar2pi** [comment]
@ktw4071 has this been fixed in prod?

**Comment by ktw4071** [comment]
Will be releasing the fix to the prod after this weekend @ar2pi

**Comment by ktw4071** [comment]
Hi @ar2pi @ariatron  @alexwulf,

The databricks plugin has been released with `1.10.11`.

Thanks

**Comment by ariatron** [comment]
Inquired and will share what I hear back!

**Comment by ariatron** [comment]
My customer is going to test more however after updating the plugin to 1.10.11 they're still getting errors.

"Gave it a quick test with the same settings as before and I currently get ... but I'll take a look at the setup and try to get a better test in for you all in the next few days."
> databricks: request error: error connecting: host=<redacted>azuredatabricks.net port=443, httpPath=/sql/1.0/warehouses69f107a0844236a7: databricks: request error: open session request error: Post "https://<redacted>azuredatabricks.net:443/sql/1.0/warehouses69f107a0844236a7": request error after 4 attempt(s): Post "https://<redacted>azuredatabricks.net:443/sql/1.0/warehouses69f107a0844236a7": failed to get access token: user context not configured

**Comment by ar2pi** [comment]
I've reminded customer yesterday, and today they reported it is still failing on their end as well

> as we tried the newest Databricks Datasource version (v1.10.11 - 2025-09-02), the results seem a bit more reliable, but I still see the same error message popping up quite often. [...] I still see queries succeeding on the SQL side that show that error on Grafana side.

https://grafana.com/orgs/asml/tickets/192512

**Comment by ktw4071** [comment]
replied in the escalation @ar2pi 

Thanks

**Comment by ariatron** [comment]
Hi, this definitely still seems like a problem even with the configuration.

**Comment by szabalza** [comment]
Close as duplicate of https://github.com/grafana/grafana/issues/112955
