### ISSUE TITLE
Alerting: breakage loading the config after upgrading to 12.3.0

### ISSUE THREAD

**Issue by hillen** [grafana/grafana#114336]
### What happened?

Using Grafana Open Source and installing it into a kubernetes cluster using kube-prometheus-stack. This was working fine until the chart upgraded Grafana from 12.2.1 to 12.3.0.

Here is what I am seeing in the log when trying to start Grafana 12.3.0 and it does not start:
After the plugins are loaded.
logger=plugin.store t=2025-11-22T04:44:10.96995983Z level=info msg="Plugins loaded" count=57 duration=169.930627ms
logger=query_data t=2025-11-22T04:44:10.975461094Z level=info msg="Query Service initialization"
logger=live.push_http t=2025-11-22T04:44:10.978893368Z level=info msg="Live Push Gateway initialization"
logger=ngalert.multiorg.alertmanager t=2025-11-22T04:44:10.981736903Z level=error msg="Failed to apply Alertmanager config for org" org=1 id=1 error="failed to parse Alertmanager config: unable to parse Alertmanager configuration: root route must not have any matchers"

Then when provisioning the alerting.
logger=provisioning.alerting t=2025-11-22T04:44:11.441615465Z level=info msg="starting to provision alerting"
logger=provisioning t=2025-11-22T04:44:11.442206515Z level=error msg="Failed to provision alerting" error="contact points: [alerting.notification.configCorrupted] Failed to unmarshal the Alertmanager configuration"
Error: ✗ invalid service state: Failed, expected: Terminated, failure: invalid service state: Failed, expected: Running, failure: not healthy, 0 terminated, 1 failed: [starting module provisioning: invalid service state: Failed, expected: Running, failure: contact points: [alerting.notification.configCorrupted] Failed to unmarshal the Alertmanager configuration]

Here are the configuration files for alerting:
  contactpoints.yaml
    apiVersion: 1
    contactPoints:
    - name: Alertmanager
      orgId: 1
      receivers:
      - settings:
          url: http://alertmanager-operated.monitoring:9093
        type: prometheus-alertmanager
        uid: alertmanager

  notification-policies.yaml
    apiVersion: 1
    policies:
    - group_by:
      - alertname
      object_matchers:
      - - contact_point
        - =
        - alertmanager
      orgId: 1
      receiver: Alertmanager

Since the log mentioned matchers, I removed the object_matchers from the notification-policies.yaml and do not see any differences.

I just modified the deployment and changed the container from 12.3.0 to 12.2.1 with no other changes and it started fine.

Here are those sections of the logs after that was done.

logger=plugin.store t=2025-11-22T04:47:41.297001843Z level=info msg="Plugins loaded" count=56 duration=1.107029453s
logger=query_data t=2025-11-22T04:47:41.335620302Z level=info msg="Query Service initialization"
logger=live.push_http t=2025-11-22T04:47:41.353687663Z level=info msg="Live Push Gateway initialization"
logger=ngalert.notifier component=alertmanager orgID=1 t=2025-11-22T04:47:41.363467774Z level=info msg="Applying new configuration to Alertmanager" configHash=afe22ddb9edde0dfde9b8a89d0d20ee6

logger=ngalert.multiorg.alertmanager t=2025-11-22T04:47:41.485073953Z level=info msg="Starting MultiOrg Alertmanager"
logger=provisioning.alerting t=2025-11-22T04:47:41.613483804Z level=info msg="starting to provision alerting"
logger=provisioning.alerting t=2025-11-22T04:47:41.766680631Z level=info msg="finished to provision alerting"

If any other configuration is needed, let me know and I can provide it.
Or, if you think starting with a fresh database would provide insight that can also be done. This is just using the SQLite database.
I looked at the latest documentation and do not see any issues with the configuration provided.

### What did you expect to happen?

I expect Grafana 12.3.0 to start.

### Did this work before?

Yes, this worked with Grafana 12.2.1.

### How do we reproduce it?

1.Start Grafana 12.3.0 with this configuration:
  contactpoints.yaml
    apiVersion: 1
    contactPoints:
    - name: Alertmanager
      orgId: 1
      receivers:
      - settings:
          url: http://alertmanager-operated.monitoring:9093
        type: prometheus-alertmanager
        uid: alertmanager

  notification-policies.yaml
    apiVersion: 1
    policies:
    - group_by:
      - alertname
      object_matchers:
      - - contact_point
        - =
        - alertmanager
      orgId: 1
      receiver: Alertmanager

### Environment (with versions)?

Grafana: 12.3.0
OS: Grafana container
Browser:

### Grafana platform?

Kubernetes

**Comment by cubakid** [comment]
All plugins are broken in 12.3. There are a few reports but they sit in "triage". I think this is critical but don't know how to up the priority on them.

[https://github.com/grafana/grafana/issues/114279](url)

**Comment by hillen** [comment]
@gillesdemey I did some builds of the grafana container and building with commit 73cf4b08955cc0df2ab30ec91387392ce0b40bd3 did not have the issue, but building with commit 488eafe02e26778c9503bc664db57e808cc54f6d has the issue. Therefore, it seems that the changes added for alerting triage in PR #110339 is what is causing this.

I am having issues building release-2.3.1 and main, so I cannot check if this is already fixed.

I am not a full stack developer and it will be difficult for me to track this down. But, I may try tomorrow to narrow this down further.

Can you provide any insights as to whether this is unintended breakage? Or, is there a configuration change for alerting that is required for this change?

**Comment by IngwiePhoenix** [comment]
Does this issue still persist? I noticed a patch release was added, but this does not seem to address this particular issue.

**Comment by hillen** [comment]
@IngwiePhoenix Yes, this issue still persists with 12.3.1. I have pinned grafana to 12.2.3 while this issue still exists.

I have not attempted to do any further isolation of the issue other than it is cause by PR 110339 that has to do with the alerting triage feature.
Unfortunately, this is a very large PR and it is not obvious what to try to back out to isolate the issue.

I did try to start with a fresh database with 12.3.0 and it did not help. And where it fails so quick in the start up of grafana, I am not sure that there is anything I can change in my configuration to keep the issue from happening. But, if I can isolate the exact change in the PR that causes it, then it may give me a clue as to whether there is something that can be done in the configuration of grafana.

**Comment by titti-dot** [comment]
Dear @hillen  @IngwiePhoenix ,

We are facing the same issue, do you now if this issue will be fix soon or if it's already fix in the release 12.3.2?

**Comment by szEvEz** [comment]
We were trying to update from 12.2.8 to 12.3.6+security-01 and unfortunately this issue still persists.

**Comment by hillen** [comment]
I was able to resolve this issue.

I changed my notification policy from:
notification-policies.yaml
apiVersion: 1
policies:
- group_by:
  - alertname
  object_matchers:
  - - contact_point
    - =
    - alertmanager
  orgId: 1 
  receiver: Alertmanager

to:

apiVersion: 1
policies:
- group_by:
  - alertname
  orgId: 1
  receiver: Alertmanager
  routes:
  - object_matchers:
    - - contact_point
      - =
      - alertmanager
    receiver: Alertmanager

and this matches the latest documentation and this change makes sense given the error that was received. failed to parse Alertmanager config: unable to parse Alertmanager configuration: root route must not have any matchers

I had looked at this before and think that I attempted to make this change, but did not catch the requirement that this change has to be made before the version of grafana is updated.
You need to update the notification policy and restart grafana version 12.2.x to allow grafana to update the notification policy in the database. Then update the version of grafana to version 12.4.3 and it will start. If you try to update the notification policy and the grafana version in the same helm chart install then grafana will not start and the new notification policy will never be stored.

I was able to upgrade to 12.4.3 last week in all environments and have started updating to 13.0.1 and it is starting fine after this change.

I am going to close this issue.
