### ISSUE TITLE
JavaScript Memory leak since 5.1/5.0

### ISSUE THREAD

**Issue by rlueckl** [grafana/grafana#12782]
### What Grafana version are you using?
5.2.1

### What datasource are you using?
Graphite

### What OS are you running grafana on?
Debian Jessie

### What did you do?
We have a TV in our office permanently displaying dashboards, refreshing with Grafana's "Refresh every..." setting.

### What was the expected result?
Browser runs for long periods of time.

### What happened instead?
Browser crashes after few hours/1-2 days.

I think there's a JavaScript memory leak issue with Grafana since at least version 5.1 (that's when I first noticed it) - maybe since 5.0 (since the overhaul of the interface?).

### Steps to reproduce:
1. Have a fairly large dashboard with lots of panels and metrics being queried. Our Dashboard has 23 graph panels (1 metric per minute) and loads about 1MB data ("Transferred" column in Firefox Debug Tools). Time range is set to 24 hours.
2. Set "Refresh every" to a minute or two.
3. Observe memory consumption of the browser for a long period of time (1-2 days).

You can accelerate the process by opening multiple tabs of the same dashboard. We have usually 4 open dashboards, each with a different set of variables and rotate them via a tab rotator in the browser. But the crash also happens with all plugins disabled, so it's not because of the tab rotator ("Tab Slideshow" in Firefox, "Revolver - Tabs" in Chrome and Vivaldi).

With 4 tabs and 4GB RAM we can crash the browser within 1 day (out-of-memory). This didn't happen before 5.0! We didn't change the dashboard, only updated Grafana.

I tested the following browsers on the same PC running Linux Mint 18:

 * Firefox ESR
 * Firefox Quantum
 * Google Chrome (not Chromium!)
 * Vivaldi

I tried to capture an "Allocation instrumentation on timeline" in Google Chrome, but the browser hung after 2 hours and the file was corrupted.

According to "Heap snapshot" most of the allocated memory is in JS Arrays. Comparing two Heap snapshots taken a few hours apart shows mostly growth in the JS Arrays. It seems to me that old metric points (after a Refresh) won't get thrown away and keep using memory for ever (even though they are not displayed anymore).

**Comment by marefr** [comment]
Why not using the playlist feature?

**Comment by rlueckl** [comment]
Because afaik playlists still can't set different template variables (see #773). But that's not the point.

The memory leak happens also with only 1 tab, without rotating between tabs (only slower).

**Comment by marefr** [comment]
The playlist will do a full reload of url from time to time to mitigate possible memory leak problems. If you can do that as well with your custom solution that could be a workaround. 

It's really hard for us to investigate these kind of problems without having exactly the setup you have so whatever information you can provide to help us would be awesome.

**Comment by torkelo** [comment]
Can you provide a dashboard json file? Any custom plugins installed?

**Comment by rlueckl** [comment]
The dashboard contains a lot of sensitive data (hostnames in the metric path, etc.) so I'll have to sanitize it before - this might take a while.

We don't have any custom plugins and only use the "Graph" panel in this specific dashboard.

**Comment by torkelo** [comment]
The memory leak is due to baron (scrollbar component) in the graph legend. It is being added on every render, unlike the previous component perfect scrollbar was only added on first render. 

baron is being destroyed / added on every render, since baron uses a much more complicated method and needs sub-elements (that are replaced every render) it's not an easy fix. Either we need to rewrite the legend in react so we can start using a good react scroll component  (https://github.com/malte-wessel/react-custom-scrollbars) or find a hacky fix to cleanup the barons between renders (but having to init a new baron every render seems so bad). 

thougts @alexanderzobnin  ?

https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/legend.ts#L273

**Comment by rlueckl** [comment]
Hi @torkelo,

thank you very much for the analysis! So I assume that you don't need the dashboard json anymore.

**Comment by EmilioD** [comment]
We have been seeing this in 5.2.4 as well. Only much faster (refreshing every 10s showing 2h of data), with 4 dashboards at once. Is a fix for this in the pipeline for 5.3.0 or a later release?

**Comment by delfuego** [comment]
I'm still seeing this in 5.3.0 as well, FYI.

**Comment by delfuego** [comment]
To follow up my own comment, I set up a node app using Puppeteer to load one of our dashboards (which contains 11 singlestat panels and eight graph panels, 24h of data, reloading every 10s, nothing fancy) and then pull the page metrics every 30 seconds.

A minute after I started it (to let the dashboard load), the relevant metrics (at least what I *think* are the relevant metrics) are:

- JS used heap size: 26,415,672 bytes
- JS total heap site: 47,931,392 bytes
- total nodes: 7,800
- total JS event listeners: 1,298

30 minutes later, the page metrics are:

- JS used heap size: 47,744,216 bytes
- JS total heap size: 61,562,880 bytes
- total nodes: 61,789
- total JS event listeners: 26,139

That's pretty stark — the the total heap increased by nearly 30%, the node count increased by nearly **700%**, and the event listeners increased by **1900%**.

Am I wrong that this points to Grafana not cleaning up after itself as it reloads? Is there anything that can be done before these issues are addressed in code?

**Comment by rlueckl** [comment]
@delfuego I think @torkelo already found the problem, see above: https://github.com/grafana/grafana/issues/12782#issuecomment-409882820 (some JS elements are added on every reload, but not cleaned up)

**Comment by delfuego** [comment]
I saw that — I was just clarifying that the fix hadn't come in 5.3.0 (or 5.3.1, I've since also verified).

Is there any idea (@torkelo, or @alexanderzobnin) about when the fix for this might hit a release? As it stands, I'm not able to run our dashboard on our Brightsign media players without them crashing within hours.

**Comment by torkelo** [comment]
we hope https://github.com/grafana/grafana/pull/13740 solves this issue

**Comment by torkelo** [comment]
fixed or improved by https://github.com/grafana/grafana/pull/13740

**Comment by ryan-williams** [comment]
I believe I'm seeing this in 5.3.4; can you clarify which version should have the fix? It seems like 5.3.4 was cut since this fix went in, so I am a little confused. Thanks!

**Comment by torkelo** [comment]
It's in v5.4 (beta out today)

**Comment by jtorrejon** [comment]
Hi there,

We are still having this issue even with the version 5.4.

Could you please have a look again?

Thanks!

**Comment by torkelo** [comment]
Can you provide more detail, what does your dashboard look like ? What is your refresh rate, what datasource , how much does memory increase for every 20 refresh for example ?

**Comment by jtorrejon** [comment]
> Can you provide more detail, what does your dashboard look like ? What is your refresh rate, what datasource , how much does memory increase for every 20 refresh for example ?

Yes. I'll give you all details:

Machine Specs:
Intel Core i5-2400
4GB RAM DDR3
Windows 7
Same issue in Google Chrome and Firefox

Grafana:
4 browser tabs with one different dashboard on each
Dashboards are filled with graphs, lists and world maps
Datasources are Elasticseach, Zabbix, Worldping and SQL
Refresh rate is 10 seconds
With 20 seconds refresh, memory is growing 500MB approximately every 2 hours

I think the graphs with Elasticsearch data is the cause of this.

If you need further information, do not hesitate to ask for it!

Many thanks!

**Comment by xliaoong** [comment]
@torkelo 
please check here: https://smallpath.me/post/grafana-fe-memory-leak

**Comment by Raboo** [comment]
@xliaoong your certificate is expired and HSTS is turned on...

**Comment by xliaoong** [comment]
@Raboo not my certificate, i just find a solution,  so .... i think it's safe, don't worry about that

**Comment by delfuego** [comment]
FYI, for me, v5.4 (specifically 5.4.2, which is the first 5.4-line I upgraded to) completely resolves this issue. Watching my memory instrumentation logs, both in headless Chromium on Linux and in Chrome running on an embedded device, the memory usage is now rock stable over time.

**Comment by Diabolo4480** [comment]
Hi i have the same Problem with Version 5.4.2 installed today. I use the prtg Plugin ans the Browser crashes cause memory problems. The browser runs on a HP 7010 with 8GB Memory.Grafana himself runs on a HP Proliant V 9 16GB RAM.  On my Dashboard there are 6 Boom Tables with Ping Request 1 Traffic Light with 12 Server Request . and 3 Graphs with stuff like cpu usage and networktraffic . prtg map runs without any problem but Grafana still crashes. after 30 Minutes  Grafana needs 2GB memory. when i look in chrome taskmanager it shows 1.8 gb javascript memory. Is there a workarround i can use?? I testest Grafana and now my CEO wants it for show off.

**Comment by Diabolo4480** [comment]
additional i use a 30sec refresh and show the last 6 hours

**Comment by torkelo** [comment]
Does it only happen on dashboards that use the prtg Plugin ?

**Comment by Diabolo4480** [comment]
at the moment i only use  the prgt Plugin. I startet with Grafana last week.

**Comment by torkelo** [comment]
Maybe it's an issue with that plugin

**Comment by Diabolo4480** [comment]
i checked the issues for that and opened an issue  at the creators account but no one else opened an issue with this problem there. The funniest thing is that when i stop auto refresh, memory will not be reduced, it still stays at the same high point. After reading in some issues here i thought grafana will delete older information automaticly.

**Comment by torkelo** [comment]
why would it be reduced? if there is a memory leak it does not go away because you stop refresh.

**Comment by mamontr** [comment]
> Maybe it's an issue with that plugin

Hi, @torkelo! Do you think the problem in plugin prtg? I use Grafana v.5.3.4 and have the same problem.
Do you know, if problem in plugin, how can i fix problem or maybe you have another recomendation? Thank you a lot!

**Comment by torkelo** [comment]
Yes, you can test in dashboard with it

**Comment by Diabolo4480** [comment]
I use a workaround. I am using an extension that refreshes the whole page about every 10
minutes.

**Comment by alexanderzobnin** [comment]
> The funniest thing is that when i stop auto refresh, memory will not be reduced, it still stays at the same high point

That's why it's called "Memory leak" :)
