### ISSUE TITLE
Big Dashboard Insufficient Resources (net::ERR_INSUFFICIENT_RESOURCES)

### ISSUE THREAD

**Issue by jmeberst** [grafana/grafana#14105]
I have a large dashboard, with 48 (4x12 repeated) panels, and each panel has 6 queries pulling the last value of a measurement from an InfluxDb database. The refresh rate in grafana and of the data is 500ms, The time interval is usually set to 2min.

After about 15-20 min I see the following start on some, but not all of the panels:
GET <URL> net::ERR_INSUFFICIENT_RESOURCES

I started with a custom developed panel plugin for this page, but once I started getting these errors I switched over to using Group by Status Panel, and I'm still seeing the same issue. The speed of the error can be accelerated by increasing the time interval.
 
Please include this information
What Grafana version are you using?
Grafana 5.0.0
What datasource are you using?
InfluxDb set to proxy mode.
What OS are you running grafana on?
Windows

**Comment by torkelo** [comment]
Maybe there is memory leak with these panels? Can you use chrome dev tool memory profile and identify what takes memory and what are the retainers?

If you use for example the singlestat panel can you replicate this? Graph legend has a memory leak in 5.3 that is fixed in master so if you want to test graph panel try nightly build

**Comment by jmeberst** [comment]
I was able to replicate the issue with single stats, but I may just be pushing grafana to its limit with the number of queries. With the single stat and repeated template variables, it works out to 288 panels/queries in a single dashboard. All refreshing at 500ms.

Surprisingly it does work, as long as the $timefilter is kept to a low enough value. The issue I'm having is that even with a relatively low value $timefilter of 2 min it hits a resource limit after about 20 minutes.

**Comment by jmeberst** [comment]
I took a look at the chrome dev tools using a heap snapshot, and it revealed that the two objects holding the most memory are window and array. I believe you could recreate this by using data from a clock and repeating it with an increasing key name into Influxdb so clock_1, clock_2, ... clock_288 then use a template variable to repeat single stat panels showing the values.

**Comment by bergquist** [comment]
I'm closing this due to inactivity. Due to the number of issues, we aim to only keep active issues open. If you want to reopen this issue. please comment on this issue and we will do so.

**Comment by jmeberst** [comment]
I'm still seeing this issue, and I think I understand a little bit more about it.

I believe it's related to high tcp workloads, which should explain why it didn't appear in the 200 single panel demo that @torkelo did on Dec 4th, since it looks like the panel's data is from the random walk, and wouldn't use the proxied network connection.

It seems that when a TCP request gets stalled longer than the refresh rate of the dashboard, that requests information stays in memory when it eventually completes. The easiest way to see this is to set a large number of panels (40+) with a large amount of data (Last 6h on a clock with datapoints every 500ms) to a really small refresh rate (500ms). 

In Chrome you'll see this insufficient resources error on the higher number panels first.
![Err_Insufficient](https://user-images.githubusercontent.com/16615407/58193075-381bed80-7c90-11e9-852b-f287d7f9e4d7.png)

Firefox will mostly let the memory just leak until it kills the browser unless it manages to successfully update the entire page, which will allow garbage collection. (why it decreases in some snapshots).
In the second screenshot I up the timeframe from 1h to 6h to show the memory difference (+ 3GB).
![MemoryLeak](https://user-images.githubusercontent.com/16615407/58193282-a5c81980-7c90-11e9-89be-13d50a2e03c3.png)
![MemoryLeak2](https://user-images.githubusercontent.com/16615407/58193295-ac569100-7c90-11e9-88e1-c1ec4e34654e.png)

Normally I would just decrease the amount of data since I really only care about the last 5s or so, but when I'm running this with a high number of clients it's very dependent on the response time of each TCP request, and even a small timespan will eventually cause the issue if the page is open long enough without being reloaded.

**Comment by jmeberst** [comment]
I just wanted to add this does occur in 6.2.2 as well. It seems like it might be mitigated a bit due to the speed of react, but with an hour timescale, it still has a pretty significant leak.

![memoryleak3](https://user-images.githubusercontent.com/16615407/58284377-755baa80-7d78-11e9-9666-0b2dd8544a5a.png)

**Comment by torkelo** [comment]
what panel are you using for your test?

**Comment by jmeberst** [comment]
Those are single stats, with an influxdb cluster for a data source, but I suspect any tcp data source should see a similar issue..

**Comment by selimt** [comment]
We are having the same issue with our dashboard which has about 48 singlestat panels each doing a simple Elasticsearch query. After an hour or so we get the "Annotation query failed" red alert dialog and looking at the Chrome console reveals "ERR_INSUFFICIENT_RESOURCES".

We are currently using Grafana 6.4.4

Thanks
-Selim

**Comment by jmeberst** [comment]
@selimt I wasn't able to solve this before leaving the project. I was waiting for the live streaming features to be included and documented before attempting to restructure my dashboards.

The problem I had with that many panels is grafana can't finish drawing the data before the next query would start (500ms refresh). That would orphan some queries and cause it to leak memory.

**Comment by selimt** [comment]
@jmeberst Thanks, in our case the refresh is 30 seconds. But we have the issue of using cross-cluster search which takes a long time. If multiple singlestat panels could share a single query it would help I believe.

**Comment by hugohaggmark** [comment]
> @jmeberst Thanks, in our case the refresh is 30 seconds. But we have the issue of using cross-cluster search which takes a long time. If multiple singlestat panels could share a single query it would help I believe.

@selimt You can share query between panels now in Grafana (can't remember when we introduced it but at least v6.7+). Use the `-- Dashboard --` from the data source picker as shown below:
![image](https://user-images.githubusercontent.com/562238/84349585-e48c8280-abb7-11ea-8263-87c8f29a049e.png)
![image](https://user-images.githubusercontent.com/562238/84349806-64b2e800-abb8-11ea-8407-608a312edfa5.png)
Let me know if that helps you out!

**Comment by peterholmberg** [comment]
Closing this because of inactivity. @selimt if you still encounter this please comment and we will reopen

**Comment by jmeberst** [comment]
I believe the original issue I had still exists, Sharing panels wasn't an option for me on that project.
