### ISSUE TITLE
$__interval variable does not get expanded in annotations queries

### ISSUE THREAD

**Issue by FUSAKLA** [grafana/grafana#15168]
### What Grafana version are you using?
Grafana 6.0.0-beta1
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Docker debian stretch
### What did you do?
Added annotations query to prometheus datasource
```
changes(process_start_time_seconds{ instance=~"$instance"}[$__interval]) > 0
```
### What was the expected result?
Get result from Prometheus after `$__interval` variable gets expanded to current used step by grafana
### What happened instead?
Grafana sends to the Prometheus query
```
changes(process_start_time_seconds{ instance=~"alertmanager-59c47fcdff-c2qfd|alertmanager-sre-77c6d44cc-hwj84"}[$__interval]) > 0
```
The `$__interval` variable does not get expanded and as a result getting error 
```json
{"status":"error","errorType":"bad_data","error":"parse error at char 113: missing unit character in duration"}
```

**Comment by torkelo** [comment]
$__interval is only available to inside panel queries at the moment

**Comment by FUSAKLA** [comment]
Thanks for answering so quickly. 
It works in the current stable version `5.4.3`. 
Does that change since `6.0.0`? If yes it might be worth to mention in breaking changes in the changelog possibly?

**Comment by FUSAKLA** [comment]
On now I see. It worked before fixing https://github.com/grafana/grafana/issues/14795 because there was always `60s` used by default. It never worked just the bug made it to look like it I suppose.

Now I don't know what to do with this? Mark it as a feature request or close this? 
I'll leave that up to you and avoid using this. 

Thanks for the clarification.

**Comment by trallnag** [comment]
It's the same with the "Link to Graph in Prometheus" feature. The variable does not get expanded.

![bug_recording](https://user-images.githubusercontent.com/24834206/84428159-4d124880-ac26-11ea-83e8-8f21deada0f0.gif)

**Comment by aocenas** [comment]
@torkelo is this something that needs to be fixed in the datasource or is this generic dashboard thing?

**Comment by torkelo** [comment]
Not sure, probably not

**Comment by davkal** [comment]
@FUSAKLA since annotations are dashboard-wide (and not panel-bound), would it be ok to calculate the step on the width of a row (this would make the interval twice as big as in a panel query that has half the row width)?

**Comment by anthraxn8b** [comment]
This is irritating for me. I can set an alert based on a dasboard panel - even if the query does not match the requirements as an alert query. I have no idea how to solve this "correctly" but either a check is required here to prevent the creation of an alert based on an invalid query or the variable has to be available by whichever magic.

**Comment by FUSAKLA** [comment]
@davkal hm, yeah I think using the full width would make sense :+1:

**Comment by fuomag9** [comment]
Same issue here ```Jan 5 13:16:22 raspi4 grafana-server[88582]: t=2021-01-05T13:16:22+0100 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=13 name="CPU alert" error="1:44: parse error: missing unit character in duration: " changing state to=alerting
```

**Comment by Elfo404** [comment]
@davkal Does it really make sense

**Comment by Elfo404** [comment]
@grafana/grafana-frontend-platform I think this has broader implications than just in Prometheus as other datasources as well might use the `$__interval` variables.

I'm moving this to your board, feel free to move it back if you think we should take care of this.

**Comment by AAverin** [comment]
Is this something that gonna be resolved in the future? Can I roll back to some version?

Queries display correctly on the board, but running an alert on top of any query with `$__interval` inside the query results in 
```error:"1:35: parse error: missing unit character in duration: "```

This basically makes alerts unusable because they simply fail

**Comment by gustavomassa** [comment]
The same issue occurs to "$__rate_interval" and alerts that use this variable

**Comment by MagicDevilZhang** [comment]
Same issue when '[${__range_s}s]' or '[$__ranger]' is used.
```
delta(kudu_live_row_count{type="table", job="tencent_kudu", instance="tencent_kudu"} [${__range_s}s])
```

**Comment by nohant** [comment]
problem still present on this query : 
`increase(http_request_duration_milliseconds_count{status=~"5.*", service="production-app"}[$__rate_interval])`
loki simply gives as output: `"1:89: parse error: missing unit character in duration: "`
which means is treaded as is "last state" due to our config.

**Comment by maidi29** [comment]
We have the same problem. Are there any solutions on this?

**Comment by ashharrison90** [comment]
hi @FUSAKLA and everyone else in this thread 👋 

first of all apologies for leaving this issue hanging around for so long... 🙏 

so it looks like there's 2 separate (but kinda related) feature requests here:
- interpolate variables in annotations
- interpolate variables in alerts

we have existing feature requests for those items [here](https://github.com/grafana/grafana/discussions/38252) and [here](https://github.com/grafana/grafana/discussions/39249).

can i please ask anyone that really wants to see these features implemented to **add their upvotes to the parent comment in those discussions** (and ofc join in on the discussion if you have any thoughts 😄 ). as with every software team we only have so much bandwidth so highly requested features or bugs will naturally be prioritised more. your vote matters! 🗳️

**Comment by glep207** [comment]
@ashharrison90 I see a third related use case:
 - interpolate $__interval and $__interval_ms in data links

See for example dicussion in https://community.grafana.com/t/link-to-external-system-using-current-interval/721.
I was about to create a new feature request for this but maybe you can link it to an existing issue that I am not aware of, if there is one?

**Comment by ashharrison90** [comment]
@glep207 i can't immediately find a matching discussion, so feel free to create one and we can go from there. thanks! 🙌

**Comment by urianawu** [comment]
We are still getting `[sse.dataQueryError] failed to execute query [query]: bad_data: invalid parameter "query": substitute queries failed: 1:270: parse error: missing unit character in duration` when using `$__interval` in alert queries.
