### ISSUE TITLE
[FeatureRequest] Dashboard List - Enable template variables in Dashboard List plugin

### ISSUE THREAD

**Issue by florianwgnr** [grafana/grafana#18113]
**Steps to reproduce** / **Actual Result**:

When using template variables (e.g. Line = 1) and clicking on an item in the dasboard list plugin, the new dashboard will be shown without handing the variables over to the next dashboard. 

Also searching (dashboard queries, tags) with template variables is not possible.

![grafik](https://user-images.githubusercontent.com/39341393/61298868-480f0400-a7df-11e9-80c4-6280c73fee32.png)

![grafik](https://user-images.githubusercontent.com/39341393/61206834-d7d78400-a6f3-11e9-970f-4786b994be01.png)

![grafik](https://user-images.githubusercontent.com/39341393/61206843-dad27480-a6f3-11e9-8a5e-436a95eb3366.png)

![grafik](https://user-images.githubusercontent.com/39341393/61206845-ddcd6500-a6f3-11e9-9045-fcfa2e623d00.png)

**Expected Result**

When using template variables in a specific dashboard, these variables should be handed over to the next dashboard when using the plugin. Probably a checkbox where you can choose the behaviour would be even better.

Also template variables should work for looking up dashboards.

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: InfluxDB
- User OS & Browser: Windows 7, latest Firefox

**Comment by florianwgnr** [comment]
*Added: searching (dashboard queries, tags) with template variables is not possible

**Comment by briangann** [comment]
The first part for passing templating variables should be easy to implement.

Not sure what is meant by `template variables should work for looking up dashboards` . To do this would require expanding all values of the template variables for every dashboard, which would be very time intensive. Or was there another idea?

**Comment by florianwgnr** [comment]
> The first part for passing templating variables should be easy to implement.

Great, thank you!

> Not sure what is meant by `template variables should work for looking up dashboards` . To do this would require expanding all values of the template variables for every dashboard, which would be very time intensive. Or was there another idea?

This page ( https://grafana.com/docs/reference/annotations/ ) shows how to use template variables in the tag query for annotations, like this: 
![grafik](https://user-images.githubusercontent.com/39341393/61350906-6ae5fa80-a869-11e9-8ad6-b87c2b9e311f.png)

But in the dashboard list plugin the same feature does not work.
![grafik](https://user-images.githubusercontent.com/39341393/61352696-4dfff600-a86e-11e9-87f4-3eca38132f8b.png)
This entry is not showing anything and thats what i meant with "template variables should work for looking up dashboards": enabling template variables in the tag query.

**Comment by florianwgnr** [comment]
> Not sure what is meant by `template variables should work for looking up dashboards` . To do this would require expanding all values of the template variables for every dashboard, which would be very time intensive. Or was there another idea?

This part of the issue has been fixed by @Maddin-619 

Now only the part for passing templating variables is missing.

**Comment by hugohaggmark** [comment]
I split out parts of this into #29028 and linked the PR to that instead.

**Comment by bjung82** [comment]
This issue seems to be fixed by 
https://github.com/grafana/grafana/pull/27926
👍

**Comment by hugohaggmark** [comment]
> This issue seems to be fixed by
> #27926
> 👍

@bjung82 I can't confirm this, care to share how #27926 could made this work?

**Comment by bjung82** [comment]
Oh sorry #27926 only fixes our problem of displaying a list of dashboards with already filled / passed template-variables. There is also functionality to filter the list of dashboard-links by tags. You are right, this one does not fix the (same?) problem in the Dashboard List (which we would prefer to use, by the way, because it looks better and more intuitive IMHO).

**Comment by joriws** [comment]
I am also trying to organize hundreds dashboards by templating via variables and letting user to select which kind of information he/she is interested in. And I am hoping that I could use by dashboard tags -system to search viable dashboards for user request. I am running 7.3.7 and this does not work AFAIK, so I am trying to set variables via custom values. 

Even changing variable value top line does not change title of plugin dashboard list..
variable: $product = [a,b,c,d,e]

panel dashboard list:
title: dashboards for $product

It maps this $product once but it is not updated when I change the top line variable from "a" to "b".
