### ISSUE TITLE
dashboard filter is case sensitive

### ISSUE THREAD

**Issue by blysik** [grafana/grafana#1896]
Noticed that the dashboard search is case sensitive.  This should probably not be.  Very confusing.

**Comment by torkelo** [comment]
what database do you use for Grafana? sqlite or mysql or postgres?

**Comment by blysik** [comment]
Postgres

**Comment by zackhsi** [comment]
+1

**Comment by bruce-lyft** [comment]
+1 this is causing us a lot of headaches.  @torkelo any hints where to look?  We can put some time into debugging this.  (also postgres)

**Comment by torkelo** [comment]
fixed!

**Comment by bobrik** [comment]
@torkelo I'm looking at linked commit 835fd38 and see that it is only present in 2.1.1 and master. This explains why it doesn't work in 2.1.3. Any reason for this?

**Comment by torkelo** [comment]
@bobrik yea, a merge mistake

**Comment by klynch** [comment]
Any idea when we can see this in a release? 2.1.4 maybe?

**Comment by neeleshkotian** [comment]
I am currently using version 7.5.7 and still see the issue with the filters using case-sensitive text. The data source is Prometheus.
![Filter-CaseSensitive-1](https://user-images.githubusercontent.com/73559039/121240188-0fabbf80-c868-11eb-8a69-903a964dab3b.jpg)
![Filter-CaseSensitive-2](https://user-images.githubusercontent.com/73559039/121240192-10445600-c868-11eb-9730-43191c141da9.jpg)

**Comment by jtommi** [comment]
@neeleshkotian That's not the same bug.
The column filtering you mention was only introduced in 7.2. and doesn't use the datasource, it's pure frontend
I created a new issue: #39283
