### ISSUE TITLE
Bar Gauge stop working for one host with low disk space

### ISSUE THREAD

**Issue by maxlehot1234** [grafana/grafana#19213]
**What happened**: 
BarGauge plugin stop working. No reason why...

**What you expected to happen**:
I want the bar gauge to work on every host. No idea which things I need to put here

**How to reproduce it (as minimally and precisely as possible)**:
I setup groups on Zabbix.
I setup a dashboard where I can choose the zabbix group and zabbix host from the selected group.
I have a host that have low disk space and it crash the bar gauge plugin for this host only.
I need to choose another ast and refresh the page to get the bar gauge work for the other host.
Example:
![image](https://user-images.githubusercontent.com/5159244/65177096-08a1a580-da24-11e9-9636-45b4c0e22c86.png)
Like you can see, we see the thing that allow us to resize the plugin (bar gauge), but no data in it, cause it crash for the host.
For the other hosts, it looks like this:
![image](https://user-images.githubusercontent.com/5159244/65177157-2969fb00-da24-11e9-9481-374c830c946d.png)

**Anything else we need to know?**:
This host have  15% less of space on the C drive.
Some other host have less than 10% and bar gauge still work without any issues.

**Environment**:
- Grafana version: Grafana v6.3.5 (67bad72)
- Data source type & version: Zabbix
- OS Grafana is installed on: CentOS6
- User OS & Browser: Win10 1903 + chrome 76.0.3809.132 

If anyone have an idea for this, let me know.

Thanks again

**Comment by torkelo** [comment]
you need to include the data your query returns for the empty bar gauge (check query inspector). 

Any errors in chrome dev console?

**Comment by maxlehot1234** [comment]
Here is the query inspector of this empty bar gauge:
https://gist.github.com/maxlehot1234/d786248e910d6954198b5c5dae91ac1a

Nothing in the Chrome dev console

**Comment by maxlehot1234** [comment]
@torkelo Any idea for this.

It was really weird that this host crash the Bar Gauge plugin :P 

Thanks again for your tiem

**Comment by torkelo** [comment]
No idea, something in the response? I do not know how zabbix parses that and turns it into response the panel

**Comment by maxlehot1234** [comment]
> No idea, something in the response? I do not know how zabbix parses that and turns it into response the panel

Ah, but why it works for every other host exept for this host ? Thats the thing :P

Need to wait for a Grafana dev, but this could take some time I think :(

**Comment by torkelo** [comment]
Can you switch to table panel to show what your query is returning to Grafana?

**Comment by maxlehot1234** [comment]
> Can you switch to table panel to show what your query is returning to Grafana?

It return this:
https://gist.github.com/maxlehot1234/761bb86c1c384db322243de57319bed2

Or this if you prefer:
![image](https://user-images.githubusercontent.com/5159244/65456753-04a4c780-de18-11e9-9be1-2dece5ca65ac.png)
With tables it works without issue. Something was going on with Bar Gauge

**Comment by maxlehot1234** [comment]
@torkelo I found the issue. Directly when a host go under 10%, Bar Gauge plugin crash.

**Comment by ryantxu** [comment]
What do you see in the table panel when it is under 10%?

by crash, do you mean? it does not show up?

In the bar gauge, what stat/calc are you using?  Can you try a different one?  maybe last_not_null?

**Comment by maxlehot1234** [comment]
> What do you see in the table panel when it is under 10%?
> 
> by crash, do you mean? it does not show up?
> 
> In the bar gauge, what stat/calc are you using? Can you try a different one? maybe last_not_null?

The table looks like this:
![image](https://user-images.githubusercontent.com/5159244/65546026-a1349b80-dee4-11e9-9669-3933afaf4ae4.png)

By crash I mean, every stats disappear instead of being like that:
![image](https://user-images.githubusercontent.com/5159244/65546108-ca552c00-dee4-11e9-8134-9ffed84d7395.png)

Right now it looks like this because a host goes under 10% of disk space percentage. (supposed to be Bar gauge)
![image](https://user-images.githubusercontent.com/5159244/65546149-e789fa80-dee4-11e9-897a-3de32e95f2f0.png)


I use this thing:
LogicalDisk Disk C: Space Available %
LogicalDisk Disk E: Space Available %
The drive letter was get from the host come from Zabbix source

If I try last_no_null, I see:
The same thing as above (the one with nothing)

Hope this will answer your questions

**Comment by maxlehot1234** [comment]
For now, I hide the host that was under 10% of disk space, but this need to be fixed :P Since disabling the host from grafana dashboard was stupid ;)

Thanks everyone if you can find the problem and/or fix it or let me know how I can fix it

I try to update to grafana 6.3.6 and got the same issue.

**Comment by ryantxu** [comment]
Can you try a query that only returns one value for each drive?  SELECT LAST(..) ...?  

Can you post the raw network response?  (using chrome dev tools) and obviously any console info if you see something there

**Comment by maxlehot1234** [comment]
> Can you try a query that only returns one value for each drive? SELECT LAST(..) ...?
> 
> Can you post the raw network response? (using chrome dev tools) and obviously any console info if you see something there

It return one value per drive right now.
1 column per drive.

I can create a bar gauge with a single drive for the host in question if you want

**Comment by ryantxu** [comment]
> 1 column per drive.

I am suggesting 1 *row* for each column. 

If you can give me the raw data for something that is failing, I will see if I can reproduce

**Comment by maxlehot1234** [comment]
> > 1 column per drive.
> 
> I am suggesting 1 _row_ for each column.
> 
> If you can give me the raw data for something that is failing, I will see if I can reproduce

Not so sure how I can create 1 row for each column.
How I can do these things?

I am probably dumb :(

**Comment by ryantxu** [comment]
> I am probably dumb :(

nonsense!

I am unfamiliar with Zabbix, so I don't know the answer either.

My guess is that the grouping used in the query breaks when the value is less than 10 -- I am curious what the output is.  The fact you see a blank panel suggests the whole process is not executing properly and we should investigate.  But I'm not sure how to reproduce ;)  I know for sure that the gauge supports values under 10!

**Comment by maxlehot1234** [comment]
>> I am probably dumb :( ...

@ryantxu I am in the Subway but I will test and let you know.

If it was an issue with Zabbix, no idea to fix it than :P

But why everything works great until 10.0001%? 

Thanks for your time

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maxlehot1234** [comment]
@ryantxu 
The Gauge plugin also have the same problem.
Gauge appear for like 1 second and disappear.
Same thing occured with the Bar Gauge plugin.

Gauge plugin:
![ezgif-4-d42d8f977838](https://user-images.githubusercontent.com/5159244/65611270-8a438700-df80-11e9-9860-cb010c45caf0.gif)

Bar Gauge plugin:
![ezgif-4-14dce65ca838](https://user-images.githubusercontent.com/5159244/65611307-9cbdc080-df80-11e9-96b7-71a967f8f335.gif)


Every other plugins (tables, graph, singlestat, heartmap, annunciator etc works without any issue

So I am 99.9% sure something was wrong between zabbix and these 2 gauge plugins.

I can probably ask alexanderzobnin for help with this since he knows zabbix a lot I think :)


Thanks in advance

**Comment by ryantxu** [comment]
If you can post the data I can help debug :) otherwise I'm just guessing

**Comment by maxlehot1234** [comment]
@ryantxu Buy raw data you mean from zabbix directly or inside grafana?
How I can "export" raw data from chrome dev tools. Not able to find the something related to it.

Thanks in advance

**Comment by ryantxu** [comment]
chrome dev tools... look at network requests -- you should see queries fire when you refresh.

Copy and paste one version that "works" and another that does not

**Comment by maxlehot1234** [comment]
> chrome dev tools... look at network requests -- you should see queries fire when you refresh.
> 
> Copy and paste one version that "works" and another that does not

Do you mean this thing?
1-) https://gist.github.com/maxlehot1234/028a9f89d342813939d14484806ce60e
Or
2-) https://gist.github.com/maxlehot1234/383a7b3c9a3cd588640cddc145c9289d

https://example.com replace our server URL for security reason
HOSTNAME replace the real hostname for security reason.

Thats the version that doesn't work with BarGauge.


Let me know if it's what you want

**Comment by ryantxu** [comment]
kinda :)

Try to limit the changes to a single request:
1. goto a single panel view
2. click "refresh"
3. in the network console you should see only the network request you made
4. looks like the request is a POST to zabbex
5. copy the *response* data (you sent the request data)

**Comment by maxlehot1234** [comment]
> kinda :)
> 
> Try to limit the changes to a single request:
> 
> 1. goto a single panel view
> 2. click "refresh"
> 3. in the network console you should see only the network request you made
> 4. looks like the request is a POST to zabbex
> 5. copy the _response_ data (you sent the request data)

I edit the panel that have issue so only get request from it now.
If I click on the first thing in the network console and click response, I get this:
https://gist.github.com/maxlehot1234/4e9e6404709e57c747a0b0f030e6a296

Is it this thing?

**Comment by ryantxu** [comment]
It will look something like this:
![image](https://user-images.githubusercontent.com/705951/65633986-20cc7400-df92-11e9-9776-1ed3fa55f85f.png)

![image](https://user-images.githubusercontent.com/705951/65634012-2e81f980-df92-11e9-95c3-9e42a1898387.png)

we care what is in the response JSON and how it is different between the query that behaves as expected and the other

**Comment by maxlehot1234** [comment]
> It will look something like this:
> ![image](https://user-images.githubusercontent.com/705951/65633986-20cc7400-df92-11e9-9776-1ed3fa55f85f.png)
> 
> ![image](https://user-images.githubusercontent.com/705951/65634012-2e81f980-df92-11e9-95c3-9e42a1898387.png)
> 
> we care what is in the response JSON and how it is different between the query that behaves as expected and the other

![image](https://user-images.githubusercontent.com/5159244/65634387-1dde7d00-dfac-11e9-892d-25a91d7d9de4.png)
I have a lot of "1" on the left column, so which one I take to take the headers and the response? :P 
I think "1" could be like your "query" one

**Comment by ryantxu** [comment]
you are close!

"1" is ok -- that is the just last part of the URL pointing to your endpoint

can you:
1. clear the console -- it will make all the previous requests disappear
2. refresh -- not the browser! -- but the icon in the upper right
3. you should see 1 new line on the network requests
4. copy the *response* json here (your screenshot is the request)

**Comment by maxlehot1234** [comment]
> you are close!
> 
> "1" is ok -- that is the just last part of the URL pointing to your endpoint
> 
> can you:
> 
> 1. clear the console -- it will make all the previous requests disappear
> 2. refresh -- not the browser! -- but the icon in the upper right
> 3. you should see 1 new line on the network requests
> 4. copy the _response_ json here (your screenshot is the request)

I still have multiple lines with "1" in the left column but the Request Payload, you need to have: user.login, hostgroup.get, host.get, application.get, item.get, usermacro.get, history.get, trigger.get

Sorry for that and thank for your patience and your time

**Comment by ryantxu** [comment]
pick that last one that executed (further down the list)

I do not want to see the request, only the response tab -- look to the right where it says "Response"

**Comment by maxlehot1234** [comment]
> pick that last one that executed (further down the list)
> 
> I do not want to see the request, only the response tab -- look to the right where it says "Response"

That's the response from the host that was under 10% and make the Bar Gauge to disappear:
https://gist.github.com/maxlehot1234/64c2f49dc16f127b86d777ad3432d10a


This is the reponse from a host that have more than 10% available:
https://gist.github.com/maxlehot1234/6793441ea4ebee30cb647ab40650b0bc

Let me know if you found something that was different.

**Comment by ryantxu** [comment]
A quick look comparing:

https://gist.githubusercontent.com/maxlehot1234/64c2f49dc16f127b86d777ad3432d10a/raw/3f0cd2f82d35bd03ca45a5a380ab5d75eca4b1ca/gistfile1.txt

to 

https://gist.githubusercontent.com/maxlehot1234/6793441ea4ebee30cb647ab40650b0bc/raw/316e76e900f418bed689de3efaf7a0081f62c600/gistfile1.txt

Only the value below 10 has a 'lastEvent' filled in -- no idea what that is, but it is different.  My guess is this has nothing to do with gauge specifically and could/should be fixed in the zabbix plugin:
<img width="287" alt="lastEvent" src="https://user-images.githubusercontent.com/705951/65643725-529c0580-dfa7-11e9-8644-75ad23782939.png">

Any thoughts @alexanderzobnin?

**Comment by alexanderzobnin** [comment]
@maxlehot1234 @ryantxu you pick wrong response, you have pick one with `histrory.get` query. `trigger.get` used only for highlighting panels with problems.

**Comment by alexanderzobnin** [comment]
@maxlehot1234 could you share your panel config? Any errors in JS browser console?

**Comment by maxlehot1234** [comment]
@alexanderzobnin By panel config, do you mean the JSON model?


No error in the browser console.

**Comment by maxlehot1234** [comment]
@alexanderzobnin 
Let me know when you can ;)

@ryantxu 
We freeup some disk space and the Bar Gauge still having the same problem even at 10.22%.

**Comment by ryantxu** [comment]
> By panel config, do you mean the JSON model?

yes

**Comment by maxlehot1234** [comment]
> > By panel config, do you mean the JSON model?
> 
> yes

Here it is with HOSTNAME represent the server hostname.
https://gist.github.com/maxlehot1234/cb7ad84d750ea4757cd59453548b04e3

**Comment by maxlehot1234** [comment]
@ryantxu @alexanderzobnin 
Problem was fixed TEMPORALY directly when I enable/disable transparent mode of the graph.

When I reload the page, Bar Gauge crash again.

So there is something related to Grafana+Bar Gauge+Zabbix.

Is it possible to fix this ;) So we can continue to have graphs with all useful datas.

Thanks again and have a nice day/night to you

**Comment by maxlehot1234** [comment]
@ryantxu @alexanderzobnin 
Now with 3 servers under 10%, Bar Gauge was fuc**ed
![image](https://user-images.githubusercontent.com/5159244/66228467-8369f200-e6ad-11e9-8a87-943a67644e51.png)

Any help plz? ;)

**Comment by torkelo** [comment]
Been unable to replicate this , something that zabbix returning that is unique and causing this? What is the graph or table showing?

**Comment by maxlehot1234** [comment]
@torkelo 
Hi,

What do you mean exactly?

I want to use the Bra Gauge plugin, but it start to crash when 1 drive goes under 10% and now I have 3 servers under 10% of disk space and Bar Gauge display errors and crash too...

**Comment by torkelo** [comment]
What error ? It says no data.

I mean what does other visualizations say for the same value? What are you bar gauge options ? Does the Normal gauge show anything ?

**Comment by maxlehot1234** [comment]
> What error ? It says no data.
> 
> I mean what does other visualizations say for the same value? What are you bar gauge options ? Does the Normal gauge show anything ?

It say no data cause it "crashed".
I use this thing from Zabbix to put datas in the Bar Gauge plugin: 

Application: Disk
Item: LogicalDisk Disk E: Space Available %
I use my server goup as the group and use the hostname as the hostname.

Check my previous message here for the Normal gauge, tables, etc: 
[https://github.com/grafana/grafana/issues/19213#issuecomment-535060971](url)


I am supposed to get this: (old picture from like a week ago)
![image](https://user-images.githubusercontent.com/5159244/66257132-32b4d080-e763-11e9-9255-db0585265775.png)

**Comment by maxlehot1234** [comment]
Nothing @torkelo @alexanderzobnin @ryantxu  ?
Sorry for the spam on this ticket, but I want it to be solve ;)

Without these graph, it was lot more harder to have everything in the same graph


Thanks again and have a nice day/night

**Comment by ryantxu** [comment]
sorry -- this seems hard to debug.  There is something happening with your response from zabbix when the value is below 10 (or something like that).  

If you could screenshare, I could maybe find a solution but we are unable to reproduce and.  Look me up on the grafana slack and we can try to sync up.

**Comment by maxlehot1234** [comment]
> sorry -- this seems hard to debug. There is something happening with your response from zabbix when the value is below 10 (or something like that).
> 
> If you could screenshare, I could maybe find a solution but we are unable to reproduce and. Look me up on the grafana slack and we can try to sync up.

Yeah it was really hard to debug.

I need to ask my boss for the screenshare for different reasons.

Maybe torkelo and alexander can "work" together on this, but without their help, it could be more complex to debug I think.

Thanks for the reply

**Comment by maxlehot1234** [comment]
@ryantxu I can screenshare so you can see zabbix and the grafana setup, but I doesn't want to put everything here, so how I can contact us "privately"?

Just let me know how we can do that.

**Comment by ryantxu** [comment]
> Look me up on the grafana slack and we can try to sync up.

**Comment by maxlehot1234** [comment]
> > Look me up on the grafana slack and we can try to sync up.

I'm on slack with the same username as github.
Never used slack so DM me if you want and if its possible :P 

Thanks in advance

**Comment by maxlehot1234** [comment]
@ryantxu I send you a message on Slack last week. No idea if we can add other people to it so I can screenshare to everyone at the same time ;)

**Comment by torkelo** [comment]
closing this for now as we have no other reports like this

Please double check your browser console for any js error logs

**Comment by maxlehot1234** [comment]
Still having the issue... So bad to close something without doing a screenshare or anything else...

I need help on this and a lot of people suggest me to post things and I post a lot of things....

Please reopen this issue since It was not related to me but was an issue between zabbix, grafana and data under 10% :( 

Please help us to make it work, we need it.
This plugin was in beta and you display a message related to possible issues.

I have an issue with it, I report it and you close it just because noone else report it?????

**Comment by maxlehot1234** [comment]
@torkelo Any other reason EXCEPT: "no one have this issue, so I close it" :(

**Comment by torkelo** [comment]
No, no other reason. 

Must be something strange with zabbix plugin or your query, maybe it return string values or some NaN value ?
