### ISSUE TITLE
Azure Monitor data source uses wrong authorization uri for Azure China

### ISSUE THREAD

**Issue by mstefa27-ford** [grafana/grafana#19545]
**What happened**:
When attempting to configure a data source in Grafana for Azure Monitor in the Azure China cloud, Grafana reports back two "unexpected error" messages and a message at the bottom: 

1. Azure Monitor: Cannot connect to Azure Monitor REST API. 2. Azure Log Analytics: Cannot connect to Azure Log Analytics REST API.

Upon inspection in the network tab in Chrome's developer console, I can see that the error appears to be caused by a 401 at http://{OUR GRAFANA HOSTNAME}/api/datasources/proxy/5/sameasloganalyticsazure/bf19f9f8-baac-4275-9a9b-546989f7d439/metadata

The www-authenticate header suggests that Grafana is attempting to obtain authentication from login.microsoftonline.com:

Www-Authenticate: Bearer authorization_uri="https://login.microsoftonline.com/common"

**What you expected to happen**:
I would expect Grafana to instead use the Azure China login gateway:

https://login.chinacloudapi.cn/common

**How to reproduce it (as minimally and precisely as possible)**:

Configure a Azure Monitor for the Azure China cloud (portal.azure.cn) with an Azure AD app registration that has the log analytics reader role to the subscription that contains your log analytics instance and the Data.Read permission for the Log Analytics API. Grant the permissions. Then attempt to configure the Log Analytics instances as a Data source within Grafana with the developer tab open to Network on Chrome (issue occurs in all browsers). 

**Anything else we need to know?**:

Grafana IS able to load the default subscription and workspace lists, but IS NOT able to query the Log Analytics API. Perhaps the way Grafana authenticates to get the subscription and workspace list is different than testing the Log Analytics API?

Confirmed all permissions are correct by calling the Log Analytics API myself with the same credentials via Postman.

**Environment**:
- Grafana version: 6.4.0
- Data source type & version: AzureMonitor 
- OS Grafana is installed on: Docker Image on Kubernetes/OpenShift
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: Only defaults
- Others:

**Comment by hugohaggmark** [comment]
Hi @mstefa27-ford we're investigating this further

**Comment by davliu-ms** [comment]
@hugohaggmark it's blocking issue. Can you give a priority and put an ETA for the fix?

**Comment by shavonn** [comment]
I believe the issue is that the `cloudName` is being saved as the select object instead of the string value that Grafana recognizes. My PR has a fix for this. Will merge today and hopefully, this will remedy this matter. https://github.com/grafana/grafana/pull/20183

**Comment by davliu-ms** [comment]
Hi Shavonn, thanks for the quick response. We will have a try with new release once merged.

Sincerely,
David Liu
________________________________
发件人: Shavonn Brown <notifications@github.com>
发送时间: 星期三, 十一月 6, 2019 10:26 下午
收件人: grafana/grafana
抄送: David Liu; Comment
主题: Re: [grafana/grafana] Azure Monitor data source uses wrong authorization uri for Azure China (#19545)


I believe the issue is that the cloudName is being saved as the select object instead of the string value that Grafana recognizes. My PR has a fix for this. Will merge today and hopefully, this will remedy this matter. #20183<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgrafana%2Fgrafana%2Fpull%2F20183&data=02%7C01%7CDAVLIU%40MICROSOFT.COM%7Cad94f6ad8f754035877e08d762c53ca5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637086471579999296&sdata=XJN7a1Q0WALqi102uaEEgWAjG1D%2BPXkVv3RxIxFgpWo%3D&reserved=0>

―

**Comment by mstefa27-ford** [comment]
Thanks for the help on this issue!
Not sure if the fix made it in the last release, but checking on the version released yesterday 6.4.4, looks like attempting to get the subscriptions for Azure China results in a 502 bad gateway.
![image](https://user-images.githubusercontent.com/32850843/68402382-3d3efd00-0149-11ea-9514-911398dbdad0.png)

**Comment by mstefa27-ford** [comment]
Additionally, if I put the same credentials under "Azure Log Analytics API Details" (unchecking the "same details as Azure Monitor box), we get a different error, a 401 with an error message of "The authorization header is missing access token": 
![image](https://user-images.githubusercontent.com/32850843/68402923-1d5c0900-014a-11ea-9328-de53aee3b18e.png)

**Comment by shavonn** [comment]
@mstefa27-ford you would need to reselect the Azure Cloud and save so that in can save the value correctly per the fix.

**Comment by mstefa27-ford** [comment]
Hmm, still no luck. Changing the Azure Cloud from NA back to China, and attempting to save with the same credentials still fails as above. If I re-enter the data source screen (via a new tab or refresh), I can see it has "Azure China" as the Azure Cloud. But, I'm not sure how successful the save is because if I try to save, it gives me this error as expected:

Nothing configured. At least one of the API's must be configured.

When trying to load subscriptions for either Azure Monitor or Log Analytics, I get the errors above. Am I missing something?

**Comment by shavonn** [comment]
fixed by https://github.com/grafana/grafana/pull/20183

**Comment by shavonn** [comment]
> Hmm, still no luck. Changing the Azure Cloud from NA back to China, and attempting to save with the same credentials still fails as above. If I re-enter the data source screen (via a new tab or refresh), I can see it has "Azure China" as the Azure Cloud. But, I'm not sure how successful the save is because if I try to save, it gives me this error as expected:
> 
> Nothing configured. At least one of the API's must be configured.
> 
> When trying to load subscriptions for either Azure Monitor or Log Analytics, I get the errors above. Am I missing something?

It will be in the 6.5 release. I thought you may be running off of the master branch.

**Comment by mstefa27-ford** [comment]
Ah ha, thank you! I will try again when the release is ready. Sorry for the confusion

**Comment by zbbkeepgoing** [comment]
**Precondition**
@shavonn I check out the master branch and build the latest images local today. Log list as follow
![image](https://user-images.githubusercontent.com/42572980/68568140-b914ae80-0495-11ea-9886-d5671558d8cc.png)


**Result after test**
But when i add azure(China) monitor on grafana. the metadata api still “Unauthorized”
The reason is just as @mstefa27-ford said.
![image](https://user-images.githubusercontent.com/42572980/68568521-c41c0e80-0496-11ea-9d3e-f8f20274ab66.png)

**The console screenshot** 
![image](https://user-images.githubusercontent.com/42572980/68568956-e5c9c580-0497-11ea-9bee-4e9b8961681d.png)


#20183 solves the problem of previous subscription load not work , but it still hava problem at log analytics

**Comment by marefr** [comment]
@shavonn seems like this is still an issue. Reopening the issue

**Comment by shavonn** [comment]
Hey @zbbkeepgoing, was this a previous datasource existing in Grafana or did you create a new one? I'm asking because it would have incorrectly saved the cloud as a `[object] [object]` instead of the cloud name. Checking to see if it needs to be reselected and saved. I do not have China credentials but when I switch to the China cloud, I can see that the bearer is correct:
`Www-Authenticate: Bearer authorization_uri="https://login.chinacloudapi.cn/"`

<img width="762" alt="Screen Shot 2019-11-12 at 6 08 26 PM" src="https://user-images.githubusercontent.com/3074595/68718848-7d064a00-0578-11ea-9feb-cd25785f315c.png">

**Comment by zbbkeepgoing** [comment]
> Hey @zbbkeepgoing, was this a previous datasource existing in Grafana or did you create a new one? I'm asking because it would have incorrectly saved the cloud as a `[object] [object]` instead of the cloud name. Checking to see if it needs to be reselected and saved. I do not have China credentials but when I switch to the China cloud, I can see that the bearer is correct:
> `Www-Authenticate: Bearer authorization_uri="https://login.chinacloudapi.cn/"`
> 
> <img alt="Screen Shot 2019-11-12 at 6 08 26 PM" width="762" src="https://user-images.githubusercontent.com/3074595/68718848-7d064a00-0578-11ea-9feb-cd25785f315c.png">

Hi @shavonn  I restart the grafana(docker run and not mount the data to hostpath)  And add the azure china cloud provider datasource. Just the same .
![image](https://user-images.githubusercontent.com/42572980/68733437-96a7a000-0611-11ea-9ab9-f322f52cd7e2.png)

I think the API I'm focusing on is different from yours. I mean, there's a 401 problem with the metadata API. not the api of your picture

**Comment by davliu82** [comment]
@shavonn I uninstalled the old version, installed the latest version v6.6.0-pre, and create a new data source to connect with Azure Monitor and Log Analytics in Azure China. Azure Monitor can work, but **Log Analytics** still have problem:
**Www-Authenticate**:   Bearer authorization_uri="https://login.microsoftonline.com/common"
**Error**:   {"error":{"message":"Valid authentication was not provided","code":"AuthorizationRequiredError"}}

![image](https://user-images.githubusercontent.com/8144963/68736578-f014cc80-061b-11ea-9197-6eb7f981d69d.png)

**Comment by shavonn** [comment]
I've found that the issue is due to the `same as` block in `plugin.json` (it is always using the azure public cloud as it is now). Now that variables are allowed in plugin.json, it needs to be rewritten to remove the hard-coded values there now. We should look to have this fixed in 6.6.

**Comment by zbbkeepgoing** [comment]
> I've found that the issue is due to the `same as` block in `plugin.json` (it is always using the azure public cloud as it is now). Now that variables are allowed in plugin.json, it needs to be rewritten to remove the hard-coded values there now. We should look to have this fixed in 6.6.

@shavonn Because our grafana only needs to run in china region. So can we make the master branch work properly by modifying the hard-coded? Can you give us some advice?

**Comment by davliu82** [comment]
@shavonn same question with @zbbkeepgoing. we are currently blocked by the log analytics connection issue. Can you please give a priority to fix it as soon as possible and give a pre-release? or advice how to fix by myself?

**Comment by shavonn** [comment]
> > I've found that the issue is due to the `same as` block in `plugin.json` (it is always using the azure public cloud as it is now). Now that variables are allowed in plugin.json, it needs to be rewritten to remove the hard-coded values there now. We should look to have this fixed in 6.6.
> 
> @shavonn Because our grafana only needs to run in china region. So can we make the master branch work properly by modifying the hard-coded? Can you give us some advice?

@zbbkeepgoing to solve this problem for yourself until this is resolved, in this block in `plugin.json`:

```   
 {
      "path": "sameasloganalyticsazure",
      "method": "GET",
      "url": "https://api.loganalytics.io/v1/workspaces",
      "tokenAuth": {
        "url": "https://login.microsoftonline.com/{{.JsonData.tenantId}}/oauth2/token",
        "params": {
          "grant_type": "client_credentials",
          "client_id": "{{.JsonData.clientId}}",
          "client_secret": "{{.SecureJsonData.clientSecret}}",
          "resource": "https://api.loganalytics.io"
        }
      },
      "headers": [
        { "name": "x-ms-app", "content": "Grafana" },
        { "name": "Cache-Control", "content": "public, max-age=60" },
        { "name": "Accept-Encoding", "content": "gzip" }
      ]
    }
```
Change `https://login.microsoftonline.com` in this block to `https://login.chinacloudapi.cn`.

**Comment by zbbkeepgoing** [comment]
> tps://login.chinacloudapi.cn
@shavonn 
Get it , i will try it . Thx

**Comment by zbbkeepgoing** [comment]
> > > I've found that the issue is due to the `same as` block in `plugin.json` (it is always using the azure public cloud as it is now). Now that variables are allowed in plugin.json, it needs to be rewritten to remove the hard-coded values there now. We should look to have this fixed in 6.6.
> > 
> > 
> > @shavonn Because our grafana only needs to run in china region. So can we make the master branch work properly by modifying the hard-coded? Can you give us some advice?
> 
> @zbbkeepgoing @davliu82 to solve this problem for yourself until this is resolved, in this block in `plugin.json`:
> 
> ```
>  {
>       "path": "sameasloganalyticsazure",
>       "method": "GET",
>       "url": "https://api.loganalytics.io/v1/workspaces",
>       "tokenAuth": {
>         "url": "https://login.microsoftonline.com/{{.JsonData.tenantId}}/oauth2/token",
>         "params": {
>           "grant_type": "client_credentials",
>           "client_id": "{{.JsonData.clientId}}",
>           "client_secret": "{{.SecureJsonData.clientSecret}}",
>           "resource": "https://api.loganalytics.io"
>         }
>       },
>       "headers": [
>         { "name": "x-ms-app", "content": "Grafana" },
>         { "name": "Cache-Control", "content": "public, max-age=60" },
>         { "name": "Accept-Encoding", "content": "gzip" }
>       ]
>     }
> ```
> 
> Change `https://login.microsoftonline.com` in this block to `https://login.chinacloudapi.cn`.

Hi,@shavonn 
I change the endpoint in plugin.json. It work in china region. There should be **nine** changes . So please pay attention to these. The file url which i changed: https://github.com/zbbkeepgoing/grafana/commit/94bbe06a21e17810d9fe896adc9edc19d141694c
Looking forward to a new version
