### ISSUE TITLE
influxdb 0.9 `GROUP BY time($interval)` incorrect for sub-second

### ISSUE THREAD

**Issue by ccutrer** [grafana/grafana#2183]
when I zoom in too far on an influxdb graph that has `GROUP BY time($interval)`, it generates `GROUP BY time(0.1s)`, which influxdb 0.9 rejects. changing the query manually to `GROUP BY time(100ms)` works.

I'm using grafana 2.0.2 and influxdb 0.9 (final)

**Comment by torkelo** [comment]
fixed in master :)

**Comment by ccutrer** [comment]
:+1:

just an FYI that requirejs optimization is busted on current master - I had to go back a few commits to get it to work

**Comment by torkelo** [comment]
@ccutrer that is strange, grunt release works fine and the optimized build results works fine.  Do you get an error?

**Comment by ccutrer** [comment]
Just pulled latest master (for the single stat fix), and I'm still getting errors in the requirejs:build:

`go run build.go build package`

```
Running "requirejs:build" (requirejs) task
{ [Error: Error: Module loading did not complete for: app, angular, angular-route, angular-sanitize, angular-strap, angular-dragdrop, extend-jquery, bindonce, s
ervices/all, services/alertSrv, services/utilSrv, services/datasourceSrv, services/contextSrv, services/timer, services/keyboardManager, services/analytics, ser
vices/popoverSrv, services/backendSrv, features/all, features/panellinks/module, features/panellinks/linkSrv, features/dashlinks/module, features/annotations/an
notationsSrv, features/annotations/editorCtrl, features/templating/templateSrv, features/templating/editorCtrl, features/templating/templateValuesSrv, features/
dashboard/all, features/dashboard/dashboardCtrl, features/dashboard/dashboardLoaderSrv, features/dashboard/dashboardNavCtrl, features/dashboard/snapshotTopNavCt
rl, features/dashboard/saveDashboardAsCtrl, features/dashboard/playlistCtrl, features/dashboard/rowCtrl, features/dashboard/shareModalCtrl, features/dashboard/s
hareSnapshotCtrl, features/dashboard/submenuCtrl, features/dashboard/dashboardSrv, features/dashboard/keybindings, features/dashboard/viewStateSrv, features/das
hboard/playlistSrv, features/dashboard/timeSrv, features/dashboard/unsavedChangesSrv, features/dashboard/directives/dashSearchView, features/dashboard/graphiteI
mportCtrl, features/dashboard/dynamicDashboardSrv, features/dashboard/importCtrl, features/panel/all, features/panel/panelMenu, features/panel/panelDirective, f
eatures/panel/panelSrv, features/panel/panelHelper, features/panel/soloPanelCtrl, features/profile/profileCtrl, features/profile/changePasswordCtrl, features/or
g/all, features/org/datasourcesCtrl, features/org/datasourceEditCtrl, features/org/orgUsersCtrl, features/org/newOrgCtrl, features/org/orgApiKeysCtrl, features/
org/orgDetailsCtrl, features/admin/all, features/admin/adminUsersCtrl, features/admin/adminEditUserCtrl, features/admin/adminSettingsCtrl, directives/all, direc
tives/arrayJoin, directives/dashUpload, directives/grafanaSimplePanel, directives/ngBlur, directives/dashEditLink, directives/ngModelOnBlur, directives/misc, di
rectives/confirmClick, directives/configModal, directives/spectrumPicker, directives/tags, directives/bodyClass, directives/valueSelectDropdown, directives/metr
ic.segment, directives/grafanaVersionCheck, directives/dropdown.typeahead, directives/topnav, directives/giveFocus, directives/annotationTooltip, directives/pas
swordStrenght, filters/all, controllers/all, controllers/grafanaCtrl, controllers/pulldown, controllers/search, controllers/metricKeys, controllers/inspectCtrl,
 controllers/jsonEditorCtrl, controllers/loginCtrl, controllers/resetPasswordCtrl, controllers/sidemenuCtrl, controllers/errorCtrl, routes/all, routes/dashLoadC
ontrollers, components/partials, plugins/datasource/grafana/datasource, plugins/datasource/graphite/datasource, plugins/datasource/graphite/queryCtrl, plugins/d
atasource/graphite/funcEditor, plugins/datasource/graphite/addGraphiteFunc, plugins/datasource/influxdb_08/datasource, plugins/datasource/influxdb_08/queryCtrl,
 plugins/datasource/influxdb_08/funcEditor, panels/dashlist/module, panels/graph/module, panels/graph/seriesOverridesCtrl, panels/graph/graph, panels/graph/lege
nd, panels/singlestat/module, panels/singlestat/singleStatPanel, panels/text/module, panels/timepicker/module
    at Function.build.checkForErrors (/home/cody/gocodez/src/github.com/grafana/grafana/node_modules/requirejs/bin/r.js:29387:19)
]
  originalError: [Error: Module loading did not complete for: app, angular, angular-route, angular-sanitize, angular-strap, angular-dragdrop, extend-jquery, bin
donce, services/all, services/alertSrv, services/utilSrv, services/datasourceSrv, services/contextSrv, services/timer, services/keyboardManager, services/analyt
ics, services/popoverSrv, services/backendSrv, features/all, features/panellinks/module, features/panellinks/linkSrv, features/dashlinks/module, features/annota
tions/annotationsSrv, features/annotations/editorCtrl, features/templating/templateSrv, features/templating/editorCtrl, features/templating/templateValuesSrv, f
eatures/dashboard/all, features/dashboard/dashboardCtrl, features/dashboard/dashboardLoaderSrv, features/dashboard/dashboardNavCtrl, features/dashboard/snapshot
TopNavCtrl, features/dashboard/saveDashboardAsCtrl, features/dashboard/playlistCtrl, features/dashboard/rowCtrl, features/dashboard/shareModalCtrl, features/das
hboard/shareSnapshotCtrl, features/dashboard/submenuCtrl, features/dashboard/dashboardSrv, features/dashboard/keybindings, features/dashboard/viewStateSrv, feat
ures/dashboard/playlistSrv, features/dashboard/timeSrv, features/dashboard/unsavedChangesSrv, features/dashboard/directives/dashSearchView, features/dashboard/g
raphiteImportCtrl, features/dashboard/dynamicDashboardSrv, features/dashboard/importCtrl, features/panel/all, features/panel/panelMenu, features/panel/panelDire
ctive, features/panel/panelSrv, features/panel/panelHelper, features/panel/soloPanelCtrl, features/profile/profileCtrl, features/profile/changePasswordCtrl, fea
tures/org/all, features/org/datasourcesCtrl, features/org/datasourceEditCtrl, features/org/orgUsersCtrl, features/org/newOrgCtrl, features/org/orgApiKeysCtrl, f
eatures/org/orgDetailsCtrl, features/admin/all, features/admin/adminUsersCtrl, features/admin/adminEditUserCtrl, features/admin/adminSettingsCtrl, directives/al
l, directives/arrayJoin, directives/dashUpload, directives/grafanaSimplePanel, directives/ngBlur, directives/dashEditLink, directives/ngModelOnBlur, directives/
misc, directives/confirmClick, directives/configModal, directives/spectrumPicker, directives/tags, directives/bodyClass, directives/valueSelectDropdown, directi
ves/metric.segment, directives/grafanaVersionCheck, directives/dropdown.typeahead, directives/topnav, directives/giveFocus, directives/annotationTooltip, direct
ives/passwordStrenght, filters/all, controllers/all, controllers/grafanaCtrl, controllers/pulldown, controllers/search, controllers/metricKeys, controllers/insp
ectCtrl, controllers/jsonEditorCtrl, controllers/loginCtrl, controllers/resetPasswordCtrl, controllers/sidemenuCtrl, controllers/errorCtrl, routes/all, routes/d
ashLoadControllers, components/partials, plugins/datasource/grafana/datasource, plugins/datasource/graphite/datasource, plugins/datasource/graphite/queryCtrl, p
lugins/datasource/graphite/funcEditor, plugins/datasource/graphite/addGraphiteFunc, plugins/datasource/influxdb_08/datasource, plugins/datasource/influxdb_08/qu
eryCtrl, plugins/datasource/influxdb_08/funcEditor, panels/dashlist/module, panels/graph/module, panels/graph/seriesOverridesCtrl, panels/graph/graph, panels/gr
aph/legend, panels/singlestat/module, panels/singlestat/singleStatPanel, panels/text/module, panels/timepicker/module] }
exit status 1
exit status 1
```

I should note that I've been compiling and running on Ubuntu Trusty 14.04 on armhf architecture (a raspberry pi 2; NOT running raspbian, but true ubuntu). I don't know how architecture could be relevant to the js part of the build, though.

**Comment by torkelo** [comment]
try npm install or npm update before

**Comment by torkelo** [comment]
I just pushed out new pre release builds (http://grafana.org/download/builds.html) without issue, must be something wrong with your npm modules.

**Comment by ccutrer** [comment]
Nope, same error. `npm install` then packaging failed. `npm update` then packaging failed. `rm -rf node_modules && npm install` then packaging failed. I'm not much of a javascript guy (mostly ruby and C/C++); any tips you can give me to try and figure this out? I'm using node version 0.12.4, and npm 2.10.1 (the nodesource debs).

**Comment by torkelo** [comment]
@ccutrer I do not know what could be the reason for your error, just upgraded to nodejs 0.12.4 and npm 2.10.1 and the build works without error (on Ubuntu 14.10) 

Maybe your nodejs version or npm version is broken, or your disk is too slow, have no clue, the error is not very detailed  :(

**Comment by papylhomme** [comment]
I ran into this problem trying to compile grafana on an ArchLinux powered RaspberryPI. Thanks for you're insight on "or your disk is too slow", that was it. Resolved by adding "waitSeconds: 0" to the "tasks/options/requirejs.js"

**Comment by ccutrer** [comment]
@papylhomme You're a lifesaver! I even tried finding a timeout setting for requirejs, and I couldn't find one. @torkelo any chance we could get that tweak committed to the main repo, to prevent this problem for other people on the future compiling Grafana on embedded systems?

**Comment by torkelo** [comment]
@ccutrer PR please :)

**Comment by papylhomme** [comment]
PR done : https://github.com/grafana/grafana/pull/2539
