### ISSUE TITLE
CloudWatch queries using variables and set IDs are not referable 

### ISSUE THREAD

**Issue by jpmontez** [grafana/grafana#23871]
**What happened**:
When using a variable to set an AWS data source, along with setting an `id` for a CloudWatch query, a 400 status code error is returned. The error message states that the `id`s previously set cannot be found.

Even if you set the AWS data source back to a hard-coded, non-variable setting, the query still breaks.

I've compared the query inspector output for a "fresh", non-variable data source and one that's been modified with a variable and back and the request queries seem identical.

**What you expected to happen**:
For the queries with a variable data source to succeed and be referable via the `id` parameter. Subsequent metric math using `id`s should be possible.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a variable for an AWS data source.
2. Create a panel with for a CloudWatch query using the variable as a data source.
3. Make any query, and assign it an `id`.
4. Create a new, empty query and reference the previously assigned `id.
5. You should see a 400 response code.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.6.2
- Data source type & version: CloudWatch 
- OS Grafana is installed on: Unknown
- User OS & Browser: Firefox, Chrome
- Grafana plugins: Unknown
- Others:

**Comment by jpmontez** [comment]
This seems related: https://github.com/grafana/grafana/issues/18337

**Comment by szymonpk** [comment]
@jpmontez check if both queries have same region set up.

**Comment by EXPEylazzari** [comment]
I also have a similar problem:

<img width="1553" alt="Screen Shot 2020-05-01 at 12 12 55 PM" src="https://user-images.githubusercontent.com/17257672/80820689-5f1fb680-8ba5-11ea-9b4c-8282d13b0f6a.png">

The two queries are in the same region. In my case, the query doesn't return an HTTP 400 error, but an empty results element. We're using Grafana v6.4.5 (62b53c3). Replacing the variables with actual values yields the expected results.

**Comment by papagian** [comment]
@jpmontez 
The query referencing the `a` query should have the same Region set.

**Comment by jpmontez** [comment]
> @jpmontez check if both queries have same region set up.

> @jpmontez
> The query referencing the `a` query should have the same Region set.

Hey folks, thanks for replying. The same region is being set.

**Comment by papagian** [comment]
@EXPEylazzari 
this should be fixed in grafana 6.5.0. Can you try upgrading to a newer grafana version and verifying it?

**Comment by papagian** [comment]
> > @jpmontez check if both queries have same region set up.
> 
> > @jpmontez
> > The query referencing the `a` query should have the same Region set.
> 
> Hey folks, thanks for replying. The same region is being set.

Can you send the output of the query inspector?

**Comment by jpmontez** [comment]
> @EXPEylazzari
> this should be fixed in grafana 6.5.0. Can you try upgrading to a newer grafana version and verifying it?

I’m on v6.6.2, per my first post.

> > > @jpmontez check if both queries have same region set up.
> > 
> > 
> > > @jpmontez
> > > The query referencing the `a` query should have the same Region set.
> > 
> > 
> > Hey folks, thanks for replying. The same region is being set.
> 
> Can you send the output of the query inspector?

Yeah, I’ll post the query once I’m at work.

**Comment by torkelo** [comment]
closing due to lack of updates

**Comment by mb-dev** [comment]
@torkelo I am also experiencing this on grafana 7.3.5. can this issue or https://github.com/grafana/grafana/issues/18337 be reopened? multiple people are reporting that this is still happening.

The first query by itself works. as soon as I add B with sum of A it fails.

This is my query inspector. I renamed private information and `asg1` comes from a variable.
```
{
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1610723871408",
      "to": "1610734671408",
      "queries": [
        {
          "intervalMs": 5000,
          "maxDataPoints": 1460,
          "datasourceId": 271,
          "type": "timeSeriesQuery",
          "namespace": "CWAgent",
          "metricName": "metricA",
          "expression": "",
          "dimensions": {
            "AutoScalingGroupName": [
              "asg1"
            ]
          },
          "region": "us-west-2",
          "id": "a",
          "alias": "",
          "statistics": [
            "Sum"
          ],
          "period": "",
          "refId": "A",
          "matchExact": true,
          "datasource": "(aws account id)"
        },
        {
          "intervalMs": 5000,
          "maxDataPoints": 1460,
          "datasourceId": 271,
          "type": "timeSeriesQuery",
          "namespace": "",
          "metricName": "",
          "expression": "SUM(a)",
          "dimensions": {},
          "region": "us-west-2",
          "id": "",
          "alias": "",
          "statistics": [
            "Average"
          ],
          "period": "",
          "refId": "B",
          "matchExact": true,
          "datasource": "(aws account id)"
        }
      ]
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "error": "ValidationError: Error in expression 'queryB': The return value of the expression must be TimeSeries or Array[TimeSeries]\n\tstatus code: 400, request id: 3af5886a-24ed-496b-989e-c5da88126d49",
        "refId": "A",
        "series": null,
        "tables": null,
        "dataframes": null
      },
      "B": {
        "error": "ValidationError: Error in expression 'queryB': The return value of the expression must be TimeSeries or Array[TimeSeries]\n\tstatus code: 400, request id: 3af5886a-24ed-496b-989e-c5da88126d49",
        "refId": "B",
        "series": null,
        "tables": null,
        "dataframes": null
      }
    },
    "message": "ValidationError: Error in expression 'queryB': The return value of the expression must be TimeSeries or Array[TimeSeries]\n\tstatus code: 400, request id: 3af5886a-24ed-496b-989e-c5da88126d49"
  }
}
```

**Comment by mb-dev** [comment]
I opened a new issue about this ^
