### ISSUE TITLE
Provisioned dashboards/folders don't show in Grafana UI 

### ISSUE THREAD

**Issue by izavadynskyi** [grafana/grafana#24943]
**What happened**:
Provisioned dashboards stored in k8s configmap don't show in Grafana UI and folders.
But we have possibility to find them in find field and open. Also in "Manage" dashboards window we can find provisioned dashboards and folders when type the dashboards/folders name.

This issue happens after we upload dashboard backup dump in grafana mysql database.

**What you expected to happen**:
We want to see all dashboards separated in folders when we open home page. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure dashboards provision on k8s.
2. Upload dump with dashboards in dashboard table.
3. Check if we have provisioned dashboards in Grafana UI.

**Anything else we need to know?**:

**Environment**: k8s
- Grafana version: 6.7.3 (a04ef6cefc)
- Data source type & version: Prometheus
- OS Grafana is installed on: ubuntu
- User OS & Browser: Windows/ Chrome
- Grafana plugins: zabbix, world map panel 
- Others: Grafana use the mysql database as a persistence volume to store all data.

**Comment by torkelo** [comment]
Not sure I understand, do you have dashboard that come both from provisioning and DB? 

> Upload dump with dashboards in dashboard table. 

What does this mean? is this new dashboard that are not provisioning? Which area not shown in UI? 

> But we have possibility to find them in find field and open.

What does mean? You find the dashboard but not the folderS? 

I am very confused

**Comment by izavadynskyi** [comment]
Hi.
Sorry for not so clear description of problem.

We use the Grafana helm deployment with provisioned dashboard inside helm chart.

All dashboard are stored  also in mysql grafana DB that connected to the Grafana container.
The dump of dashboard table we uploaded to new Grafana DB because we were migrating from old Grafana service that were run on Linux virtual server and had to uploaded old dashboards to new Grafana in container.
And after that action we don't see provisioned dashboards in the Grafana UI home page but we can open them when using the url or when finding the dashboard/folder name in search field.

By the way after deleting not needed dashboards through Grafana UI the issue was resolved.

Maybe was some glitch.

**Comment by torkelo** [comment]
I still do not understand

> And after that action we don't see provisioned dashboards in the Grafana UI home page 

In dashboard list panel on the default home dashboard?

You can find them in search and open them, but not not find them where?

I do not understand what your talking about DB dashboards & provisioned dashboards, this is very confusing. Provisioning takes dashboard from disk and stores them in db and syncs changes from disk to db, if you remove them from disk they will disapper, if you copy db to another instance without any provisioned files they will be removed

**Comment by izavadynskyi** [comment]
Hi.
Now the issue was fixed after deleting old dashboards.
Thank you.
