### ISSUE TITLE
InfluxDB: improve the UX for InfluxDB 1.8 so it does not require Organization

### ISSUE THREAD

**Issue by danieldonoghue** [grafana/grafana#26397]
**Steps to reproduce:**

1. create a new datasource for InfluxDB (using InfluxDB 1.8 with flux enabled)
2. set query language to "flux"
3. click "save and test"

**Expected behavior:**

data source should be connected.

**Actual behavior:**

receive error message "Error reading InfluxDB". According to the logs, this is because "missing organization in datasource configuration" but organisations are only relevant to influxDB 2. The same setup works correctly using the influxdb-flux-datasource plugin.

**Environment info:**

running docker image grafana/grafana:latest (currently at 7.1.0)
running influxDB 1.8 with flux enabled

**Logs:**
```
t=2020-07-17T08:52:31+0000 lvl=info msg=query logger=tsdb.influxdb q=[0xc000dd1d00]
t=2020-07-17T08:52:31+0000 lvl=eror msg="Metric request error" logger=context userId=2 orgId=1 uname=XXXXXX error="missing organization in datasource configuration" remote_addr=XXXXX
t=2020-07-17T08:52:31+0000 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=XXXXXX method=POST path=/api/ds/query status=500 remote_addr=XXXXXX time_ms=0 size=34 referer=https://XXXXXX/datasources/edit/13/
````

**Comment by ryantxu** [comment]
As a workaround just put any value into the organization field.

We will fix this in the UI

**Comment by mertbakir** [comment]
Normally we enter username/password for 1.8. Where to enter credentials for Flux with 1.8.x?

**Comment by mertbakir** [comment]
> > Where to enter credentials for Flux with 1.8.x?
> 
> enter u:p into the token field

It still returns "Error reading InfluxDB"

**Comment by cdfuller** [comment]
@mertbakir Which version of InfluxDB are you on? It sounds like you could be running to this issue which was resolved in 1.81.
https://github.com/grafana/grafana/issues/26051

**Comment by rafecolton** [comment]
I am seeing the same issue with Influx 1.8.1

**Comment by mertbakir** [comment]
@cdfuller I am on 1.8.1.

**Comment by andig** [comment]
Need to add that on 7.1, even if datasource is configured to Flux, dashboard variables still don't support flux. Also highly un-intuitive...

**Comment by danieldonoghue** [comment]
> As a workaround just put any value into the organization field.
> 
> We will fix this in the UI

I tried that and the issue persists.

**Comment by rafecolton** [comment]
Took a while to get this to work, but I was finally able to do so with 1.8.1. I had to reverse engineer the code to figure out how to configure the datasource in a file instead of the UI. The hardest part was figuring out the full path on the URL, which I could not find documented anywhere in Grafana. Here's the configuration that worked:

```yaml
- name: Whatever
  type: influxdb
  url: https://<host>:8086/api/v2/query
  jsonData:
    editable: false
    version: Flux
    defaultBucket: telegraf/autogen
    organization: non-empty
  secureJsonData:
    token: <username>:<password>
```

It would be great if you could add an example to your docs with all of the configuration options.

**Comment by zoltanbedi** [comment]
@oddlittlebird Can you help with this?

**Comment by danieldonoghue** [comment]
I too was able to get this to work. an additional error creating the source was that the first time I clicked save and test, it reported an error but if I clicked it again, it completed successfully.

**Comment by oddlittlebird** [comment]
> It would be great if you could add an example to your docs with all of the configuration options.

Please file this as a doc PR.

**Comment by mirellou** [comment]
Hello everyone,

We also get the same issue. 

I add a flux datasource and I get the "error reading influxdb".

![image](https://user-images.githubusercontent.com/65293215/88162947-4528c980-cc12-11ea-9d4b-6bc3f3e43016.png)

Even though, I tried on a dashboard to see if it is going to work and when I add the Flux query, I get the following error "Metric request error". Therefore, the query does not work. 

Do you have any solution on that? 

br,
Mirella

**Comment by mertbakir** [comment]
Hi @mirellou, configure as @rafecolton suggested a few comments above. It works.

**Comment by mirellou** [comment]
Hi @mertbakir,

That is not the problem. The problem is that if I write a very simple query like the following then the query will work correctly. 

![image](https://user-images.githubusercontent.com/65293215/88173380-c2f4d100-cc22-11ea-9f8a-d5f5c6ea8b3f.png)

The moment that I will add a more complex flux query, it will crush and give me the error of my previous message "Metric request error".
For instance I added the 'groub by' and it crushed because of that. 
I refreshed it again and it worked. 
Later I added the keep columns and it crushed again. 
|> keep(columns: ["_measurement", "_value"])

Therefore, it does not respond correctly in complex queries. 

Do you have any advice on that? 

Thank you in advance. 

Best regards,
Mirella

**Comment by danieldonoghue** [comment]
> Hi @mertbakir,
> 
> That is not the problem. The problem is that if I write a very simple query like the following then the query will work correctly.
> 
> ![image](https://user-images.githubusercontent.com/65293215/88173380-c2f4d100-cc22-11ea-9f8a-d5f5c6ea8b3f.png)
> 
> The moment that I will add a more complex flux query, it will crush and give me the error of my previous message "Metric request error".
> For instance I added the 'groub by' and it crushed because of that.
> I refreshed it again and it worked.
> Later I added the keep columns and it crushed again.
> |> keep(columns: ["_measurement", "_value"])
> 
> Therefore, it does not respond correctly in complex queries.
> 
> Do you have any advice on that?
> 
> Thank you in advance.
> 
> Best regards,
> Mirella

take a careful look at your query and, specifically, the columns being returned. when this happened to me, I used tcpdump to see the response going back to grafana from influxdb and could clearly see my data but it wasn't formatted the same way (was missing columns) as a simple query.

**Comment by mirellou** [comment]
Hi @danieldonoghue ,

Thank you for your response! I do not think that the columns are the problem in my case .. 

The query returned just fine the right columns when I tested it in Chronograph. 

I believe that the problem is that not all the functions work correctly or that it cannot handle more complex queries. 

Best regards,
Mirella

**Comment by Hircus** [comment]
Hi everyone, i'm new with this kind of technologies. I have the same problem and i tried to configure the file etc/grafana/grafana.ini like @rafecolton suggested, but i'm missing something. Is it the right config file? What fields do i have to change? Thanks you for your help

**Comment by mertbakir** [comment]
> Hi everyone, i'm new with this kind of technologies. I have the same problem and i tried to configure the file etc/grafana/grafana.ini like @rafecolton suggested, but i'm missing something. Is it the right config file? What fields do i have to change?
> Thanks you for your help

As far as I know there is no way to configure influxdb in grafana.ini. You can use the GUI. ```Configuration > Data Sources > Add data source```

**Comment by Hircus** [comment]
> > Hi everyone, i'm new with this kind of technologies. I have the same problem and i tried to configure the file etc/grafana/grafana.ini like @rafecolton suggested, but i'm missing something. Is it the right config file? What fields do i have to change?
> > Thanks you for your help
> 
> As far as I know there is no way to configure influxdb in grafana.ini. You can use the GUI. `Configuration > Data Sources > Add data source`

![Schermata del 2020-07-27 15-30-27](https://user-images.githubusercontent.com/48201861/88547529-2e251580-d01e-11ea-976d-e790204f5103.png)
Hi! That is what i am trying to do but with no results and i have no idea how to use @rafecolton solution

**Comment by mertbakir** [comment]
Are you trying to connect Influx 1.8.X or 2.0?

I'm guessing it's 2.0 since the port is ```9999```. I don't have influx 2.0 right now, so I can't check but the suggested configuration is for 1.8.X.

For 2.0: you'll have a token. It's provided in influxdb gui. So, you do not enter ```<user>:<passwd>``` Also you should enter the bucket name and organization name correctly.

Check this: https://v2.docs.influxdata.com/v2.0/visualize-data/other-tools/grafana/

**Comment by Hircus** [comment]
Yes it's 2.0 but i already tried everything: 
i checked the token in InfluxDb LoadData/Tokens and pasted in the token field, entered Organization and Bucket of my Influxdb, as the docs suggest, but the error was still there. 

Literally full days stuck with all kind of errors from Influxdb, Telegraf and Grafana. 
Then i tried the good old trial and error with all i could find.

Somethng i noticed that after saving the configuration, the log does not report errors, as shown in the image below
![Schermata del 2020-07-27 16-20-51](https://user-images.githubusercontent.com/48201861/88553409-8ad7fe80-d025-11ea-88a7-1ce2358d4968.png)

This is the configuration that i first tried
![Schermata del 2020-07-27 16-21-14](https://user-images.githubusercontent.com/48201861/88553410-8c092b80-d025-11ea-84d8-5d0fe083551d.png)

thank you for your time

**Comment by mirellou** [comment]
@Hircus Hello 

I still have the same issue as you and I have tried everything that the other people suggested, therefore I still believe that there is a bug. 

In any case, let's hope that it will be solved or we will have a solution soon. 

Br,
Mirella

**Comment by Hircus** [comment]
Yes, i hope so. I think the best solution for now is to install version 1.x and try to work with that, hoping in a smooth configuration

**Comment by rafecolton** [comment]
@Hircus It looks like you have not followed the configuration options, and that is probably why it's not working. Notice that the URL in your screenshot is different from the one in the config I provided. That or it's something related to 2.0, which I cannot confirm, as I am using 1.8.1.

The YAML example was added in a custom datasources YAML file as documented [here](https://grafana.com/docs/grafana/latest/administration/provisioning/), but you can do it in the UI too. It works as long as you use the correct configuration values. You should also be able to test on the command line, as that tends to provide more helpful error messages than the Grafana UI

**Comment by torkelo** [comment]
@kylebrandt @ryantxu is there anything we can do here?

**Comment by Hircus** [comment]
> @Hircus It looks like you have not followed the configuration options, and that is probably why it's not working. Notice that the URL in your screenshot is different from the one in the config I provided. That or it's something related to 2.0, which I cannot confirm, as I am using 1.8.1.
> 
> The YAML example was added in a custom datasources YAML file as documented [here](https://grafana.com/docs/grafana/latest/administration/provisioning/), but you can do it in the UI too. It works as long as you use the correct configuration values. You should also be able to test on the command line, as that tends to provide more helpful error messages than the Grafana UI

Hi thank you for your help! Actually the config i used are the ones provided by the docs and what i found online. I managed to find the yaml, with the help of the docs you kindly linked, but it didnt work. I am now switching to 1.8.1, lets see

**Comment by Hircus** [comment]
Hi all, i tried with influx cloud, basically influx 2.0, and worked no problem!

**Comment by mirellou** [comment]
We upgraded influx from 1.8.0 version to 1.8.1 version and it seems to work fine now. We do not get an error on saving the data source or when we add a complex Flux query on our dashboards!

**Comment by torkelo** [comment]
ok, closing this as it seems to work now

**Comment by Zincr0** [comment]
Same bug with influxdb 1.8.2, cannot add a datatasource using flux.

**Comment by MartynKeigher** [comment]
Hmmm.... still not working in the following setup...

- Grafana: 7.3.0
- InfluxDB 2.0 (RC) and\or Influx 2.0 (beta)

Anyone out there managed to get this work in this setup? I have been battling this one now for HOURS!!

Thanks.

**Comment by PeeJay** [comment]
Just noticed for 1.8.x you need to enter a username:password even when not using authentication.

**Comment by kumters** [comment]
That GUI is still broken somehow (no TLS CA skip and so on), you have to create a provisioning YAML config file and place it to /etc/grafana/conf/provisioning/ (don't forget to chown rights to grafana group). Do restart of grafana and Woala it's there and test button works:)

My yaml file:
apiVersion: 1

datasources:
  - name: InfluxDB_v2
    type: influxdb
    access: proxy
    url: **https**://localhost:8086
    secureJsonData:
      token: USER:PASSWORD
    jsonData:
      version: Flux
      organization: **admin**
      defaultBucket: **telegraf**
      tlsSkipVerify: **true**

**Comment by samualg** [comment]
Agree with mirellou. During planning the migration to Flux, I had the same issue with 1.8.0. Upgraded to 1.8.3 and the Save and test database error was fixed.  Grafana is now able to save during the Save and Test and recognises the bucket.
I noted that you need to enter "" for Organisation (as it is not supported in 1.8.x) and "" for token (when not using authentication). Both these entries worked for me.

**Comment by Kungitoo** [comment]
Could we please get some clarity on the 1.8 scenario?
Could it please also be updated here https://grafana.com/docs/grafana/latest/datasources/influxdb/ ?
I have a 1.8.3 influxdb which I've been using through influxql successfully for a while, and now I cannot create a grafana connection using the flux option. The db doesn't have a password so all I enter is the url. Am I missing something?

**Comment by samualg** [comment]
@Kungitoo 
> Could we please get some clarity on the 1.8 scenario?
> Could it please also be updated here https://grafana.com/docs/grafana/latest/datasources/influxdb/ ?
> I have a 1.8.3 influxdb which I've been using through influxql successfully for a while, and now I cannot create a grafana connection using the flux option. The db doesn't have a password so all I enter is the url. Am I missing something?

It is not clear where you are having difficulties. In 1.8.3, You enter "" for organisation and "" for the Token as you said you dont use credentials.
So Set the datasource to Influx and then choose flux from the Query Language dropdown. 
The URL is the URL of your datasource - this will probably be the same as the Influxdb.
The organisation is ""  ...... literally type 2 double quotes.
The token is "" (as org).
Default bucket - Mine was telegraf - the same as my influxdb database .....this is what ever your bucket is.

**Comment by Kungitoo** [comment]
I missed in all these messages that the token should also be "" (weird)

**Comment by larsxschneider** [comment]
I did run into the same problem with InfluxDB 1.8.10 and I made it work with _only_ the following settings:

URL: `http://<IP>:8086` (e.g. `http://192.168.1.10:8086` - the `http://` seems to be important!)
Organization: `any`
Token: `<username>:<password>` (e.g. `admin:mysecret`)
