### ISSUE TITLE
Transformations: able to build table with rows/columns based on labels

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#29393]
**What would you like to be added**:
Transformations look really great and flexible. I'm moving to the data frames usage in Zabbix plugin and wonder if it's possible to build a table-like data based on labels. Example: I get 4 metrics and then result converted to the data frames (wide format):

```
+---------------------+---------------------------+------------------------------+----------------------------+------------------------------+
| Name: time          | Name: cpu user            | Name: cpu system             | Name: cpu user             | Name: cpu system             |
| Labels:             | Labels: host='a',         | Labels: host='a',            | Labels: host='b',          | Labels: host='b',            |
|                     |         metric='cpu user' |         metric: 'cpu system' |         metric: 'cpu user' |         metric: 'cpu system' |
+---------------------+---------------------------+------------------------------+----------------------------+------------------------------+
| 2020-01-02 03:04:00 | 3                         | 4                            | 5                          | 6                            |
| 2020-01-02 03:05:00 | 6                         | 7                            | 3                          | 2                            |
+---------------------+---------------------------+------------------------------+----------------------------+------------------------------+
```

So as you can see, each field contains two labels: host and metric name. I want to reduce each metric and get table with last (or any other possible reduce function) metric value for each host/metric pair:

```
+----------+--------------+-----------------+
| host     | cpu user     |  cpu system     |
+----------+--------------+-----------------+
| a        | 3            | 4               |
| b        | 5            | 6               |
+----------+--------------+-----------------+
```

I've found it's not possible with existing transform functions. I can perform _Reduce_ transformation with _reduce fields_ mode and get values for each host/metric pair, but then I cannot transform it to the table like in example above. So proposal is a new transformation which takes 2 labels as dimensions and builds a table. Here's a graphical representation of that idea:

```
+---------------------+---------------------------+------------------------------+----------------------------+------------------------------+
| Name: time          | Name: cpu user            | Name: cpu system             | Name: cpu user             | Name: cpu system             |
| Labels:             | Labels: host='a',         | Labels: host='a',            | Labels: host='b',          | Labels: host='b',            |
|                     |         metric='cpu user' |         metric: 'cpu system' |         metric: 'cpu user' |         metric: 'cpu system' |
+---------------------+---------------------------+------------------------------+----------------------------+------------------------------+
| 2020-01-02 03:04:00 | 6                         | 7                            | 3                          | 2                            |
| 2020-01-02 03:05:00 | 3                         | 4                            | 5                          | 6                            |
+---------------------+---------------------------+------------------------------+----------------------------+------------------------------+

Reduce fields (last)
  ||
  \/

+---------------------------+------------------------------+----------------------------+------------------------------+
| Name: cpu user            | Name: cpu system             | Name: cpu user             | Name: cpu system             |
| Labels: host='a',         | Labels: host='a',            | Labels: host='b',          | Labels: host='b',            |
|         metric='cpu user' |         metric: 'cpu system' |         metric: 'cpu user' |         metric: 'cpu system' |
+---------------------------+------------------------------+----------------------------+------------------------------+
| 3                         | 4                            | 5                          | 6                            |
+---------------------------+------------------------------+----------------------------+------------------------------+

Use host label for the rows and metric label for the columns
  ||
  \/

+----------+--------------+-----------------+
| host     | cpu user     |  cpu system     |
+----------+--------------+-----------------+
| a        | 3            | 4               |
| b        | 5            | 6               |
+----------+--------------+-----------------+
```

**Why is this needed**:
Build overview tables with multiple metrics from different hosts.

**Comment by torkelo** [comment]
HAve you tried using the labels to fields transform?

**Comment by alexanderzobnin** [comment]
Yes, and it doesn't work for that example.

**Comment by UnicodeTreason** [comment]
I have the exact same use case. Need to make a Dashboard to display 3x items for 1-100 Hosts.
This table format feels like the most logical way to display it but seems to be currently impossible to achieve?

**Comment by thamayron** [comment]
I'm facing the same problem here, using boom table, 1 host for tests and 2 or more columns, but does not work, I've created a pattern with "*" as delimiter , because I'm using IPv6 and I can't use ":", but does not work.
![Uploading grafana.png…]()

**Comment by Nastradamus** [comment]
We are really looking forward to this feature too.

**Comment by danieldemoraisgurgel** [comment]
This functionality would be very welcome. It would avoid the need to work with the Boom Table plugin, which today finds itself with several bugs in new versions of Grafana.

**Comment by torkelo** [comment]
This was added in v7 , labels to field transform

**Comment by danieldemoraisgurgel** [comment]
> This was added in v7 , labels to field transform

This still doesn't work as per the example.
Could you give an example of how to implement?

When selecting **Transform** > **Labels to fidels** , **no options found** is displayed.

**Comment by kale1d0code** [comment]
I'm trying to use rows to fields in a similar way, but it will only allow for 1 row of information
my client has requested a table that looks like
```
+----------------+----------------+----------------+----------------+----
| DESCRIPTION    | YEAR - QUARTER | YEAR - QUARTER | YEAR - QUARTER | ETC
+----------------+----------------+----------------+----------------+----
| Val for foo    | 12             | 23             | 8              |
+----------------+----------------+----------------+----------------+----
| Val for bar    | 34             | 12             | 32             |
+----------------+----------------+----------------+----------------+----
| etc            | etc            | etc            | etc            |
```

Ignoring the first column with the descriptor\label for the row (I'm guessing I'll do this with a UNION)

I start with something like
```
+----------------+-----------
|Quarter  | foo | bar | ETC
+----------------+-----------
| YYYY Q1 | 12  | 34  |
+---------------+------------
| YYYY Q2 | 23  | 12  |
+---------------+------------
| YYYY Q3 | 8   | 32  |
+---------------+------------
```


this table is some data from mysql which has been grouped by year and quarter and then reduced with COUNT
but when I use the labels to fields transform it only allows for 1 row of data like

```
+----------------+----------------+----------------+----
|YEAR - QUARTER | YEAR - QUARTER | YEAR - QUARTER | ETC
+----------------+----------------+----------------+----
| 34            | 12             | 32             |
+---------------+----------------+----------------+-----
```


I tried moving the additional counts into a separate query to see if grafana would place them in rows but it put the values in a dropdown at the bottom of the table instead

**Comment by danielsilvapereira** [comment]
Anyone could think of a way without using the boom table?

**Comment by vanimesh** [comment]
I too tried using boom table but its very complex. I am also looking for this feature. If anyone achieved then please let us know :-)

**Comment by vanimesh** [comment]
> HAve you tried using the labels to fields transform?

Yes tried but it shows "No options found"

**Comment by vldbel** [comment]
it was year 2023, we still cannot build a multicolumn table with zabbix data in grafana...

**Comment by ryantxu** [comment]
@alexanderzobnin -- I am pretty sure this is solved with the "Join by labels" transform.

Check (devenv) 

Source:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/705951/210426273-58239038-0d0d-4493-83c1-c19bb09dfa06.png">

With transform:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/705951/210426316-b81467c8-dee2-4afe-8223-61243a71c1b3.png">

**Comment by vldbel** [comment]
@ryantxu, thx. I can confirm - it works. 
Not perfectly - a lot of excessive work for cpu on joining a lot of unneeded data, unfortunatelly. But works.

**Comment by vldbel** [comment]
![image](https://user-images.githubusercontent.com/13711403/210561277-0b09d764-6cf2-4efa-98cf-ae559c6bf668.png)
![image](https://user-images.githubusercontent.com/13711403/210561490-060f102e-c4bf-4281-aa94-af17e4d403f6.png)
![image](https://user-images.githubusercontent.com/13711403/210561661-ee25fd85-d78a-44ab-9b70-24c951feae80.png)

**Comment by thethirstyturtle** [comment]
It would be nice if Grafana continued the work of the Boom Table since it isn't being updated anymore. The Boom Table plugin is amazing and offers so much customization for building a table. We use the Boom Table plugin heavily and it's been amazing. 

It does have a lot of features, which takes time to fully understand, but once you do it's hard to imagine not having it. I still don't understand why Grafana's table Plugin doesn't offer more capability. My favorite feature of the Boom Table is being able to add multiple queries as columns and have different alerting/options based on the label of the column. It's not an all or nothing option. Example: Each Column can have it's own option for how to handle null data, coloring for thresholds, etc. 

https://github.com/yesoreyeram/yesoreyeram-boomtable-panel

**Comment by sgriff96** [comment]
This should be possible with the existing transformations available, please let us know if it's still an issue.
