### ISSUE TITLE
Incorrect bar width for ElasticSearch query 

### ISSUE THREAD

**Issue by sfthomas** [grafana/grafana#3131]
I was setting up a simple count-query to show event occurence - but it seems the bar width is not right, even if I set the histogram interval to a fixed 10s value.
If I add another (e.g Graphite) series, then they look fine (thin bars) together,

Incorrect:
![image](https://cloud.githubusercontent.com/assets/1913456/10938681/61870a74-82fc-11e5-99b5-4883ff1a9c3f.png)

Correct (with workaround):
![image](https://cloud.githubusercontent.com/assets/1913456/10938769/f34e61c8-82fc-11e5-8e5b-076c4161cd5a.png)

**Comment by torkelo** [comment]
this is because Graphite fills missing values with nulls (so the distance between points is 10s), Elasticsearch group by does not add empty buckets for missing values so the distance between two points (which determines the bar width) is not the same as the group by interval

**Comment by sfthomas** [comment]
Okay, but then how do I set up the ElasticSearch query to look right? If there are two events close to each other, the first one can almost get hidden (just like on the first screenshot).
I am no expert, but it feels right to set the bar width to be the same as the bucket interval - otherwise bars may overlap, causing the issue in question.

**Comment by torkelo** [comment]
I agree, this should be fixed somehow.

**Comment by andycarlsonuk** [comment]
The tooltips also display the wrong values if there is a time gap between data points - I think they are displaying the value from the closest data point to the left. I suspect this is the closely related (or the same issue) but there is no mention of tooltips in the bug so far.

I'm sure others have tried but for the record... changing the null behaviour doesn't solve the problem.
