### ISSUE TITLE
Make legend colors consistent across panels

### ISSUE THREAD

**Issue by vitorboschi** [grafana/grafana#3250]
Currently Grafana may assign any color to each timeseries in each panel, so you can have a situation where on panel 1, the Server1 is displayed red, but on the next panel the same server is blue.

making them equal on all panels would better transmit information to the user.

Manually assigning colors using overrides is the only way to make that work in current version, but that is not always possible/desirable (eg. when using templating or tag=*)

**Comment by mtanda** [comment]
+1

**Comment by nopzor1200** [comment]
We run into this too on many of our Dashboards.

One simple solution would be to just consistently hash a color in the existing palette off of legend name/alias. 

The problem with this is that when viewing multiple series, color choice will not be optimal to discern each series individually (a really nice behavior currently).

In some situations it's definitely worth that disadvantage, especially when correlating related metrics in different panels (or even across Dashboards).

Maybe the color choice behavior could be a configurable option (probably on a per Panel basis?)

**Comment by addshore** [comment]
+1

**Comment by torkelo** [comment]
This is a lot trickier than might be expected (so far no one has submitted a PR that solves it). The panels all fetch series async, colors are assigned automatically by the order of the series returned by the metric query or by alias or regex style override. 

Since all queries finish at different times the only way to provide consistent automatic colors for series across panels would be to wait for all panels to complete before rendering the graph or use a hash index based on the series name, the later option is something I have tried but fails to generate good contrasting colors.

**Comment by jportoles** [comment]
>  use a hash index based on the series name, the later option is something I have tried but fails to generate good contrasting colors.

Are you sure this cannot be made to work? As it stands right now, not only panels can appear out of "sync" color-wise, but if a panel has the series "a","b","c","d" and "e", and you remove "b", "c", "d" and "e" automatically change color due to the order based mechanism. A checksum or hash based mechanism that assigns colors based on the series name would solve it all, in theory.

**Comment by torkelo** [comment]
It could be possible, but so far now one has solved it :(

**Comment by jportoles** [comment]
Ok, I'll see if I can have a go at it and submit a PR when I find some time. I think it should be possible while keeping contrast somehow.

**Comment by brycefisher** [comment]
@torkelo -- what if we broke this down into separate problems:

 1. Consistently hashing series names -- that seems simple enough
 2. Coming up with a palette of "good" contrasting colors -- it seems like, this problem can be solved for a small of series (say 10?), but there's no way to get good contrast beyond some threshold (say 30 series). Given that, once we cross some threshold for number of series we give up on good contrast
 3. We do a mapping from series hash value to "good" colors that's remembered per page view.

So, what we solve for is consistent, good contrast within a single "session", but not for all time. Ex: if you refresh the page, you'll get a different set of colors.

**Comment by torkelo** [comment]
We have no 2 since the start, the default palette has contrasting colors (in sequence)

Nr 3 is the hard problem, how map a semi random hash value to a color so that other semi random hash values get good contrasting colors.

**Comment by brycefisher** [comment]
Right! So focusing in on number three I'm imagining an algorithm like this:

* On page load:
   * make an empty ordered list
   * initialize that list of "good" contrasting colors

 * At render time:
   1. for each series:
     a. check if that series is already in our list and return that color value from the map
     b. if series not in list, add to the next open slot in the list
   2. remove any series still in list that are no longer on the graph
   3. iterate over ordered list take the corresponding index from the good colors

---

I think this implementation would guarantee that colors are consistent until they drop the list of series being rendered.

This would _not_ guarrantee consistent colors across page-loads, but to me it's the flickering colors every time the data refreshes that bothers me.

**Comment by torkelo** [comment]
And what if first graph contains 10 series (unique for the dashboard), what colors should the other graphs use (also with unique series names) ?

**Comment by torkelo** [comment]
What you propose could work ok for dashboards with graphs with very few unique series names (counted for the whole dashboard)

**Comment by brycefisher** [comment]
Good question! Hmmm, I'd be inclined to provide a dashboard settting to reuse the same ordered list for all panels or separate ones for each panel... no idea what would be a good default on that.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brycefisher** [comment]
@torkelo -- okay, what if I put together a little github repo with an example algorithm as discussed in https://github.com/grafana/grafana/issues/3250#issuecomment-532361304, that would allow us to test out various edge cases and the lay the foundation for a PR against the appropriate repo. Would that be valuable?

**Comment by mpatel-cpi** [comment]
+ 💯 

This will be super useful since right now we have a lot of panels and having consistent coloring will enable correlating them visually.

**Comment by bwesen** [comment]
This thread was started in 2015 (?), is this not solved yet? I just installed the latest Grafana and immediately ran into this, by group(tag) showing completely inconsisting colors across panels and what's worse, within a panel (if you change some other filter, so the set of tags with data change the color coding will change for all the tags all the time...)

Manually creating Queryies for every tag for every panel seems like a gigantic overkill to solve something that I'd be happy to do completely manually (once) in a tag name => color lookup table for example. Maybe that's available, and I don't know about it :)

**Comment by Dammi87** [comment]
I'm also having this issue with ADX data-source and Grafana.
Currently viewing 8 panels with 5 series in each panel, where each series is the same device across the panels.  Almost all panels have different orders right now.

A similar issue arises as well if one series is missing from those 8 panels, then the color order also will change (understandably I guess). Unfortunately, I can't easily use regexp, as those 8 panels are fetching from different source based on customer name.

It's quite annoying to be fair, right now we solve it by selecting a single device from a variable to show only single device across all the panels.

**Comment by dt-rush** [comment]
There must be an algorithmic way to avoid "nearby-color-collision" given a finite set of strings to hash.

**Comment by brycefisher** [comment]
I do feel like a research spike should be started to explore something like this:
https://github.com/grafana/grafana/issues/3250#issuecomment-532006804
https://github.com/grafana/grafana/issues/3250#issuecomment-532361304
https://github.com/grafana/grafana/issues/3250#issuecomment-532369762

Also, my feeling is that there's enough interest in this issue, it should perhaps be reopened or reincarnated as a new issue.

**Comment by nanoscopic** [comment]
This issue should be reopened and it should be fixed. If you have a dashboard showing multiple graphs for different hosts, all from the same data source, and group by host, then the lists of hosts shown on each graph is the same.

Easy solution to this ( in my described case ):

- Have an array of distinct colors
- Sort the names and use the colors in order

More complex solution ( for varying tags per graph ):
- Color "array"; all distinct colors; with minor variants for bucket overflow
- Hash into the array of colors; using the variants if needed.

Combined solution ( only really works if the graphs are updated at once on same intervals ):
- Recognize all shared tags on graphs shown on a dashboard
- Sort those
- Use distinct color array

To deal with flickering as tags change over a period; the information should be cached and reused per graph also.

**Comment by elsehow** [comment]
Has this been re-opened as a new issue? I agree that this should be fixed - it's a very common need.

**Comment by jensb** [comment]
Yes, please! I am also struggling with this - assigning colors based on legend names (eg. for timeseries).
I would even be satisfied having to specify a key-value list somewhere (as variable, or in the database to query, or ...) to assign a color to each possible Legend entry. It would not have to be automatic.

Maybe we can extend the color palette feature to allow custom palettes where each color can have a regexp or substring to match against each legend entry of a graph which uses this palette? If there is a match, mark this color as "used", otherwise use it in order as before. This would already be sufficient for me.

**Comment by eliovr** [comment]
I'm having a case where one panel shows an aggregation of some groups (pie chart on the left), and another panel the aggregations of the same groups, but over time (timeline).
In SQL terms the first one does a GROUP BY `some_categorical_field`, while the second a GROUP BY `time_interval`, `some_categorical_field`.
You can see that the colors of the groups are not the same in both panels, even though they represent the same groups.

![image](https://user-images.githubusercontent.com/10911004/202507643-56b2a1c5-1a35-4808-8c09-634a791cfc32.png)

**Comment by IARI** [comment]
It seems like one of the most important ans most basic features one would want from a dashboard:
2 panels with consistent colors.
it really sucks that this is still does not seem possible, and overrides are kind of impossible to really use for this.

**Comment by lilydjwg** [comment]
I ended up with a Python script that rewrites the panel JSON with color overrides.

**Comment by bmeyer99** [comment]
What about centralized key:value store that is populated by the first widget and colors are set, next widget reads this, assigns color to matching items and if more are found it updates the store and the next widget will read and populate, eventually every item would have a color associated with it and it can be used throughout the page.

**Comment by melicheradam** [comment]
Having the same problem. I need to present the same data by groups on multiple panels (some aggregated, some calculated, some over time..) and I cannot keep the color scheme consistent among these panels. Grafana does not need to do this automatically, just provide a way to set the color by field labels or column in data

Hardcoding the colors as field overrides is tedious and can lead to inconsistencies, is hard to maintain. If this overrides could be set on a dashboard level as "default" that would be ideal.

**Comment by marcleblanc2** [comment]
> I ended up with a Python script that rewrites the panel JSON with color overrides.

@lilydjwg mind sharing your Python script?

**Comment by lilydjwg** [comment]
@marcleblanc2 here it is: https://gist.github.com/lilydjwg/3215ebf80dd867271370c8771d8218cc
