### ISSUE TITLE
Query editor input is broken for some use of dead key modifiers in Firefox

### ISSUE THREAD

**Issue by lindhe** [grafana/grafana#34378]
**What happened**:
In a query field, I attempt to write `foo{bar~="baz"}` but after typing the `~` character there's suddenly an offset introduced which causes the next character(s) to be typed further to the right than expected. This results in the string `foo{bar~}="baz"` being typed instead of `foo{bar~="baz"}`:

![Screenshot from 2021-05-19 11-09-12](https://user-images.githubusercontent.com/7773090/118787097-c41e7b00-b892-11eb-9583-2c8126365ff9.png)

**What you expected to happen**:
The characters should be input in the same order I type them (as expected in any input field and as it works for this field in Chromium).

**How to reproduce it (as minimally and precisely as possible)**:
1. Use Firefox 88
2. Use a keyboard where `~` requires a dead key modifier, e.g. pressing it twice or pressing it followed by space.
3. Go to the Explore view (or edit a dashboard panel) and in the query input field (e.g. for Prometheus, but I think it is the same no matter the data source).
4. Start typing `foo{bar` and then insert a `~` by pressing the `~` key twice (_not_ `~` followed by space, see below).

**Anything else we need to know?**:
I am using a Swedish keyboard, so the `~` character requires use of a [Dead Key modifier](https://en.wikipedia.org/wiki/Dead_key) (i.e. it requires more than one key press to produce the character). I believe this is the case for many non-American keyboards, and American keyboards also have dead keys (perhaps `´`, I'm not sure).

This seems to be the case for any character that requires a dead key modifier, not just `~`. On my keyboard it's for example `^` and `¨` too.

It seems that it matters how the character is produced. Pasting it is fine, for example. If I press <kbd> ~ </kbd><kbd> ~ </kbd> (`~` key twice), then I get this error. If I instead press <kbd> ~ </kbd><kbd>space</kbd>, I get correct behavior.

Adding more `~` characters seems to shift the input position of the cursor further to the right. If I add three `~` and then press `a` the `a` will not be placed just after the third `~` but actually three positions further to the right.
If I place my cursor just after the number `3` in the following string and insert three `~` characters, instead of `foo{bar="123~~~a456789"}` I get `foo{bar="123456a789"}`. Note especially that the `~` characters were removed.

**Environment**:
- Grafana version: `v7.5.3 (3e3cf4dc60)`
- Data source type & version: Prometheus (but I don't think it matters). Don't know how to identify version.
- OS Grafana is installed on: Kubernetes via Helm chart [bitnami/grafana 5.2.9](https://artifacthub.io/packages/helm/bitnami/grafana/5.2.9)
- User OS & Browser: Ubuntu 20.04, Firefox 88.0.1
- Grafana plugins: whatever ones are enabled by default.

**Misc**:
@simonalling helped me debug this

**Comment by zoltanbedi** [comment]
Hi @lindhe,
Thanks for reporting this. This issue should be fixed in https://github.com/grafana/grafana/pull/33545 and released in 8.0.0-beta1

**Comment by marcobiscaro2112** [comment]
Hey @zoltanbedi, I just tested Grafana 8.0.0-beta3 and it doesn't seem completely fixed, at least on Firefox.

I'm using macOS 10.15.7, with U.S. International - PC input source.

On Chrome 90.0.4430.212 it works fine. On Firefox 90.0b1 the query input field is unusable when I try to type any character that requires a dead key modifier like `"` or `~` :(


https://user-images.githubusercontent.com/196153/120723701-a105e500-c4a8-11eb-91be-e55bc4736cee.mov

**Comment by zoltanbedi** [comment]
I was able to reproduce this, sadly. We need to check Firefox as well.

**Comment by sylr** [comment]
As a user which works almost exclusively with prometheus datasources it is very annoying.

I can still reproduce as of `Grafana v8.2.0-beta2 (a2306d2765)`.

Regards.

**Comment by cykl** [comment]
While there are still some glitches with the Prometheus data source, Loki data source is completely unusable with dead keys. 

To me, having to switch between keyboard layout to use Grafana is a real issue that has been going on for months. How can we help to get that prioritized and fixed? I'm not a front developer but will happily help reproducing / troubleshooting if needed.

**Comment by sylr** [comment]
Well the Monaco editor is worse than the default one so I rolled it back ...

**Comment by sylr** [comment]
Still not fixed in v8.2.5 by the way ... How is this not critical bug ?

**Comment by gabor** [comment]
grafana 8.3.0 has been released which uses the monaco editor by default, which should fix the problem [based on @sylr 's comment](https://github.com/grafana/grafana/issues/34378#issuecomment-950847315)

**Comment by gabor** [comment]
@sylr  wrote
> Well the Monaco editor is worse than the default one so I rolled it back ...

grafana 8.3.0 has been released which switches to the monaco editor by default, if you find bugs in it, feel free to submit new github issues. thanks!

**Comment by cykl** [comment]
@gabor Situation looks good on the Prometheus side :+1:  However, Loki data source is still completely unusable. Could you clarify whether Loki should have been fixed by 8.3.0, or if issue is being addressed, or if I should fill a new issue.

**Comment by gabor** [comment]
@cykl the Loki query editor was not fixed yet. i recommend filing a new issue for Loki.
