### ISSUE TITLE
Grafana Meta Queries (Generic Transforms on Time Series Query Results)

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#3677]
Will enable support for transform functions like scale, derivative, timeShift, movingAverage to all data sources.

**Comment by mtanda** [comment]
I hope this feature is released not so far :-)

**Comment by fungusakafungus** [comment]
:+1:

**Comment by hassanfarid** [comment]
When this feature is expected to go in release for elasticsearch data source?

**Comment by torkelo** [comment]
not ETA, hopefully this year :)

**Comment by yehosef** [comment]
If we were interested/possible to help with development - where would we start?  Does some code exist as a starting point?

**Comment by felixbarny** [comment]
I don't think there is any code for this, yet. A general decision has to be made wether the meta queries are performed server side or client side. I'm in favor of doing this server side so that it can be used for alerting as well. The disadvantage is that this would only work for proxied datasources but I think this is what most people are doing anyway.

**Comment by yehosef** [comment]
If it's helpful at all - I had thought through this problem and had a discussion with Rashid before timelion was release (the first private commits were from before our discussion so I can't claim any credit :)

https://drive.google.com/drive/folders/0B9HCLnVMhNurTVY1UUJWZGxOdEU

I don't know if this is the right vision, but I had been thinking of modular components some of which could potentially be user client or server side.  The advantages of server include caching and minimizing data transfer for larger queries/combinations.  An advantage for client side is for other data sources where the permissions are granted via the browser or potentially to add a new series to an existing graph - the client could just query it directly.  

I would think the timelion code would be an interesting start.  We use the iframe sharing of timelion and the templating in grafana to create templated timelion queries in grafana - a bit hacky but solve the problem until a better solution comes along.

Thanks!

**Comment by arcolife** [comment]
@yehosef Hey thanks for all this material. I had started work on this too, but later, after going through these discussions, realized that adding timeshift just for ES was not so much better an idea, as adding meta queries as Torkeo suggests above. If you guys have started coding this part, I'd be able to help you guys out. If not, I'm happy to take this forward with the reviews for your designs coming in later..

cheers.

**Comment by yehosef** [comment]
@arcolife We haven't started working on it yet - would be happy if someone is able to pick it up.

I don't know how these kinds of things work, but it's possible we would would be able/willing to pay for development of these features if that made it more feasible.  I don't know if there a bounty system for these kinds of things - eg the raintank or some other company says it'll cost  "$x" to develop the feature and different interested parties could contribute.  For us, this and the ability to do SQL queries are really really valuable.

**Comment by arcolife** [comment]
@yehosef Hey thanks! I'm just glad to be able to contribute. :)
PS: if setting up a meeting soon (to discuss those mockups) helps, let's do it?

**Comment by yehosef** [comment]
I'm happy to do whatever I can to help this move forward.  contact me at my_name@google.com if you want to try to set up a meeting - or just just correspond about idea to proceed.

**Comment by arcolife** [comment]
@yehosef "The email account that you tried to reach does not exist." :) 
I tried it on your [github_id] @ google [dot] com.

**Comment by yehosef** [comment]
sorry - its gmail.com

**Comment by shivam009** [comment]
Hi, so we have an ETA of when this feature would be available for OpenTSDB datasource.

**Comment by torkelo** [comment]
no ETA yet, maybe in 4.1 or 4.2 which means hopefully within 6months

**Comment by shivam009** [comment]
I am not sure if this issue is similar to "Feature request: Two different time-range series data are shown in the same graph #3235" as i am concerned about #3235 .
So if you could tell me specifically to this that when this feature will be available for OpenTSDB datasource.

**Comment by arcolife** [comment]
@torkelo whenever this issue is being reviewed, please copy me and @yehosef for we had some email exchanges around this thought and the designs Yehosef had proposed in this thread, and I've realized that it's better to bring those back here for wider exposure. Thanks.

**Comment by cattt84** [comment]
quite interested in updates on this!

**Comment by JanaVi** [comment]
Any update on release date for this feature? I am really looking forward to use timeshift option for Elasticsearch data source.

**Comment by friesoft** [comment]
We would also be really interested in this. Atm there is only Timelion for Kibana

**Comment by natizlp** [comment]
+1

**Comment by bkmeneguello** [comment]
It's possible to create a datasource plugin that has access to the other datasources?
This way could be possible to wrap datasource responses and transform then.

**Comment by torkelo** [comment]
yes,

the included -- Mixed -- data source does this:

https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/mixed/datasource.ts#L13

**Comment by bkmeneguello** [comment]
This is perfect! I think I'll try to build something over this, to create some language to take series from other datasources and process then with functions.
Anyone else interested?

**Comment by felixbarny** [comment]
@bkmeneguello be sure to read my comment: https://github.com/grafana/grafana/issues/3677#issuecomment-230233579. Before implementing anything we should agree on if this should be done client side (js) or server side.

**Comment by bkmeneguello** [comment]
Sure, if this implementation will be core, but for preview it could be made as a datasource plugin.

**Comment by shanielh** [comment]
@torkelo Will this allow "dividing" two queries?

**Comment by RAR** [comment]
Very interested in this functionality as well.

**Comment by jonxor** [comment]
I would also be interested in this as well.  I could use this to have the ability to show a "combined total" in the hover-over of all metrics on a panel that are stacked.

**Comment by shivam009** [comment]
@torkelo  Hi, so do we have an ETA now of when this feature would be available for OpenTSDB datasource.

**Comment by torkelo** [comment]
@shivam009 no ETA currently

**Comment by arunasp** [comment]
@torkelo Hello,

Is there any ETA for #3677 ? It will be very helpful when combining sum/avg/etc on results of the multiple metrics in same way as Graphite data source does. 
Using Elasticsearch as data source here.

**Comment by torkelo** [comment]
no ETA yet, but it's something we hope to get to this year.

**Comment by balda** [comment]
It could be usefull to compare with an arbitrary time range (for example, a "data reference")

**Comment by shiv6146** [comment]
Hi @torkelo,

Any updates on #3677 ??

**Comment by torkelo** [comment]
no updates :(  I would post update here if i had any

**Comment by shiv6146** [comment]
Hi @torkelo,

Thanks for the quick response. Essentially, my requirement is to average out data points returned from ES and bucketize them over a 1 min time interval. Is there any other alternative to achieve summarize and sumSeries functionalities in Elasticsearch?

**Comment by torkelo** [comment]
@shiv6146 can't you use Elasticsearch date histogram interval function for that?

**Comment by shiv6146** [comment]
@torkelo I can do a nested group by, using date histogram but unfortunately Grafana does not allow me to hide the inner group by's output and plot only the aggregated data points :(

**Comment by mstipanov** [comment]
Can you at least implement something simple like adding and subtracting?
* Metric C: #A - #B
* Metric D: #A + #B

**Comment by daniellee** [comment]
@mstipanov it is on our [roadmap](https://github.com/grafana/grafana/blob/master/ROADMAP.md) but we are busy with other features until after the summer.

**Comment by f1-outsourcing** [comment]
@mstipanov 
Looking forward to see this soon also. Using influxdb

•Metric C: #A - #B
•Metric D: #A + #B

**Comment by Gauravshah** [comment]
would like to definitely help on this one if there is a spec. Any place I can start working for this one ?  Also there could be some metrics that might require more data that is available on the existing "A" for example, moving average of 7 days will require (current series +  7 days earlier data)

**Comment by Gauravshah** [comment]
@torkelo do you have any ideas on how do you think we should go about implementing it ? I am willing to invest some time on building this. Need a frontend on top of Druid.

**Comment by Gauravshah** [comment]
looked into extending via plugin. Would have to pass the `datasourceSrv` to the `meta-queries-plugin` and then let the plugin do calls back to the datasource. Planning to work on Moving average & Time Shift first.

**Comment by fabiojose** [comment]
Hi folks, I had an issue like @f1-outsourcing and @mstipanov (metric A (+-) metric B). And then, I developed a panel plugin to do this, called "Calculated Stat plugin". If you are interested, this my github [https://github.com/fabiojose/grafana-calcltdstat-plugin](https://github.com/fabiojose/grafana-calcltdstat-plugin).

**Comment by Gauravshah** [comment]
@fabiojose thanks, I looked at your plugin. Thanks for putting it out. I think it might be better to implement it as a data source that way we can use any panel like table or graph. I am done with Time Shift. Will open source it in a day or two. Will be done with moving average by then as well

**Comment by Gauravshah** [comment]
Poshmark has opensourced github.com/GoshPosh/grafana-meta-queries, it supports computed columns, Moving Average & Timeshift

**Comment by nemenemsrouge** [comment]
Impressive! good job guys!

**Comment by Gauravshah** [comment]
@torkelo if you get some time can you please give your feedback on the plugin ?

**Comment by torkelo** [comment]
@Gauravshah yes! sorry, the hole team has been busy preparing and travelling to a developer conference that we are sponsoring this week so been slow on plugin reviews & feedback. Maybe next week or week after

**Comment by Gauravshah** [comment]
@torkelo no worries, please take your time. Thanks

**Comment by Shushuang-Li** [comment]
@torkelo Is there any update?

**Comment by lilachmaliniak** [comment]
Hi,
using grafana v4.5.2 with Elasticsearch. 
Need to convert timestamp to boolean value based on whether the time elapsed since the timestamp is less than 5minutes. 
script field value (Time is a function that return current epoch): 
boolean( Time - _value > 300 ) 
Is that also in your plans?
Also, we need the option to generate a graph that is the division of two values from different queries, over time.
Thanks,

**Comment by Gauravshah** [comment]
@lilachmaliniak 
you could do `((new Date()).getTime() - A['_value']) > 300`
two different data sources would work

**Comment by lilachmaliniak** [comment]
Thanks @Gauravshah 
I couldn't do exactly what you've suggested, probably due to the value type, which is a number/int.
I got error:500
that is when I set the Options script to: (((new Date()).getTime() - _value) < 300000 )
This is the query:
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"beaconindex"} {"size":0,"query":{"bool":{"filter":[{"range":{"private_data.timestamp":{"gte":"1513673225106","lte":"1513676825106","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"private_data.kes_hostname.keyword:(\"lilach\\-centos\\-vm.com\")"}}]}},"aggs":{"5":{"terms":{"field":"private_data.kes_hostname.keyword","size":10,"order":{"_term":"desc"},"min_doc_count":1},"aggs":{"1":{"max":{"field":"private_data.timestamp","missing":0,"script":{"inline":"(((**new Date()).getTime() - _value) < 300000 )**"}}},"3":{"min":{"field":"private_data.systemMetrics.systemData.system.uptime"}}}}}} "
Running same query from Kibana, I got:
{
  "error": {
    "root_cause": [
      {
        "type": "class_cast_exception",
        "reason": null
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "beaconindex",
        "node": "TGW3SyrEQHSnIi8qQt3rNw",
        "reason": {
          "type": "class_cast_exception",
          "reason": null
        }
      }
    ]
  },
  "status": 500
}

So I used following, in Options, script: (((new Date()).getTime() - _value) < 300000 ) ? 1 : 0
And it works converting the values to rang: [0,1]

My question is: how can I convert the value further in Grafana, to display token instead (e.g. up/down)

**Comment by Gauravshah** [comment]
I think that has to be supported by grafana and not by this plugin as such. You might be able to assign `(((new Date()).getTime() - _value) < 300000 ) ?  '↑' : '↓'` haven't tried though

**Comment by lilachmaliniak** [comment]
@Gauravshah, thanks
Can you be more specific, where do I set this? 
If I write it in the Metric tab under Metric->Options->Script, the script is included in Lucene query as inline property and the query fail with error status 500.
"script":{"inline":"(((new Date()).getTime() - _value) < 300000 ) ? 'up' : 'down'"}

**Comment by Gauravshah** [comment]
I think I have misunderstood your question. I do not know much on elastic search queries. I thought you were asking on how to do it on meta-queries plugin

**Comment by lilachmaliniak** [comment]
@Gauravshah, yes I am trying to do it with ES queries. I already installed the meta-queries plugin but for some reason failed to create dashboard with it. When created new dashboard the option of MetaQuery type was not available. I'll give it another try, thanks.

**Comment by lilachmaliniak** [comment]
@Gauravshah, how do I use MetaQuery with ES datasource?
where can I find the plugin docs?
as I couldn't find doc in git: https://github.com/GoshPosh/grafana-meta-queries
thanks

**Comment by lilachmaliniak** [comment]
Hey @Gauravshah,
I managed to create a new dashboard after installing the MetaQueries datasource plugin.
after creating a new table and set table Data Source to -- Mixed --
added 2 queries:
A ($datasource) Metrics: Max(private_data.timestamp), Group by:Term(private_data.kes_hostname.keyword)
B (MetaQuery Datgasource) Type Arithmetic Expression ((new Date()).getTime() - A['_value']) < 300000 ? 'up' : 'down'
Query A returns expected value and it is successfully displayed in the table.
but, I fail to display a column with the expression value from query B, and I can see what is the expression output, neither whether it succeeded or failed. There is no indication. 
My question: how do I debug the metaQuery and display the expression value in the table as an additional column?
Cheers

**Comment by Gauravshah** [comment]
data source should be set to `Meta Queries` & not mixed. Will add it tot he readme of plugin :(

**Comment by lilachmaliniak** [comment]
Hey @Gauravshah,
Thanks.
Changed table datasource to "MetaQuery Datasource" as you advised.
Now I get error "cannot read property 'length' of undefined" and the table fail to display thought, as before the query from ES succeeds with expected value.

**Comment by Gauravshah** [comment]
@lilachmaliniak can you create an issue on https://github.com/GoshPosh/grafana-meta-queries, also please attach stack trace from your browser

**Comment by lilachmaliniak** [comment]
Hey @Gauravshah,
Added new issue: [https://github.com/GoshPosh/grafana-meta-queries/issues/9](url)

**Comment by costimuraru** [comment]
👍

**Comment by prasadsilva** [comment]
This issue is >2 years old. Did this feature request get rolled into a different one?

**Comment by amuraru** [comment]
👍

**Comment by matschaffer** [comment]
Many time series data stores can do this for you, but some (looking at you cloudwatch) don't and might never support this sort of thing.

In the mean time we can at least do timeShift with two panels, but per-query timeshift to do comparison graphs in the same panel would be pretty fantastic.

**Comment by JJMVG** [comment]
+1

**Comment by Gauravshah** [comment]
@matschaffer  & @JJMVG you should be able to use https://github.com/GoshPosh/grafana-meta-queries

**Comment by SwathiMuppalla** [comment]
@Gauravshah  I have been using table plugin in grafana 6.2.5, Elasticseach datasource. I have a situation where i have a template variable “Version” with data V1, V2, V3 …etc. for every version there is lots of data and i am querying to get total count of every versions data
eg: V1 Total V2 Total
A 10 A 20
B 20 B 15
C 30 C 25
Since I am having template variable “Version” If i try combining two versions i get
V1,V2 | Total
A | 30
B | 35
C | 55

But I am trying to create another column in table panel to subtract the values which i am not able to create. I need it like this
V1,V2 | Total | Difference
A | 30 | 10
B | 35 | 5
C | 55 | 5

Screenshot%20(46)
Screenshot (46).png
1894×888 72.7 KB

I need Difference column which gives value of (server1 - server3)
How do i do this using metaqueries?

**Comment by Gauravshah** [comment]
@SwathiMuppalla you should be creating issues in plugin repo not here.

**Comment by tamsl** [comment]
+1

**Comment by Drewster727** [comment]
+1 this would be yuge

**Comment by redlus** [comment]
As a visualization layer that supports a multitude of data sources, this could be the crown jewel of monitoring features. We combine data from MySQL, Elasticsearch, and Prometheus in our dashboards, and normalizing data from one source based on another could be a huge leap forward in the product's importance in our monitoring stack.

This is not another +1 comment.

**This is a +100 🙏🏼✌🏼**

**Comment by yehosef** [comment]
@torkelo Perhaps it would be possible to use something like https://github.com/wesm/feather or https://arrow.apache.org/docs/python/ipc.html as a kind of "column-store cache" that can then be used for additional processing or manipulations.

**Comment by redlus** [comment]
> @torkelo Perhaps it would be possible to use something like https://github.com/wesm/feather or https://arrow.apache.org/docs/python/ipc.html as a kind of "column-store cache" that can then be used for additional processing or manipulations.

While it's nice to have external tools for advanced functions, this does not address the issue in terms of simplicity or integration with Grafana. Providing the very basic arithmetic operations on two series can solve 80% of the problems with only 20% of the time.

**Comment by Gauravshah** [comment]
@redlus  @yehosef why is https://github.com/GoshPosh/grafana-meta-queries not a solution ?

**Comment by Gauravshah** [comment]
@torkelo if you think https://github.com/GoshPosh/grafana-meta-queries solves the problem mentioned in this issue, we should close the issue addressing that it is being solved by a plugin for grafana. It is difficult for people to scan through long issue to find out that there is a plugin that solves the problem.

**Comment by redlus** [comment]
@Gauravshah
Would love to see a working plugin, but we've had issues using this plugin with newer versions of Grafana.

**Comment by Gauravshah** [comment]
@redlus you should give it another shot, it does work on the grafana 6.4. Also if latest grafana version was the only issue , there were options to go back one minor version. Not sure why would you call `would love to see a working plugin`

**Comment by siegmund42** [comment]
@Gauravshah unfortunately still not working with Grafana 6.5.1 - I didn't try with 6.4 but switching to an older release may not be acceptable for most users.

**Comment by debu99** [comment]
no progress ...

**Comment by gtowsey** [comment]
I see a lot of people bouncing here trying to aggregate multiple data sources. I wonder if the blendstat panel solves some peoples problem and whether that design could be reused in other panels?

[https://grafana.com/grafana/plugins/farski-blendstat-panel](https://grafana.com/grafana/plugins/farski-blendstat-panel)

**Comment by TryTryAgain** [comment]
Blendstat does fill a gap, but it doesn't work with repeating or looping for all variables. If there's a way I don't know how.

**Comment by TryTryAgain** [comment]
I just came across another use case I hope this solves. I am getting back CloudWatch metrics with percent (0.0-0.1) which gives me whole numbers 5, 7, etc. I was expecting 0.5%, 0.7% and I don't see a way to transform that.

**Comment by omaskery** [comment]
Hi, apologies if I'm treading old ground here, but this is quite a long thread:

Am I right in thinking this feature request is to support graphs produced as a result of combining multiple queries? For example, if this work were done, you could take a time series from Prometheus and sum it with a time series from, say, Stack Driver?

If so: is this work still planned, what is the road map and do you need help? :)

**Comment by smurfix** [comment]
that, plus (I hope) time shifting any graph so that I can compare todays graph with yesterday, Or the 7-day average.
Yes, some data stores can already do that, but this should be a generic feature.

**Comment by shassan-el** [comment]
I just came across this thread as it's something that would be useful for me. This was originally raised several years ago. Is there any progress on this?

**Comment by TryTryAgain** [comment]
> I hope this feature is released not so far :-)

:D

**Comment by gelicia** [comment]
Hello all, we wanted to provide an update on this one.

Grafana has tackled many things that people have asked for in this issue in different ways, and having them all under one abstract issue won't help our development teams move forward. As such, we would like to proceed by breaking this into smaller issues that fit with features Grafana has now and closing this ticket. By doing so, we can be sure the relevant teams see specific features and can prioritize them the way they do with other requests.

The team has compiled a list of things people have requested in this ticket and provided some notes. If you feel that your request was not addressed or understood, please feel free to leave a comment or create a new issue. Apologies in advance if a request was misunderstood. We will absolutely open new tickets to represent an individual feature request if something existing doesn't adequately capture what we're looking for.

### Transform function - scale
We weren’t sure what was meant by this. If it's getting a percentage out of a total, there is a PR open here https://github.com/grafana/grafana/pull/97358. Getting the percentage and using the math transformation to multiply that to a number could scale that number. 

### Transform function - derivative
This seems to be something that’s best for metrics, and may be better as a feature for individual metric data sources vs generically for all data sources. Derivative calculations are supported in Grafana in Elasticsearch, Graphite, and InfluxDB. If this would work as a generic aggregation, could we have some more information about it? We can create a ticket about it to move forward.

### Transform function - timeshift
"per-query timeshift to do comparison graphs in the same panel would be pretty fantastic."
"time shifting any graph so that I can compare todays graph with yesterday, Or the 7-day average."
"compare with arbitrary time range"
You can time shift an entire panel in Grafana via Query options, but the feature requested here is for a Grafana-wide ability to time shift an individual query. The idea being that, on the same panel, you could have the results of this week and last week overlaying each other. We will cover this here https://github.com/grafana/grafana/issues/22942

### Transform function - moving average
We believe this is accomplished with Window functions in the "Add field from calculation" transformation
https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#add-field-from-calculation

### Caching data for reuse
Caching results to limit the amount of redundant requests is generally handled by the data source teams. We can work on this, but knowing what the scenario is would be helpful to move forward.

### Query data result
The "--Dashboard--" data source lets you run transformations on the query results from another panel. Not sure what else we might be looking for in terms of querying a data result. 
https://grafana.com/docs/grafana/latest/datasources/#dashboard

### Using multiple data sources in one panel
"create a datasource plugin that has access to the other datasources". 
"combine data from MySQL, Elasticsearch, and Prometheus in our dashboards, and normalizing data from one source based on another"
As stated, this can be accomplished via the Mixed data source. We also have various JOIN transformations to help merge data sets together.
https://grafana.com/docs/grafana/latest/datasources/#mixed
https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#join-by-field

### Perform logic or functions on multiple queries from multiple data sources
"take series from other data sources and process them with functions"
"dividing two queries"
“adding and subtracting results from two queries”
This is possible with a combination of the Mixed data source and the "Add field from calculation" transformation. If you are looking for another kind of function to be added, please create a feature request ticket for it.

### Total all metrics on a stacked panel
"show a combined total of all metrics on a stacked panel"
Where would we want this data to be shown?

### Timestamp logic
"convert timestamp to boolean value based on whether the time elapsed since the timestamp is less than 5minutes."
"my requirement is to average out data points returned from ES and bucketize them over a 1 min time interval. Is there any other alternative to achieve summarize and sumSeries functionalities in Elasticsearch?"
It looks like in this case, there was logic available in the query language itself to cover this. I see an issue for bucketing here https://github.com/grafana/grafana/issues/82995 . Is there any other kind of time logic we may want to add to the "Add field from calculation" transformation? 

### 0-100% to 0-1 conversion
"I am getting back CloudWatch metrics with percent (0.0-0.1) which gives me whole numbers 5, 7, etc. I was expecting 0.5%, 0.7% and I don't see a way to transform that." 
The “Add field from calculation” transformation could do this conversion for you.

Once again, thank you for your feedback and even though this ticket is closed, feel free to comment on whatever may have been missed! Thank you!

**Comment by certara-jgitlin** [comment]
https://github.com/grafana/grafana/issues/5390 was closed in favor of this issue, which has been closed because "having them all under one abstract issue won't help our development teams move forward" -- which makes sense, but I still need the functionality from #5390... 

Specifically I need:

> Transform function - derivative
>
>This seems to be something that’s best for metrics, and may be better as a feature for individual metric data sources vs generically for all data sources.

I need this for CloudWatch because there's ECS `StorageReadBytes` and `StorageWriteBytes` *counter* metrics (they just go up, representing total number of bytes read/written since a container started).

I want to graph _throughput_ so I need `derivative("StorageReadBytes", "1s")` but this isn't InfluxDB, so I am left with a graph that isn't as useful as I want.

Can't find a way to get this using Math or Transformations.
