### ISSUE TITLE
migration failed for 8.0.6

### ISSUE THREAD

**Issue by adrianovieira** [grafana/grafana#37372]
**What happened**:

*"Executing migration failed"*

**What you expected to happen**:

Migration success.

**How to reproduce it (as minimally and precisely as possible)**:

1. take the v7.4.3 database PostgreSQL dump
2. restore one on a staging environment
3. deploy and start grafana-7.5.10 that execute its migration successfully
4. so, deploy and start grafana-8.0.6 that breaks message "Executing migration failed" with

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.3 -> 7.5.10 -> 8.0.6
- Data source type & version: NA
- OS Grafana is installed on: docker/kubernetes
- User OS & Browser: NA
- Grafana plugins:  (bellow list)
<details>

```
agenty-flowcharting-panel, alexanderzobnin-zabbix-app, bessler-pictureit-panel, briangann-datatable-panel, 
briangann-gauge-panel, btplc-peak-report-panel, btplc-status-dot-panel, btplc-trend-box-panel, 
digiapulssi-breadcrumb-panel, digiapulssi-organisations-panel, digrich-bubblechart-panel, 
fatcloud-windrose-panel, grafana-clock-panel, grafana-kubernetes-app, grafana-piechart-panel, 
grafana-polystat-panel, grafana-worldmap-panel, gretamosa-topology-panel, jdbranham-diagram-panel, 
larona-epict-panel, marcuscalidus-svg-panel, marcusolsson-csv-datasource, michaeldmoore-annunciator-panel, 
michaeldmoore-multistat-panel, mtanda-histogram-panel, natel-discrete-panel, natel-plotly-panel,
neocat-cal-heatmap-panel, pierosavi-imageit-panel, satellogic-3d-globe-panel, savantly-heatmap-panel,
scadavis-synoptic-panel, snuids-radar-panel, snuids-trafficlights-panel, vonage-status-panel
```
</details>

- Others: (logging)  
<details>

```
lvl=info msg="Connecting to DB" logger=sqlstore dbtype=postgres
lvl=info msg="Starting DB migrations" logger=migrator
lvl=info msg="Executing migration" logger=migrator id="add index in alert_instance table on def_org_id, def_uid and current_state columns"
lvl=eror msg="Executing migration failed" logger=migrator id="add index in alert_instance table on def_org_id, def_uid and current_state columns" error="pq: coluna \"def_org_id\" não existe"
lvl=eror msg="Exec failed" logger=migrator error="pq: coluna \"def_org_id\" não existe" sql="CREATE INDEX \"IDX_alert_instance_def_org_id_def_uid_current_state\" ON \"alert_instance\" (\"def_org_id\",\"def_uid\",\"current_state\");"
service init failed: migration failed (id = add index in alert_instance table on def_org_id, def_uid and current_state columns): pq: transaction stopped ...
```

</details>

**Comment by kylebrandt** [comment]
@adrianovieira Are you able to share the last ~ 50 rows of the `migration_log` table from the database?

**Comment by adrianovieira** [comment]
For sure:

<details>

```
t=2021-07-30T22:43:29+0000 lvl=info msg="App mode production" logger=settings 
t=2021-07-30T22:43:29+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=postgres 
t=2021-07-30T22:43:29+0000 lvl=info msg="Starting DB migrations" logger=migrator 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create migration_log table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create user table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add unique index user.login" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add unique index user.email" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop index UQE_user_login - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop index UQE_user_email - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Rename table user to user_v1 - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create user table v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index UQE_user_login - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index UQE_user_email - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="copy data_source v1 to v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Drop old table user_v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column help_flags1 to user table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update user table charset" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add last_seen_at column to user" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add missing user data" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add is_disabled column to user" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add index user.login/user.email" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create temp user table v1-7" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index IDX_temp_user_email - v1-7" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index IDX_temp_user_org_id - v1-7" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index IDX_temp_user_code - v1-7" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index IDX_temp_user_status - v1-7" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update temp_user table charset" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop index IDX_temp_user_email - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop index IDX_temp_user_org_id - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop index IDX_temp_user_code - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop index IDX_temp_user_status - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Rename table temp_user to temp_user_tmp_qwerty - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create temp_user v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index IDX_temp_user_email - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index IDX_temp_user_org_id - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index IDX_temp_user_code - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index IDX_temp_user_status - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="copy temp_user v1 to v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop temp_user_tmp_qwerty" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Set created for temp users that will otherwise prematurely expire" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create star table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add unique index star.user_id_dashboard_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create org table v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index UQE_org_name - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create org_user table v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index IDX_org_user_org_id - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index UQE_org_user_org_id_user_id - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update org table charset" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update org_user table charset" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Migrate all Read Only Viewers to Viewers" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create dashboard table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index dashboard.account_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add unique index dashboard_account_id_slug" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create dashboard_tag table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add unique index dashboard_tag.dasboard_id_term" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop index UQE_dashboard_tag_dashboard_id_term - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Rename table dashboard to dashboard_v1 - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create dashboard v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index IDX_dashboard_org_id - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index UQE_dashboard_org_id_slug - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="copy dashboard v1 to v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop table dashboard_v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="alter dashboard.data to mediumtext v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column updated_by in dashboard - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column created_by in dashboard - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column gnetId in dashboard" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add index for gnetId in dashboard" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column plugin_id in dashboard" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add index for plugin_id in dashboard" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add index for dashboard_id in dashboard_tag" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update dashboard table charset" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update dashboard_tag table charset" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column folder_id in dashboard" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column isFolder in dashboard" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column has_acl in dashboard" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column uid in dashboard" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update uid column values in dashboard" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add unique index dashboard_org_id_uid" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Remove unique index org_id_slug" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update dashboard title length" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add unique index for dashboard_org_id_title_folder_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create dashboard_provisioning" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Rename table dashboard_provisioning to dashboard_provisioning_tmp_qwerty - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create dashboard_provisioning v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index IDX_dashboard_provisioning_dashboard_id - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index IDX_dashboard_provisioning_dashboard_id_name - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="copy dashboard_provisioning v1 to v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop dashboard_provisioning_tmp_qwerty" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add check_sum column" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add index for dashboard_title" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="delete tags for deleted dashboards" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="delete stars for deleted dashboards" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create data_source table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index data_source.account_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add unique index data_source.account_id_name" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop index IDX_data_source_account_id - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop index UQE_data_source_account_id_name - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Rename table data_source to data_source_v1 - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create data_source table v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index IDX_data_source_org_id - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index UQE_data_source_org_id_name - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="copy data_source v1 to v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Drop old table data_source_v1 #2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column with_credentials" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add secure json data column" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update data_source table charset" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update initial version to 1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add read_only data column" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Migrate logging ds to loki ds" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update json_data with nulls" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add uid column" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update uid value" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add unique index datasource_org_id_uid" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add unique index datasource_org_id_is_default" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create api_key table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index api_key.account_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index api_key.key" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index api_key.account_id_name" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop index IDX_api_key_account_id - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop index UQE_api_key_key - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop index UQE_api_key_account_id_name - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Rename table api_key to api_key_v1 - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create api_key table v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index IDX_api_key_org_id - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index UQE_api_key_key - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index UQE_api_key_org_id_name - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="copy api_key v1 to v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Drop old table api_key_v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update api_key table charset" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add expires to api_key table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create dashboard_snapshot table v4" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop table dashboard_snapshot_v4 #1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create dashboard_snapshot table v5 #2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index UQE_dashboard_snapshot_key - v5" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index UQE_dashboard_snapshot_delete_key - v5" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index IDX_dashboard_snapshot_user_id - v5" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="alter dashboard_snapshot to mediumtext v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update dashboard_snapshot table charset" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column external_delete_url to dashboard_snapshots table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add encrypted dashboard json column" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Change dashboard_encrypted column to MEDIUMBLOB" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create quota table v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index UQE_quota_org_id_user_id_target - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update quota table charset" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create plugin_setting table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index UQE_plugin_setting_org_id_plugin_id - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column plugin_version to plugin_settings" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update plugin_setting table charset" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create session table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Drop old table playlist table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Drop old table playlist_item table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create playlist table v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create playlist item table v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update playlist table charset" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update playlist_item table charset" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop preferences table v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop preferences table v3" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create preferences table v3" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update preferences table charset" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column team_id in preferences" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update team_id column values in preferences" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create alert table v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index alert org_id & id " 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index alert state" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index alert dashboard_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Create alert_rule_tag table v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add unique index alert_rule_tag.alert_id_tag_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop index UQE_alert_rule_tag_alert_id_tag_id - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Rename table alert_rule_tag to alert_rule_tag_v1 - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Create alert_rule_tag table v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index UQE_alert_rule_tag_alert_id_tag_id - Add unique index alert_rule_tag.alert_id_tag_id V2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="copy alert_rule_tag v1 to v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop table alert_rule_tag_v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create alert_notification table v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column is_default" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column frequency" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column send_reminder" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column disable_resolve_message" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index alert_notification org_id & name" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update alert table charset" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update alert_notification table charset" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create notification_journal table v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index notification_journal org_id & alert_id & notifier_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop alert_notification_journal" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create alert_notification_state table v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index alert_notification_state org_id & alert_id & notifier_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add for to alert table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column uid in alert_notification" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update uid column values in alert_notification" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add unique index alert_notification_org_id_uid" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Remove unique index org_id_name" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column secure_settings in alert_notification" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="alter alert.settings to mediumtext" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add non-unique index alert_notification_state_alert_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add non-unique index alert_rule_tag_alert_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Drop old annotation table v4" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create annotation table v5" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index annotation 0 v3" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index annotation 1 v3" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index annotation 2 v3" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index annotation 3 v3" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index annotation 4 v3" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update annotation table charset" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column region_id to annotation table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Drop category_id index" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column tags to annotation table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Create annotation_tag table v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add unique index annotation_tag.annotation_id_tag_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop index UQE_annotation_tag_annotation_id_tag_id - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Rename table annotation_tag to annotation_tag_v2 - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Create annotation_tag table v3" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index UQE_annotation_tag_annotation_id_tag_id - Add unique index annotation_tag.annotation_id_tag_id V3" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="copy annotation_tag v2 to v3" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop table annotation_tag_v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Update alert annotations and set TEXT to empty" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add created time to annotation table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add updated time to annotation table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add index for created in annotation table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add index for updated in annotation table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Convert existing annotations from seconds to milliseconds" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add epoch_end column" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add index for epoch_end" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Make epoch_end the same as epoch" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Move region to single row" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Remove index org_id_epoch from annotation table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Remove index org_id_dashboard_id_panel_id_epoch from annotation table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add index for org_id_dashboard_id_epoch_end_epoch on annotation table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add index for org_id_epoch_end_epoch on annotation table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Remove index org_id_epoch_epoch_end from annotation table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add index for alert_id on annotation table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create test_data table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create dashboard_version table v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index dashboard_version.dashboard_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add unique index dashboard_version.dashboard_id and dashboard_version.version" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Set dashboard version to 1 where 0" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="save existing dashboard data in dashboard_version table v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="alter dashboard_version.data to mediumtext v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create team table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index team.org_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add unique index team_org_id_name" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create team member table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index team_member.org_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add unique index team_member_org_id_team_id_user_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index team_member.team_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column email to team table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column external to team_member table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column permission to team_member table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create dashboard acl table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index dashboard_acl_dashboard_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add unique index dashboard_acl_dashboard_id_user_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add unique index dashboard_acl_dashboard_id_team_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="save default acl rules in dashboard_acl table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="delete acl rules for deleted dashboards and folders" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create tag table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index tag.key_value" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create login attempt table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index login_attempt.username" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop index IDX_login_attempt_username - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Rename table login_attempt to login_attempt_tmp_qwerty - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create login_attempt v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index IDX_login_attempt_username - v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="copy login_attempt v1 to v2" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop login_attempt_tmp_qwerty" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create user auth table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create index IDX_user_auth_auth_module_auth_id - v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="alter user_auth.auth_id to length 190" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add OAuth access token to user_auth" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add OAuth refresh token to user_auth" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add OAuth token type to user_auth" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add OAuth expiry to user_auth" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add index to user_id column in user_auth" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create server_lock table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index server_lock.operation_uid" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create user auth token table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add unique index user_auth_token.auth_token" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add unique index user_auth_token.prev_auth_token" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index user_auth_token.user_id" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add revoked_at to the user auth token" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create cache_data table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add unique index cache_data.cache_key" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create short_url table v1" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index short_url.org_id-uid" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="delete alert_definition table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="recreate alert_definition table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index in alert_definition on org_id and title columns" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index in alert_definition on org_id and uid columns" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="alter alert_definition table data column to mediumtext in mysql" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop index in alert_definition on org_id and title columns" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop index in alert_definition on org_id and uid columns" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add unique index in alert_definition on org_id and title columns" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add unique index in alert_definition on org_id and uid columns" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="Add column paused in alert_definition" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop alert_definition table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="delete alert_definition_version table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="recreate alert_definition_version table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index in alert_definition_version table on alert_definition_id and version columns" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="add index in alert_definition_version table on alert_definition_uid and version columns" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="alter alert_definition_version table data column to mediumtext in mysql" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="drop alert_definition_version table" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Skipping migration: Already executed" logger=migrator id="create alert_instance table" 
t=2021-07-30T22:43:29+0000 lvl=info msg="Executing migration" logger=migrator id="add index in alert_instance table on def_org_id, def_uid and current_state columns" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Executing migration condition SQL" logger=migrator id="add index in alert_instance table on def_org_id, def_uid and current_state columns" sql="SELECT 1 FROM \"pg_indexes\" WHERE\"tablename\"=? AND \"indexname\"=?" args="[alert_instance IDX_alert_instance_def_org_id_def_uid_current_state]" 
t=2021-07-30T22:43:29+0000 lvl=dbug msg="Executing sql migration" logger=migrator id="add index in alert_instance table on def_org_id, def_uid and current_state columns" sql="CREATE INDEX \"IDX_alert_instance_def_org_id_def_uid_current_state\" ON \"alert_instance\" (\"def_org_id\",\"def_uid\",\"current_state\");" 
t=2021-07-30T22:43:29+0000 lvl=eror msg="Executing migration failed" logger=migrator id="add index in alert_instance table on def_org_id, def_uid and current_state columns" error="pq: coluna \"def_org_id\" não existe" 
t=2021-07-30T22:43:29+0000 lvl=eror msg="Exec failed" logger=migrator error="pq: coluna \"def_org_id\" não existe" sql="CREATE INDEX \"IDX_alert_instance_def_org_id_def_uid_current_state\" ON \"alert_instance\" (\"def_org_id\",\"def_uid\",\"current_state\");" 
service init failed: migration failed (id = add index in alert_instance table on def_org_id, def_uid and current_state columns): pq: transação atual foi interrompida, comandos ignorados até o fim do bloco de transação 
```
</details>

**Comment by kylebrandt** [comment]
@adrianovieira couple questions/requests if possible:

 1. Do you know if `ngalert` feature toggle had been enabled during an earlier version with your instance?
 2. In my previous request I was hoping for something different. In the postgres database, there is a table called `migration_log`, so I am wondering if you can share the last 100 of something like `select * from migration_log` (I see how that could be confusing :-) ).

**Comment by kylebrandt** [comment]
@adrianovieira It would also be helpful I think to know what the columns of the the alert `alert_instance` table are in the db at the time of this.

**Comment by kylebrandt** [comment]
Dev side note:
 I see a couple commits that renamed the column without a migration https://github.com/grafana/grafana/commit/d38aafd6ce1bda73cff927d7a4722b1ebe3fc4f5#diff-7d06812ea52e3b21739a01a623ea7f429c3eef483ad920571d9f8691d825ba18 and https://github.com/grafana/grafana/commit/d26e43b3b2ea3d9edfd1287834e3240874233a22#diff-7d06812ea52e3b21739a01a623ea7f429c3eef483ad920571d9f8691d825ba18 but not sure if they made it into a release...

**Comment by adrianovieira** [comment]
> @adrianovieira It would also be helpful I think to know what the columns of the the alert `alert_instance` table are in the db at the time of this.

There is no `alert_instance` table on the 7.4.3 database dump.

There are only the following `alerts`' tables:

```
CREATE TABLE public.alert
CREATE TABLE public.alert_notification
CREATE TABLE public.alert_notification_state
CREATE TABLE public.alert_rule_tag
```

**Comment by adrianovieira** [comment]
> @adrianovieira couple questions/requests if possible:
> 
>     1. Do you know if `ngalert` feature toggle had been enabled during an earlier version with your instance?
> 
>     2. In my previous request I was hoping for something different. In the postgres database, there is a table called `migration_log`, so I am wondering if you can share the last 100 of something like `select * from migration_log` (I see how that could be confusing :-) ).

So, the log in debug mode (328 lines) since the "Starting Grafana" line:

[migrate-grafana-7.5.10-to-8.0.6-log-mode-debug.log](https://github.com/grafana/grafana/files/6918508/migrate-grafana-7.5.10-to-8.0.6-log-mode-debug.log)

**Comment by kylebrandt** [comment]
If you make a database dump after the failed upgrade to 8.0.6, is there an `public.alert_instance` table?

**Comment by adrianovieira** [comment]
Hi!
Yes. There is.

```sql
CREATE TABLE public.alert_instance (
    rule_org_id bigint NOT NULL,
    rule_uid character varying(40) DEFAULT 0 NOT NULL,
    labels text NOT NULL,
    labels_hash character varying(190) NOT NULL,
    current_state character varying(190) NOT NULL,
    current_state_since bigint NOT NULL,
    last_eval_time bigint NOT NULL,
    current_state_end bigint DEFAULT 0 NOT NULL
);
```

**Comment by kylebrandt** [comment]
Hmm... this seems like a strange state. Will explore more tomorrow and see if I can understand.

My migration log for reference:

![image](https://user-images.githubusercontent.com/1692624/128070935-18dd9011-feb6-4bbb-afbe-12bd98c5b305.png)

So looks as if some migrations that should happen later (renaming of def_uid to rule_uid somehow already) somehow already happened. Does your `migration_log` table at the 8.0.6 snapshot show those migrations as having been run (success == 1)? (I am unable to tell, because it seems the previous uploads are missing those rows).

**Comment by adrianovieira** [comment]
I believe that those attached files (`migration.log`, `migration-7.5.10.log`, and `migration-8.0.6.log`) have all records from that table `migration_log` (at least I suppose they have), according to:

- `migration.log`: has the rows of our actual database for grafana-7.4.3 which was running in production
- `migration-7.5.10.log`: has all the rows added after grafana-7.5.10 migrations
- `migration-8.0.6.log`: has all the rows added after grafana-8.0.6 migrations. But just before the crash of its migrations I think.

<br><br>

_PS_: Some additional information... . We decided to migrate from 7.4.3 to 7.5.10 as its migrations appears to ran with success. So, we deployed grafana-7.5.10 in production. It appears to work well as a whole so far. This way, we put aside the migration to 8.0.6 for a while until we find what's wrong its migrations with.

**Comment by adrianovieira** [comment]
Hi!
Thanks for your help, Kyle!

As I said, from now on, we migrated to 7.5.10, and it is working well so far.
We want to update to v8.0 asap.

So, we again are sharing some of the logging files (which represents our current resulting tests on staging):

- [grafana-7.5.10.schema-only.sql.log](https://github.com/grafana/grafana/files/6945509/grafana-7.5.10.schema-only.sql.log): 
  our database schema that is serving our production service
- [grafana-7.5.10.migration_log-fullcontent.sql.log](https://github.com/grafana/grafana/files/6945507/grafana-7.5.10.migration_log-fullcontent.sql.log): 
  the full content of `migration_log` table, which was updated by version 7.5.10
- [grafana-8.0.6-migration_log-fullcontent.sql.log](https://github.com/grafana/grafana/files/6945496/grafana-8.0.6-migration_log-fullcontent.sql.log): 
    the full content of `migration_log` table, which was updated by version 8.0.6 migrations ("before it crashes")

Once more, we are still counting on all of you to solve this big deal for us.

**Comment by kylebrandt** [comment]
@adrianovieira Sorry for the delay have been out for a bit.

I am still not sure why this is happening. But given:

1. The migration_log says "create alert_instance" table was successful
2. The next migration after, which is "create alert instance table", is expecting there to be `def_org_id` and `def_uid` columns. 

It looks like on your alert_instance table has columns based on later migrations that should not have run yet such as "rename def_uid to rule_uid in alert_instance".

So I am wondering if in the db while grafana is not running (this can be with the db in the state it is after the migration failure):
 1. Drop the alert_instance table
 2. In the migration_log table, set the success column to 0 (or false for postgres?) for the "create alert_instance table" migration

Then try starting Grafana again and see if the migration succeeds or if we get same or different error?

**Comment by adrianovieira** [comment]
It's ok, Kyle.
Thanks for your help.

Steps that I did:
1. Dropped the staging database (Postgres)
2. recovery it from 7.5.10 dumped from production (it doesn't have `migration_id like 'create alert_instance%'`)
3. dropped table `alert_instance`
4. updated `migration_log set success=False where migration_id='create alert_instance table'` (0 rows affected, see "2." above)
5. started v8.0.6 app
6. Got a new migration error: 
   `"Executing migration failed" logger=migrator id="add column for to alert_rule" error="pq: coluna \"for\"  \"alert_rule\" already exists"`

**Comment by kylebrandt** [comment]
This is strange, seems like migrations are running out of order. What is the status of these migrations T/F? And maybe timestamps from the timestamp column?

![image](https://user-images.githubusercontent.com/1692624/128742438-4c4d2b96-7529-49a8-880b-0588f8295755.png)

**Comment by adrianovieira** [comment]
Here are them..

[grafana-8.0.6-migration_log-fullcontent-20210809-0333.sql.log](https://github.com/grafana/grafana/files/6956619/grafana-8.0.6-migration_log-fullcontent-20210809-0333.sql.log)

**Comment by kylebrandt** [comment]
Can you tell me more about the setup of your staging environment? I am starting to wondering of something more general is going on. I don't see how the `for` column could already be there, and not getting any similar reports that I am aware of.

In particular:
 - Multi-instance Grafana or single instance?
 - What does the DB look like, any replication or persistent volumes, noteworthy postgres configuration involved?

---

Continuing the other track of trying to get working without really knowing what is going on yet:
 - Since the For column already exists for some reason, assuming it exists in the DB with the same schema (type, len), then maybe mark the migration manually in DB as successful and see how far the migration continues from there.

**Comment by adrianovieira** [comment]
Hi, Kyle!
Many thanks for your time in helping us in this process.

> Can you tell me more about the setup of your staging environment? I am starting to wondering of something more general is going on. I don't see how the `for` column could already be there, and not getting any similar reports that I am aware of.
> 
> In particular:
> 
>     * Multi-instance Grafana or single instance?
> 
>     * What does the DB look like, any replication or persistent volumes, noteworthy postgres configuration involved?
> 
> 
> Continuing the other track of trying to get working without really knowing what is going on yet:
> 
>     * Since the For column already exists for some reason, assuming it exists in the DB with the same schema (type, len), then maybe mark the migration manually in DB as successful and see how far the migration continues from there.

Grafana has only one instance, and the database is deployed in a standalone machine, but doesn't have replication nor a special setup in it.

We give up on migrating the database, and we throw it away.

What we going to do for staging:
- "export" all dashboards from 7.5.10 on production env (there aren't so many dashboards for this task)
- deploy a fresh new database and 8.0 version
- "import" it on the new staging env.
- after that, we will "pg dump" it and stress both "database restore" and "a new staging deployment"

Let's see if we succeed this time.

**Comment by ki0** [comment]
Any news about this? we are also facing this issue.

**Comment by devopstt** [comment]
Same issue on our side after importing a grafana 6.7.3 Dump to grafana 8.1.5.
Migration will not complete with the following error:
> {"error":"Error 1072: Key column 'def_org_id' doesn't exist in table","id":"add index in alert_instance table on def_org_id, def_uid and current_state columns","logger":"migrator","lvl":"eror","msg":"Executing migration failed","t":"2021-09-29T11:44:23.422825568+02:00"}

**Comment by devopstt** [comment]
Migration works after deleting the Table "alert_instance" and recreating it with
> CREATE TABLE IF NOT EXISTS `alert_instance` (
    -> `def_org_id` BIGINT(20) NOT NULL
    -> , `def_uid` VARCHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 0
    -> , `labels` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
    -> , `labels_hash` VARCHAR(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
    -> , `current_state` VARCHAR(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
    -> , `current_state_since` BIGINT(20) NOT NULL
    -> , `last_eval_time` BIGINT(20) NOT NULL
    -> , PRIMARY KEY ( `def_org_id`,`def_uid`,`labels_hash` )) ENGINE=InnoDB DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;

It seems like "def_org_id" was added a while ago but was not part of an ALTER table. And because of the "CREATE TABLE **IF NOT EXISTS** `alert_instance`", the table was not touched. So the def_org_id is still missing and can not used for creating an index.

**Comment by gerobinson** [comment]
Hi, would it be possible to upgrade to 8.1.7 and see if the issue is still present?

**Comment by zhukaiqiang** [comment]
![image](https://user-images.githubusercontent.com/20986844/150976660-e66637d4-185f-49db-bebd-21ab6a548074.png)
this is my log 
I have the same problem

**Comment by yuri-tceretian** [comment]
Based on the information available in this issue, unfortunately, it is not possible to determine the timeline. I tried to reproduce the problem by running different upgrade paths with and without the feature flag `ngalert` enabled but no luck.

The only guess I have is that there were two concurrent Grafana instances that were started almost at the same time (~1-2 seconds). An instance that started first read the migration log, and started migration, then another instance started to read the log.
As long as the migration log is read at the very beginning of the migration and is not refreshed during the migration, the concurrency can cause this situation.

To whoever encounters this issue please report the following:
1. full dump of the table `migration_log` with all fields included. 
2. if it is mysql database do `SELECT create_time FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'alert_instance'` and post the timestamp
3. versions of Grafana were started against the database. 
3.1. did you run any beta versions against this database?
3.2. did you enable unified alerting in 7.x?
4. Look for `failed to roll back transaction due to error` in the logs and report if you find anything.

**Comment by tubemeister** [comment]
This might shed some light...

This happens if you've ever restored a database dump like normal people do, that is just import it over an existing database without dropping and recreating the whole database or without manually dropping every table in there. 

A typical mysql dump will drop any table before creating it again, but it won't touch tables that exist in the database but not in the dump. So you end up with the original database state from the dump, PLUS any new tables that have been created after you made the dump you're restoring to.

But since you restore the migration_log table from the dump, it does not reflect the existence of those new tables and during migration Grafana apparently does not verify whether a change has already been done, it just executes the changes which will lead to the familiar "already exists" errors.

The Grafana version from when the dump was made will run just fine on this database but migration to a newer version will fail. Once you get in this kind of database state it seems very hard to recover from unless you're deeply familiar with the Grafana migration process, or unless Grafana starts checking whether things exist before executing changes.

Adding this sort of check before making any database changes seems like a good idea to me.
