### ISSUE TITLE
Azure monitor - resources not loading - Grafana - 8.2.5

### ISSUE THREAD

**Issue by ketul-kothari** [grafana/grafana#42106]
I have updated Grafana to version 8.2.5 (prev version - 7.0.5) and noticed that the resources are not loading (actually taking too much time) when using Azure Monitor as data source.

The service principal that I am using has access to more than 1000 subscriptions. From dev tools, I can see that Grafana is trying to load all the resources details. In my case, There are around 8 lakh+ records that are being fetched with 1000 set as fetch at a time count. This way Grafana is making around 800 calls before the resource details can be displayed. The network data being transferred for 300 calls or so is more than 80 Mb. This is making the tool unusable.

Please find the screenshots below.

![Grafana - count details](https://user-images.githubusercontent.com/51498070/142982072-6109b27a-8dbb-4024-b725-7bcf8961948f.jpg)
![Grafana dev tools](https://user-images.githubusercontent.com/51498070/142982096-74da72d9-14e5-45c3-94ec-bc19ef0ff011.jpg)

Kindly check and provide fix for the same.

**Comment by andresmgot** [comment]
seems like a duplicate of https://github.com/grafana/grafana/issues/28016. Can you confirm if this is the same issue @ketul-kothari ?

**Comment by ketul-kothari** [comment]
@andresmgot Root cause does not look same from the description though UI behavior matches (resources not loading, panel showing No Data) etc.

**Comment by andresmgot** [comment]
right, this seems to be a different issue. It was not clear to me but @ketul-kothari you were trying to use Azure Monitor Logs. This should be fixed by https://github.com/grafana/grafana/discussions/41809 (please upvote that if you are interested in the feature). 

One question, it should eventually load and let you select a resource, is that not the case? Do you get any error?

**Comment by ketul-kothari** [comment]
@andresmgot  For Service principal that has access to fewer resources it's working fine. For service principal with access to large number of resources (8 lacs+) it took almost 8-10 mins -- and the processing was still not finished. I didn't get any error. Found the reason so closed the page.

**Comment by andresmgot** [comment]
Thanks for confirming @ketul-kothari. Let's keep the discussion at #41809.
