### ISSUE TITLE
Prometheus: Variables with curly braces stopped working in 8.3.x

### ISSUE THREAD

**Issue by sbrandtb** [grafana/grafana#42867]
**What happened**:

After updating from 8.2.7 to 8.3.1, Prometheus queries that are using variables in curly braces show _parse error: missing unit character in duration_:

```
ts[${__rate_interval}] # parse error: missing unit character in duration
ts[$__rate_interval] # works
ts[${__range_s}s] # parse error: missing unit character in duration
# no fix because of literal s
```

**What you expected to happen**:

From my understanding of the [variable syntax](https://grafana.com/docs/grafana/latest/variables/syntax/), curly braces should be allowed.

**How to reproduce it (as minimally and precisely as possible)**:

Create a panel with a prometheus query like the above.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker Image
- User OS & Browser: Ubuntu 20.04, Firefox
- Grafana plugins: None
- Others: -

**Comment by torkelo** [comment]
@ivanahuckova this looks like something introduced by the new backend implementation

**Comment by sbrandtb** [comment]
This is also happening for `${__range_s}s`, which is a bit more severe since the braces are required due to the literal `s`.

**Comment by lkoenigsberger** [comment]
For me this is also happening when using no braces in the variable at all.
`error="failed to query data: time: invalid duration \"$variable\""`

**Comment by gmwiku** [comment]
in my case (```8.3.0``` and ```8.3.1```) according to ```Query inspector``` ```$__to``` is interpreted properly but ```$__range``` stays untouched.

**Comment by mindw** [comment]
possibly some more info:
variable interpolation within the "Min step" seems to work only for built-ins:
Fails:
![image](https://user-images.githubusercontent.com/578872/145262802-b5719fdd-1c82-47db-a15a-a95e8258adb1.png)
Success:
![image](https://user-images.githubusercontent.com/578872/145262889-3b0d8fda-ec76-4653-b561-2c5a07496bd8.png)
Hope this helps.

**Comment by ivanahuckova** [comment]
Thank you for reporting the issue. This is because curly braces variable are missing here: https://github.com/grafana/grafana/blob/main/pkg/tsdb/prometheus/time_series_query.go#L22

I'll create a fix and it will be part of patch release.

Regarding:
> in my case (8.3.0 and 8.3.1) according to Query inspector $__to is interpreted properly but $__range stays untouched.


@gmwiku Can you please share if your query fails? Some parts of the query can be interpolated on backend, so this might be correct behaviour. If it fails, can you please share where the query is run (Explore/Dashbaord) and where exactly is your variable (`$__to` `$__range`)  - `min step`, `query expr`,...

> variable interpolation within the "Min step" seems to work only for built-ins:

@mindw This was fixed in https://github.com/grafana/grafana/pull/42637

>

**Comment by m1keru** [comment]
> possibly some more info: variable interpolation within the "Min step" seems to work only for built-ins: Fails: ![image](https://user-images.githubusercontent.com/578872/145262802-b5719fdd-1c82-47db-a15a-a95e8258adb1.png) Success: ![image](https://user-images.githubusercontent.com/578872/145262889-3b0d8fda-ec76-4653-b561-2c5a07496bd8.png) Hope this helps.

The same problem, any custom variables stopped working in "min step".
In logs I see 

`error="failed to query data: time: invalid duration \"$interval\"" `

**Comment by ResDiaryLewis** [comment]
Same issue as @m1keru here:
![image](https://user-images.githubusercontent.com/29224433/145367448-cf3c7a3b-73c5-4491-9254-f67ce6ee46af.png)

We can see in the query inspector that it's interpolating the `$interval` in the query but not the min step:
![image](https://user-images.githubusercontent.com/29224433/145367618-66fa4117-56b2-4432-8b06-beb5a3c9ae5f.png)

**Comment by faxm0dem** [comment]
Same issue as @ivanahuckova for `$interval`

**Comment by ivanahuckova** [comment]
@faxm0dem ResDiaryLewis As mentioned, this was fixed in #42637 which will be part of 8.3.2 release.

**Comment by gmwiku** [comment]
@ivanahuckova 

> @gmwiku Can you please share if your query fails? Some parts of the query can be interpolated on backend, so this might be correct behaviour. If it fails, can you please share where the query is run (Explore/Dashbaord) and where exactly is your variable (`$__to` `$__range`) - `min step`, `query expr`,...

```$__range``` is used in query expression ```keep_next_value(quantile_over_time(0.95,ts[$__range])```
Query does not generate any error, it just returns no data. ```data source``` is prometheus type and in fact it is [victoriametrics](https://github.com/VictoriaMetrics/VictoriaMetrics)

query generates ```slow query``` warning in both cases (grafana ```8.2.7``` and ```8.3.1```) and in both cases logs shows ```$__range``` has been interpreted, but only ```8.2.7``` version reports returned data

**Comment by gmwiku** [comment]
@ivanahuckova
 
> `$__range` is used in query expression `keep_next_value(quantile_over_time(0.95,ts[$__range])` Query does not generate any error, it just returns no data. `data source` is prometheus type and in fact it is [victoriametrics](https://github.com/VictoriaMetrics/VictoriaMetrics)
 
in fact the query is a bit more complicated than I wrote before; it is something like this:
```keep_next_value(quantile_over_time(0.95,ts[$__range]) if time() >=$__to/1000)``` 
and probably ```if time() >=$__to/1000)``` leads to no data. In both grafana versions (```8.2.7``` and ```8.3.1```) time range is set to previous month, but query from ```8.2.7``` is ```end=1638313200&query=keep_next_value(quantile_over_time(0.95,...[2592000s]) if time() >=1638313199999/1000)&start=1635721200&step=300``` and from ```8.3.1``` is ```end=1638312900&query=keep_next_value(quantile_over_time(0.95,...[2592000s]) if time() >=1638313199999/1000)&start=1635721200&step=300```

Please take a look on **different** ```end``` parameter value (while $__to remains the same)!!! I suppose that is the clue!!!

**Comment by cztk** [comment]
> @faxm0dem ResDiaryLewis This was fixed in #42637 which will be part of 8.3.2 release.

Beeing on 8.3.3 and seeing this issue still makes me wonder if this promise holds true or not because 8.3.2 might have been planned for a later stage and security issues needed to be fixed sooner?

**Comment by faxm0dem** [comment]
I concur this isn't fixed in 8.3.2

**Comment by ivanahuckova** [comment]
@faxm0dem this is because 8.3.2 turned out to be security release. The fix was merged and will be part of the. next patch release.
