### ISSUE TITLE
Popup menu flows off bottom of screen, items unclickable.

### ISSUE THREAD

**Issue by bobemoe** [grafana/grafana#43239]
**What happened**:

Menu opened off bottom of screen, cant scroll or access the lower items

**What you expected to happen**:

Menu opens fully visible, all items clickable

**How to reproduce it (as minimally and precisely as possible)**:

The two most frustrating instances are:

1. Open context menu by clicking line on chart. In screenshot there are some "data links" that are off screen, even "Add Annotation" is only just visible.
![image](https://user-images.githubusercontent.com/2304970/146423313-5e9b4a7a-497b-4899-8654-ac84aa18bb0b.png)

2. Use the metric selector on query editor. Most of the metrics come off bottom of screen
![image](https://user-images.githubusercontent.com/2304970/146423404-a683f7b0-dba9-46bd-acd1-31c13cb9dfde.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: Graphite 
- OS Grafana is installed on: Docker grafana/grafana
- User OS & Browser: Linux Firefox & Chromium
- Grafana plugins: Default
- Others:

**Comment by Elfo404** [comment]
Hi @bobemoe thanks for reporting this.

The issue with the Graphite editor should be fixed with https://github.com/grafana/grafana/pull/42446 to be released in 8.3.4.

regarding the first one, I can reproduce the behavior and I agree it could be quite frustrating.

**Comment by hugohaggmark** [comment]
Moved the "first" issue in the Time Series graph to @grafana/grafana-bi-squad

**Comment by electronsandstuff** [comment]
Hey folks, I see a similar problem in version 8.3.4 with menus being drawn off screen in the following setup.

Environment:

- Grafana version: 8.3.4
- Data source type & version: InfluxDB 5.0.0
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Windows Chromium
- Grafana plugins: Default

I tried to read through #42446 and it seems the fix made it into the version I'm running (correct me if I'm wrong) and so I thought I would report that the menu issue is still here. The bottom of the menu is cutoff and I have to use arrow keys to select items off of the screen.

![image](https://user-images.githubusercontent.com/61094787/152414138-939633ac-2d04-4f4a-8961-0dc5cf793c26.png)

**Comment by bobemoe** [comment]
Yeah, just updated to 8.3.4 and also still seeing same issue still exists

**Comment by lmynsberge** [comment]
We are on 8.4.4 and also have this issue -- although typically our team is aware of all the values possible, sometimes, when other teams generate these or we source from say, CloudWatch, we have less control and can't see our options for what we can select. 

<img width="218" alt="Screen Shot 2022-04-07 at 4 35 19 PM" src="https://user-images.githubusercontent.com/2281571/162324300-1127f849-9c3b-41bf-862f-a0f1cac3deca.png">
<img width="445" alt="Screen Shot 2022-04-07 at 4 36 44 PM" src="https://user-images.githubusercontent.com/2281571/162324302-2b6c0c15-f050-4465-9989-3752c69e6f49.png">

On MacOS running up-to-date Chrome.
