### ISSUE TITLE
Template variable value not updated in Graph Legends !

### ISSUE THREAD

**Issue by gugansankar** [grafana/grafana#5138]
Not sure why Template variable is not updated in graph's Legends. But its replaced in dashboard Title and also it retrieves the value based on template variable.  In my case I used Template variable name as "appname". I have attached screenshot log also here for your reference,

it shows as :  

> **$appname.BytesOutRate and  $appname.BytesInRate**   instead of showing like "Web1.BytesOutRate and Web1.BytesInRate"

I don't know whether its an existing issue or my configuration mistake.

Grafana Version : Grafana version: 3.0.2, commit: v3.0.1+21-g0c345e2, build date: 2016-05-16 12:36:39
OS : Centos 6.7
Datastore : ES

![grafana-els1](https://cloud.githubusercontent.com/assets/4958813/15469744/dc500110-2109-11e6-9903-c9f0c7a596ee.png)

**Comment by torkelo** [comment]
Looks like template variable interpolation is not used when building the series name. 

As a temp workaround try specifying a Alias pattern `{{metric}}`

**Comment by gugansankar** [comment]
Thanks. I already specified some custom value in alias pattern and using it. 

Please update once its fixed. thanks again

**Comment by trevorndodds** [comment]
Grafana 3.0.4 with Elasticsearch

Template names are not updating the Alias or tooltip.

![image](https://cloud.githubusercontent.com/assets/10899305/16325107/07ce15f6-3989-11e6-8ef1-fb90d85ef5ef.png)

**Comment by danievanzyl** [comment]
bump, getting the same issue,

with Grafana 3.0.4 + Elasticsearch 2.3.3

**Comment by yershalom** [comment]
Hi,

Getting the same error since we were upgraded from 2.6.0 to 3.1.1.
Using Prometheus (1.1.2) as data source here.
![screen shot 2016-09-29 at 9 36 27 am](https://cloud.githubusercontent.com/assets/7933604/18943440/45f16e0a-8628-11e6-8e57-d1096ff28e05.png)

As you can see at the screenshot there is a GroupBy option, in this case i chose datacenter and it worked on our last version.

**Comment by mtanda** [comment]
@yershalom Sorry, it is my fault.
I fixed it recently, but it isn't release in latest Grafana.
https://github.com/grafana/grafana/pull/5994

**Comment by yershalom** [comment]
@mtanda Thank you!

**Comment by millerjp** [comment]
@mtanda do you know which version of 3 this bug was introduced in?

**Comment by trevorndodds** [comment]
In 4.2 the alias is still not reading the template variable as tooltip name.

**Comment by dnhodgson** [comment]
Using Grafana 4.4.2 this is still an issue. However, this may not be a bug. This may never have been implemented in the ES datasource. Bug [#5994](https://github.com/grafana/grafana/pull/5994) involved the Prometheus datasource and I do see the updated code in 4.4.2.

Is it possible to get this added or fixed?

**Comment by marefr** [comment]
Duplicate of #4075
