### ISSUE TITLE
phantom timeout less than 1s?

### ISSUE THREAD

**Issue by tokudan** [grafana/grafana#5368]
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
Issue appeared when upgrading from 2.6 to 3.0.4
- What datasource are you using? InfluxDB 0.9
- What OS are you running grafana on? Debian Jessie
- What did you do? Rendering a snapshot
- What was the expected result? A graph
- What happenend instead? A white PNG

**IMPORTANT** If it realates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

---

I seem to face this issue as well since I upgraded to grafana 3. With 2.6 everything was working, but with version 3 only one of the two images we currently use is successfully generated.
This generated image works:
https://statistik.hamburg.freifunk.net/render/dashboard-solo/db/freifunk-ubersicht?panelId=1&fullscreen&var-region=ffhh&theme=light&width=530&height=332&from=now-3d

This image seems to fail. wget is able to load it in about 600ms, so it does not seem to be a slow server.
https://statistik.hamburg.freifunk.net/render/dashboard-solo/db/freifunk-knoteninfo-knoten-id?panelId=1&fullscreen&var-region=ffhh&var-knoten=14cc20b4c774&theme=light&width=530&height=332&from=now-3d
The base graph sitting behind this can be found here and it does not seem to take long to load either:
https://statistik.hamburg.freifunk.net/dashboard/db/freifunk-knoteninfo-knoten-id?panelId=1&fullscreen&var-region=ffhh&var-knoten=14cc20b4c774&theme=light&width=530&height=332&from=now-3d

**Comment by torkelo** [comment]
could you look for any error in grafana.log ?

**Comment by tokudan** [comment]
There are some errors, but they do have different timestamps:

**Comment by tokudan** [comment]
Sorry, mobile gui...
Here are the errors, they seem to match the timestamps but do not show any details:

2016/06/16 08:27:57 [I] PhantomRenderer::renderToPng url http://127.0.0.1:3000/dashboard-solo/db/freifunk-knoteninfo-knoten-id?panelId=1&fullscreen&var-region=ffhh&var-knoten=002722948b03&theme=light&width=530&height=332&from=now-3d
2016/06/16 08:27:57 [I] Completed 127.0.0.1 - "GET /query HTTP/1.1" 500 Internal Server Error 0 bytes in 145880us
2016/06/16 08:27:57 [I] Completed 127.0.0.1 - "GET /query HTTP/1.1" 500 Internal Server Error 0 bytes in 150374us
2016/06/16 08:27:58 [I] Completed 127.0.0.1 - "GET /query HTTP/1.1" 500 Internal Server Error 0 bytes in 160323us

**Comment by torkelo** [comment]
looks like the metric query if failing when issues from phantomjs, is the data source configured with direct or proxy access, what is the url ? is it accessible from the grafana-server backend?

**Comment by tokudan** [comment]
Data source url is http://127.0.0.1:8086 (influxdb 0.9) setup as a proxy with user/pass.
Since the regular graphs are working fine, grafana seems top be able to connect to influxdb without issues.

**Comment by tokudan** [comment]
Is there any other information that helps to figure out what's going on?

**Comment by tokudan** [comment]
Maybe an interesting information: I updated to influxdb 0.13 in the meantime and the grafana log now shows an additional line (proxy error) per failed request:
Jun 17 21:33:20 ashe grafana-server[24119]: 2016/06/17 21:33:20 [I] PhantomRenderer::renderToPng url http://127.0.0.1:3000/dashboard-solo/db/freifunk-knoteninfo-knoten-id?panelId=1&fullscreen&var-region=ffhh&var-knoten=14cc20b4c774&theme=light&width=530&height=332&from=now-3d
Jun 17 21:33:20 ashe grafana-server[24119]: 2016/06/17 21:33:20 http: proxy error: net/http: request canceled
Jun 17 21:33:20 ashe grafana-server[24119]: 2016/06/17 21:33:20 [I] Completed 127.0.0.1 - "GET /query HTTP/1.1" 500 Internal Server Error 0 bytes in 111991us

**Comment by torkelo** [comment]
strange, you could try Grafana 3.1 nightly build , has some better logging, might show more

**Comment by tokudan** [comment]
So... I just updated to the most recent nightly build (3.1.0-1466167749) and now all pictures are rendered, but they always take slightly over 10s to load.

**Comment by jonozzz** [comment]
Same here, I noticed all PNG snapshots take ~10s. I was looking at /usr/share/grafana/vendor/phantomjs/render.js and apparently checkIsReady() is always timing out after 10 seconds, because rootScope.panelsRendered is NaN.

`    function checkIsReady() {
      var panelsRendered = page.evaluate(function() {
        if (!window.angular) { return false; }
        var body = window.angular.element(document.body);
        if (!body.injector) { return false; }
        if (!body.injector()) { return false; }

        var rootScope = body.injector().get('$rootScope');
        if (!rootScope) {return false;}
        return rootScope.panelsRendered;
      });

      if (panelsRendered || tries === 1000) {
        var bb = page.evaluate(function () {
          return document.getElementsByClassName("main-view")[0].getBoundingClientRect();
        });

        page.clipRect = {
          top:    bb.top,
          left:   bb.left,
          width:  bb.width,
          height: bb.height
        };

        page.render(params.png);
        phantom.exit();
      }
      else {
        tries++;
        setTimeout(checkIsReady, 10);
      }
    }
`

**Comment by torkelo** [comment]
This is fixed in master and 3.1.x branch (and in nightly builds) will be included in next patch release (Eta soon)

**Comment by jonozzz** [comment]
I sync'ed from master branch today, and I'm seeing the same issue. The "+ 1" vs "++" fix, had no effect apparently.

If you log the panelsRendered variable here, you'll see that's always null and only the second condition is hit (tries == 1000).

/usr/share/grafana/vendor/phantomjs/render.js:
> 
      console.log(panelsRendered);
      if (panelsRendered || tries === 1000) {
        var bb = page.evaluate(function () {
          return document.getElementsByClassName("main-view")[0].getBoundingClientRect();
        });

**Comment by torkelo** [comment]
@jonozzz I did another fix, hope it works this time :)

**Comment by tokudan** [comment]
Grafana was updated to 3.1.1-1470047149 (debian package) today. Right now none of the graphs get rendered, only the title is visible in the picture. So this issue is not solved.
---
![ff-knoteninfo](https://cloud.githubusercontent.com/assets/692610/17301552/e38a9ffe-5817-11e6-8714-30b54dc489da.png)
---

**Comment by torkelo** [comment]
@tokudan strange, works here

**Comment by tokudan** [comment]
Did you try the links I mentioned in my first post and they work for you?

**Comment by torkelo** [comment]
Remove the fullscreen parameter from your url

**Comment by tokudan** [comment]
That did the trick. Thanks!

**Comment by jonozzz** [comment]
I too can confirm that the timeout is fixed now, but while testing this I ran into a different bug.
Sharing (link or PNG) of a graph in a repeated row (templated) doesn't work. For the PNG link you get a 404 error.

**Comment by gooodmorningopenstack** [comment]
Hi,

I still have this exact problem, even with the latest build:

* Apache 2.4 proxy (to localhost), timeout 120secs
* Grafana 4.0.0 1471946435pre1 (23/08)

Phantomjs works as I can run It separately but it appears that it takes too much time.

Grafana log:
`lvl=eror msg="Failed to render to png" logger=context userId=3 orgId=1 uname=ldenis error="PhantomRenderer::renderToPng timeout (>30s)"`

`ERROR: TypeError: undefined is not an object (evaluating 'document.getElementsByClassName("main-view")[0].getBoundingClientRect')
TRACE:
-> undefined: 2
-> : 3
phantomjs://code/render.js:46 in onError
TypeError: null is not an object (evaluating 'bb.top')
phantomjs://code/render.js:67 in checkIsReady
`

Any input ?

Thanks

**Comment by JeanFred** [comment]
I have a similar issue

----

* **I'm submitting a ...**
- [X] Bug report

When trying to generate a PNG of a graph via 'Share panel', I’m getting a « Server side error :( − 
Failed to render to png » after 30s.
(As I am on Ubuntu, I’m running the PhantomJS binary that shipped with it. I did install suggested font package.)

Here are the Grafana logs:
```
t=2016-08-31T15:10:33+0000 lvl=info msg="PhantomRenderer::renderToPng url [http://grafana.example.com/dashboard/db/example?width=100]"
t=2016-08-31T15:11:03+0000 lvl=eror msg="Failed to render to png" logger=context userId=2 orgId=1 uname=JeanFred error="PhantomRenderer::renderToPng timeout (>30s)"
t=2016-08-31T15:11:03+0000 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=MyUser method=GET path=/render/dashboard/db/example status=500 remote_addr=127.0.0.1 time_ns=30.002µs size=694
```

Debugging more, I located the exact ` phantomjs` command via `ps` and execute it directly:
```
$ /usr/share/grafana/vendor/phantomjs/phantomjs --ignore-ssl-errors=true /usr/share/grafana/vendor/phantomjs/render.js url='http://grafana.example.com/dashboard-solo/db/example?panelId=11&from=1472650988919&to=1472654588919&width=1000&height=500' width=1000 height=500 png=/var/lib/grafana/png/xxx.png cookiename=grafana_sess domain=grafana.example.com sessionid=xxxxxx
```
Which yields:
```
TypeError: undefined is not an object (evaluating 'document.getElementsByClassName("main-view")[0].getBoundingClientRect')

  undefined:2
  :3
TypeError: null is not an object (evaluating 'bb.top')

  phantomjs://code/render.js:56 in checkIsReady
```

The PhantomJS process then hangs until killed via `pkill`.

No PNG is generated in `/var/lib/grafana/png/`. I can access the `http://grafana.example.com/dashboard-solo/db/example?panelId=11` URL just fine and it does display the 

Thoughts?

---
- What Grafana version are you using? Latest 3.1.1
- What datasource are you using? Graphite
- What OS are you running grafana on? Ubuntu 14.04

**Comment by lsalsich** [comment]
I've been struggling with the same issue as @JeanFred. 

I have a proxy setup with /grafana as the location. root_url has also been modified to use /grafana. The web interface works well. 

However, rendering images fails with the same error as reported by JeanFred. 

However, when I remove /grafana from the root_url in grafana.ini, then the shared image loads fine. 

So, I assume that the render library is looking for the root_url and not finding it - since this only works when combined with the proxy when accessing through an http request. An internal server reference to localhost:3000/grafana will fail to find anything. 

Maybe we need a setting in grafana.ini that is the root_url (for internal grafana references like the ones coming from the reder library) and another 'web_url' (which could include /grafana for proxy users)?

**Comment by torkelo** [comment]
Try nightly build of master / v4
