### ISSUE TITLE
Cursor jumps to end of the query

### ISSUE THREAD

**Issue by theapache64** [grafana/grafana#54942]
**What happened**:

- Cursor jumped to last character

**What you expected to happen**:

- Cursor stays wherever it is

**How to reproduce it (as minimally and precisely as possible)**:

https://user-images.githubusercontent.com/9678279/189293575-9571964f-f749-42e3-a113-29551d380685.mov

**Anything else we need to know?**:

In console it shows this error

```
Uncaught (in promise) Error: Not inside selector, previous selector already closed: ﻿﻿﻿et_lib_timer_subssdk_request_duration_seconds_bucket﻿﻿﻿{﻿﻿﻿﻿﻿le﻿﻿﻿=﻿﻿﻿"+Inf"﻿﻿﻿,﻿﻿﻿clientId﻿﻿﻿=﻿﻿﻿"DDS"﻿﻿﻿,﻿﻿﻿source_cluster﻿﻿﻿=~﻿﻿﻿"$source_cluster"﻿﻿﻿﻿﻿}﻿﻿﻿﻿﻿[﻿﻿﻿1m﻿﻿﻿﻿﻿]﻿

```

- None

**Environment**: 
- Grafana version:  `Grafana v7.5.11 (6f8c1d9fe4)` 
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by scherbakoviv** [comment]
I have a same problem. Version: Grafana v9.1.3 (f3f9a818c2)

https://user-images.githubusercontent.com/15011123/189349299-dadcd00b-afd4-43f2-ab86-a089c1716328.mp4

**Comment by ivanahuckova** [comment]
@theapache64 in v8.3.0 we have changed the editor for Prometheus. To fix your issue, we recommend to update to latest Grafana (or at least use v8.3+)

@scherbakoviv we have fixed this issue and fix will be part of the next patch release (9.1.4) https://github.com/grafana/grafana/pull/54566

**Comment by MikeKholomeev** [comment]
We have version Grafana v8.3.5 (a53fcac7b1) and the issue is there. At Loki. At Chrome.

**Comment by xcono** [comment]
**Environment**:
- Grafana version: v9.1.2
- Data source type & version: Loki v2.6.1
- OS Grafana is installed on: Docker
- User OS & Browser: Ubuntu 22, Chrome 105.0.5195.102 (Official Build) (64-bit)

I have a similar cursor behavior under Linux Chrome, but everything is working like a charm under Linux Firefox or Chrome under Windows. The cursor jumps to the end of the line after any input. After that, if you move the cursor back with an arrow button it seems like the line has additional hidden symbols, because not every arrow press is moving cursor back.

**Comment by ivanahuckova** [comment]
@MikeKholomeev I was talking about Prometheus editor. For Loki, you need to update to v9.1.4 or wait for release 8.5.12 that should happen this week.

**Comment by YuanXingH** [comment]
@grafana/ui 9.1.5 QueryFiled Component
That's still the problem when I develop my own plugin. the cursor   jumps to end of the query

**Comment by sglajchEG** [comment]
https://github.com/ianstormtaylor/slate/issues/5110#issuecomment-1234797133
Is this slate-js fix/workaround relevant?  I see that grafana seems to use slate-js, so maybe that's it?
Chromium bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=1358970&q=text%20input&can=2

**Comment by bbotezatu-mintel** [comment]
Still getting this issue

**Comment by giladcornix** [comment]
Can you please fix this? you got your solution right here in the comment above.

**Comment by theobarrague** [comment]
Same issue in 8.5.11

**Comment by alexeyantropov** [comment]
Have same problem in v8.2.7 (d2cccfe91e).

**Comment by michal-ciechan** [comment]
> If you're in a hurry, as a workaround you can execute either of the following statements in browser console while you're in the query editor view:
> 
> `document.querySelectorAll("div[aria-label='Query field'] > div")[0]['style'].removeProperty('-webkit-user-modify');` or `document.querySelectorAll("div[aria-label='Query field'] > div")[0]['style']['-webkit-user-modify'] = 'read-write';`

This worked for me, for reference if anyone needs it, to change all inputs on the page this worked for me:

```javascript
document.querySelectorAll(".slate-query-field > div").forEach(x => x['style']['-webkit-user-modify'] = 'read-write');
```

**Comment by ZhangSIming-blyq** [comment]
Anything update? I still trap in this problem not matter which version I choose.

**Comment by G0V1NDS** [comment]
This is an annoying issue, above mentioned solutions work but we need to do it everytime we load the Grafana page.
I automated this using this browser extension: https://github.com/Lor-Saba/Code-Injector

Just add below script for your Grafana domain url, it will automatically modify the required `style` for the query field whenever it gets the focus.
```
document.body.addEventListener('click', function (e) {
    closest_query_field = e.target.closest('.slate-query-field')
    if(closest_query_field && closest_query_field.getAttribute('aria-label') === 'Query field'){
        closest_query_field.querySelector('div')['style']['-webkit-user-modify'] = 'read-write';
    }
} );```

**Comment by samng01** [comment]
> This is an annoying issue, above mentioned solutions work but we need to do it everytime we load the Grafana page. I automated this using this browser extension: https://github.com/Lor-Saba/Code-Injector
> 
> Just add below script for your Grafana domain url, it will automatically modify the required `style` for the query field whenever it gets the focus.
> 
> ```js
> document.body.addEventListener('click', function (e) {
>     closest_query_field = e.target.closest('.slate-query-field')
>     if (closest_query_field && closest_query_field.getAttribute('aria-label') === 'Query field') {
>         closest_query_field.querySelector('div')['style']['-webkit-user-modify'] = 'read-write';
>     }
> });
> ```

This works like a charm, thank you!

**Comment by itayB** [comment]
still happens in v9.0.5 :(

**Comment by mcuca1** [comment]
why is this closed, was it resolved in one of the newer versions?

**Comment by ivanahuckova** [comment]
Yes, this was resolved for both prometheus and loki. We recommend to update to a newest version.

**Comment by itayB** [comment]
> Yes, this was resolved for both prometheus and loki. We recommend to update to a newest version.

But it still persists for graphite data source 😞

**Comment by ivanahuckova** [comment]
I recommend to create a new issue for Graphite data source then.

**Comment by robhamnett** [comment]
This seems to still happen. Using Victoria Metrics/Prometheus as data source.

**Comment by uorhsohk** [comment]
I have also encountered this issue using Grafana version Grafana v11.2.0.

**Comment by DutchEllie** [comment]
Constantly happening in v11.4.0.

**Comment by DeathRabbit679** [comment]
Yep, happens constantly on prometheus queries when editing panels. Huge pain.

**Comment by leeoniya** [comment]
should be fixed in 11.6: https://github.com/grafana/grafana/pull/100273
