### ISSUE TITLE
Geomap - Share View not working at all

### ISSUE THREAD

**Issue by rjvtww** [grafana/grafana#57497]
**What happened**:

The Share View toggle, to sync multiple map panels to always be on the same zoom/view, does not work anymore. I tested with already created dashboards, as well as deploying a fresh newest grafana and just a simple dashboard with two geomap panels with Share View on. Does not work even after reloading the page.

**What you expected to happen**:

That multiple geomap panels keep the view/zoom in sync.

**How to reproduce it (as minimally and precisely as possible)**:

Simply create a geomap panel, no data necessary, toggle Share View on, duplicate panel, save dashboard, and refresh website.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.1
- Data source type & version: InfluxDB 2.4
- OS Grafana is installed on: RPI 64bit
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: None
- Others:

**Comment by rjvtww** [comment]
Has anybody been able to test this?

**Comment by ej25a** [comment]
> Has anybody been able to test this?

I was able to get my panels to sync initially between each other when I toggle the Share View within the panel options. However, when I navigate away from my dashboard to another page, or refresh(F5), the panels are no longer synced when I zoom or pan the map.

**Comment by connorhsm** [comment]
I am also experiencing this issue using Grafana 9.4.7.
I've had the same experience as @ej25a whereby toggling the Share View for each panel will temporarily resolve the problem, but after navigating to another dashboard or website and returning, the panels will no longer be in sync.

**Comment by srzetifi** [comment]
Dear @drew08t and Grafana team, I'm seeing this issue on version 9.4.7 as well. What's the status of this ticket?

**Comment by Stephane-Thales** [comment]
same issue on Grafana v9.5.1 (bc353e4b2d)

**Comment by connorhsm** [comment]
Is there any way I can assist to move this along?
Would further information help?

**Comment by drew08t** [comment]
We are looking into this issue and should have an update on it soon!

**Comment by nmarrs** [comment]
Potentially addressed by https://github.com/grafana/grafana/pull/72909

**Comment by kelvinyrb** [comment]
@nmarrs @drew08t Any updates on this issue?

**Comment by connorhsm** [comment]
> toggling the Share View for each panel will temporarily resolve the problem, but after navigating to another dashboard or website and returning, the panels will no longer be in sync.

I've found this work around has now been broken as of version 10.1.1, rolling back to 9.5.8 and the work around temporarily solves the problem again.

**Comment by chrisharbro** [comment]
@nmarrs 
https://github.com/grafana/grafana/pull/72909 does not seem to have fixed it, or at least it has not fixed it for the specific example I am looking at.

**Comment by connorhsm** [comment]
This has been resolved as expected as of v10.3.1, appreciate the work to get this out ❤️
