### ISSUE TITLE
Templating - The results are not 'one of node' but rather 'one of service'

### ISSUE THREAD

**Issue by bodsch** [grafana/grafana#6086]
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using?
 version=4.0.0-pre1 commit=v3.1.0+831-g20f7eee compiled=2016-09-20T11:38:18+0200
- What datasource are you using?
 graphite
- What OS are you running grafana on?
 alpine
- What did you do?
 create template

I test the current master branch in a Docker Container.
I import a set of generated Dashbaords in an older Version ((commit: v3.1.0+738-g583790e)) and in the newest.
When i use Templating to combine a set of Nodes, is the resultset in the newest Version wrong.
The results are not 'one of node' but rather 'one of service'

example of correct result:
![templating_good](https://cloud.githubusercontent.com/assets/6715361/18674467/a0b99216-7f4f-11e6-9420-a27d55164125.jpg)

example of wrong result:
![templating_bug](https://cloud.githubusercontent.com/assets/6715361/18674466/a0b7204e-7f4f-11e6-98db-f1af7a035084.jpg)

**Comment by torkelo** [comment]
I cannot really determine that it is wrong from your screenshot. Can you show the response from graphite for the metricFindQuery?

**Comment by bodsch** [comment]
In the first picture, you can see on service (e.g. ADOBE_DRIVE_SERVER, CAE_LIVE, and so on)
In the second picture, we found many of these service.
the graphite Database is the same.

**Comment by torkelo** [comment]
yes, but what is the response from graphite datasource? is it returning duplicates?

**Comment by bodsch** [comment]
I will tested this ASAP

**Comment by bodsch** [comment]
My Output of metricFindQuery:
```
curl "http://admin:admin@localhost/grafana/api/datasources/proxy/1/metrics/find/?query=*.*.*CAE_*CacheClasses*" | json_pp


[
   {
      "id" : "*.*.CAE_LIVE-CacheClasses-AMAsset",
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-AMAsset",
      "expandable" : 1
   },
   {
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-Aspect",
      "expandable" : 1,
      "id" : "*.*.CAE_LIVE-CacheClasses-Aspect"
   },
   {
      "leaf" : 0,
      "expandable" : 1,
      "text" : "CAE_LIVE-CacheClasses-AssumesIdentity",
      "allowChildren" : 1,
      "id" : "*.*.CAE_LIVE-CacheClasses-AssumesIdentity"
   },
   {
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-ContentBeanBackedPageGridPlacement",
      "expandable" : 1,
      "id" : "*.*.CAE_LIVE-CacheClasses-ContentBeanBackedPageGridPlacement"
   },
   {
      "leaf" : 0,
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-DIGEST",
      "id" : "*.*.CAE_LIVE-CacheClasses-DIGEST"
   },
   {
      "id" : "*.*.CAE_LIVE-CacheClasses-Disk",
      "leaf" : 0,
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-Disk"
   },
   {
      "id" : "*.*.CAE_LIVE-CacheClasses-Heap",
      "leaf" : 0,
      "expandable" : 1,
      "text" : "CAE_LIVE-CacheClasses-Heap",
      "allowChildren" : 1
   },
   {
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMAvailability",
      "leaf" : 0,
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMAvailability"
   },
   {
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMCategory",
      "leaf" : 0,
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMCategory"
   },
   {
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMCommerceUser",
      "leaf" : 0,
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMCommerceUser"
   },
   {
      "leaf" : 0,
      "text" : "CAE_LIVE-CacheClasses-IBMContract",
      "allowChildren" : 1,
      "expandable" : 1,
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMContract"
   },
   {
      "expandable" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMContractIdsByUser",
      "allowChildren" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMContractIdsByUser"
   },
   {
      "leaf" : 0,
      "expandable" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMContractsByUser",
      "allowChildren" : 1,
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMContractsByUser"
   },
   {
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMDynamicPrice",
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMDynamicPrice",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMMarketingSpot",
      "expandable" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMMarketingSpot"
   },
   {
      "text" : "CAE_LIVE-CacheClasses-IBMMarketingSpots",
      "allowChildren" : 1,
      "expandable" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMMarketingSpots"
   },
   {
      "expandable" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMPreviewToken",
      "allowChildren" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMPreviewToken"
   },
   {
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMProduct",
      "leaf" : 0,
      "expandable" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMProduct",
      "allowChildren" : 1
   },
   {
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMProductsByCategory",
      "expandable" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMProductsByCategory"
   },
   {
      "text" : "CAE_LIVE-CacheClasses-IBMSegment",
      "allowChildren" : 1,
      "expandable" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMSegment"
   },
   {
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMSegments",
      "leaf" : 0,
      "expandable" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMSegments",
      "allowChildren" : 1
   },
   {
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMSegmentsByUser",
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMSegmentsByUser",
      "leaf" : 0
   },
   {
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMStaticPrice",
      "leaf" : 0,
      "expandable" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMStaticPrice",
      "allowChildren" : 1
   },
   {
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMStoreInfo",
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMStoreInfo",
      "leaf" : 0
   },
   {
      "leaf" : 0,
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMSubCategories",
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMSubCategories"
   },
   {
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMTopCategories",
      "leaf" : 0,
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMTopCategories"
   },
   {
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMUserIsLoggedIn",
      "expandable" : 1,
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMUserIsLoggedIn"
   },
   {
      "id" : "*.*.CAE_LIVE-CacheClasses-IBMWorkspaces",
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-IBMWorkspaces",
      "expandable" : 1
   },
   {
      "id" : "*.*.CAE_LIVE-CacheClasses-LoadedImageCacheKey",
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-LoadedImageCacheKey",
      "expandable" : 1
   },
   {
      "leaf" : 0,
      "expandable" : 1,
      "text" : "CAE_LIVE-CacheClasses-Object",
      "allowChildren" : 1,
      "id" : "*.*.CAE_LIVE-CacheClasses-Object"
   },
   {
      "id" : "*.*.CAE_LIVE-CacheClasses-Page",
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-Page",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "leaf" : 0,
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-PageGridImpl",
      "id" : "*.*.CAE_LIVE-CacheClasses-PageGridImpl"
   },
   {
      "leaf" : 0,
      "expandable" : 1,
      "text" : "CAE_LIVE-CacheClasses-SearchTermExternalReferenceResolver",
      "allowChildren" : 1,
      "id" : "*.*.CAE_LIVE-CacheClasses-SearchTermExternalReferenceResolver"
   },
   {
      "id" : "*.*.CAE_LIVE-CacheClasses-SolrQueryCacheKey",
      "leaf" : 0,
      "expandable" : 1,
      "text" : "CAE_LIVE-CacheClasses-SolrQueryCacheKey",
      "allowChildren" : 1
   },
   {
      "text" : "CAE_LIVE-CacheClasses-Unlimited",
      "allowChildren" : 1,
      "expandable" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_LIVE-CacheClasses-Unlimited"
   },
   {
      "id" : "*.*.CAE_LIVE-CacheClasses-ViewLookup",
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-CacheClasses-ViewLookup",
      "expandable" : 1
   },
   {
      "allowChildren" : 1,
      "text" : "CAE_PREV-CacheClasses-AMAsset",
      "expandable" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_PREV-CacheClasses-AMAsset"
   },
   {
      "id" : "*.*.CAE_PREV-CacheClasses-Aspect",
      "expandable" : 1,
      "text" : "CAE_PREV-CacheClasses-Aspect",
      "allowChildren" : 1,
      "leaf" : 0
   },
   {
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "CAE_PREV-CacheClasses-AssumesIdentity",
      "expandable" : 1,
      "id" : "*.*.CAE_PREV-CacheClasses-AssumesIdentity"
   },
   {
      "expandable" : 1,
      "text" : "CAE_PREV-CacheClasses-ContentBeanBackedPageGridPlacement",
      "allowChildren" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_PREV-CacheClasses-ContentBeanBackedPageGridPlacement"
   },
   {
      "leaf" : 0,
      "expandable" : 1,
      "text" : "CAE_PREV-CacheClasses-DIGEST",
      "allowChildren" : 1,
      "id" : "*.*.CAE_PREV-CacheClasses-DIGEST"
   },
   {
      "leaf" : 0,
      "text" : "CAE_PREV-CacheClasses-Disk",
      "allowChildren" : 1,
      "expandable" : 1,
      "id" : "*.*.CAE_PREV-CacheClasses-Disk"
   },
   {
      "id" : "*.*.CAE_PREV-CacheClasses-Heap",
      "leaf" : 0,
      "text" : "CAE_PREV-CacheClasses-Heap",
      "allowChildren" : 1,
      "expandable" : 1
   },
   {
      "leaf" : 0,
      "text" : "CAE_PREV-CacheClasses-IBMAvailability",
      "allowChildren" : 1,
      "expandable" : 1,
      "id" : "*.*.CAE_PREV-CacheClasses-IBMAvailability"
   },
   {
      "id" : "*.*.CAE_PREV-CacheClasses-IBMCategory",
      "expandable" : 1,
      "text" : "CAE_PREV-CacheClasses-IBMCategory",
      "allowChildren" : 1,
      "leaf" : 0
   },
   {
      "leaf" : 0,
      "expandable" : 1,
      "text" : "CAE_PREV-CacheClasses-IBMCommerceUser",
      "allowChildren" : 1,
      "id" : "*.*.CAE_PREV-CacheClasses-IBMCommerceUser"
   },
   {
      "text" : "CAE_PREV-CacheClasses-IBMContract",
      "allowChildren" : 1,
      "expandable" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_PREV-CacheClasses-IBMContract"
   },
   {
      "allowChildren" : 1,
      "text" : "CAE_PREV-CacheClasses-IBMContractIdsByUser",
      "expandable" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_PREV-CacheClasses-IBMContractIdsByUser"
   },
   {
      "allowChildren" : 1,
      "text" : "CAE_PREV-CacheClasses-IBMContractsByUser",
      "expandable" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_PREV-CacheClasses-IBMContractsByUser"
   },
   {
      "text" : "CAE_PREV-CacheClasses-IBMDynamicPrice",
      "allowChildren" : 1,
      "expandable" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_PREV-CacheClasses-IBMDynamicPrice"
   },
   {
      "id" : "*.*.CAE_PREV-CacheClasses-IBMMarketingSpot",
      "leaf" : 0,
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_PREV-CacheClasses-IBMMarketingSpot"
   },
   {
      "id" : "*.*.CAE_PREV-CacheClasses-IBMMarketingSpots",
      "leaf" : 0,
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_PREV-CacheClasses-IBMMarketingSpots"
   },
   {
      "leaf" : 0,
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_PREV-CacheClasses-IBMPreviewToken",
      "id" : "*.*.CAE_PREV-CacheClasses-IBMPreviewToken"
   },
   {
      "id" : "*.*.CAE_PREV-CacheClasses-IBMProduct",
      "leaf" : 0,
      "text" : "CAE_PREV-CacheClasses-IBMProduct",
      "allowChildren" : 1,
      "expandable" : 1
   },
   {
      "leaf" : 0,
      "text" : "CAE_PREV-CacheClasses-IBMProductsByCategory",
      "allowChildren" : 1,
      "expandable" : 1,
      "id" : "*.*.CAE_PREV-CacheClasses-IBMProductsByCategory"
   },
   {
      "id" : "*.*.CAE_PREV-CacheClasses-IBMSegment",
      "leaf" : 0,
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_PREV-CacheClasses-IBMSegment"
   },
   {
      "leaf" : 0,
      "text" : "CAE_PREV-CacheClasses-IBMSegments",
      "allowChildren" : 1,
      "expandable" : 1,
      "id" : "*.*.CAE_PREV-CacheClasses-IBMSegments"
   },
   {
      "id" : "*.*.CAE_PREV-CacheClasses-IBMSegmentsByUser",
      "leaf" : 0,
      "text" : "CAE_PREV-CacheClasses-IBMSegmentsByUser",
      "allowChildren" : 1,
      "expandable" : 1
   },
   {
      "expandable" : 1,
      "text" : "CAE_PREV-CacheClasses-IBMStaticPrice",
      "allowChildren" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_PREV-CacheClasses-IBMStaticPrice"
   },
   {
      "allowChildren" : 1,
      "text" : "CAE_PREV-CacheClasses-IBMStoreInfo",
      "expandable" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_PREV-CacheClasses-IBMStoreInfo"
   },
   {
      "id" : "*.*.CAE_PREV-CacheClasses-IBMSubCategories",
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "CAE_PREV-CacheClasses-IBMSubCategories",
      "expandable" : 1
   },
   {
      "id" : "*.*.CAE_PREV-CacheClasses-IBMTopCategories",
      "leaf" : 0,
      "text" : "CAE_PREV-CacheClasses-IBMTopCategories",
      "allowChildren" : 1,
      "expandable" : 1
   },
   {
      "expandable" : 1,
      "text" : "CAE_PREV-CacheClasses-IBMUserIsLoggedIn",
      "allowChildren" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_PREV-CacheClasses-IBMUserIsLoggedIn"
   },
   {
      "allowChildren" : 1,
      "text" : "CAE_PREV-CacheClasses-IBMWorkspaces",
      "expandable" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_PREV-CacheClasses-IBMWorkspaces"
   },
   {
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_PREV-CacheClasses-LoadedImageCacheKey",
      "leaf" : 0,
      "id" : "*.*.CAE_PREV-CacheClasses-LoadedImageCacheKey"
   },
   {
      "id" : "*.*.CAE_PREV-CacheClasses-Object",
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "CAE_PREV-CacheClasses-Object",
      "expandable" : 1
   },
   {
      "id" : "*.*.CAE_PREV-CacheClasses-Page",
      "expandable" : 1,
      "text" : "CAE_PREV-CacheClasses-Page",
      "allowChildren" : 1,
      "leaf" : 0
   },
   {
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "CAE_PREV-CacheClasses-PageGridImpl",
      "expandable" : 1,
      "id" : "*.*.CAE_PREV-CacheClasses-PageGridImpl"
   },
   {
      "leaf" : 0,
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_PREV-CacheClasses-SearchTermExternalReferenceResolver",
      "id" : "*.*.CAE_PREV-CacheClasses-SearchTermExternalReferenceResolver"
   },
   {
      "id" : "*.*.CAE_PREV-CacheClasses-SolrQueryCacheKey",
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_PREV-CacheClasses-SolrQueryCacheKey",
      "leaf" : 0
   },
   {
      "id" : "*.*.CAE_PREV-CacheClasses-Unlimited",
      "expandable" : 1,
      "text" : "CAE_PREV-CacheClasses-Unlimited",
      "allowChildren" : 1,
      "leaf" : 0
   },
   {
      "id" : "*.*.CAE_PREV-CacheClasses-ViewLookup",
      "allowChildren" : 1,
      "text" : "CAE_PREV-CacheClasses-ViewLookup",
      "expandable" : 1,
      "leaf" : 0
   }
]
```

**Comment by torkelo** [comment]
Just tested with that response and get no values at all after the regex pass, since none of those match your regex pattern (No MemoryPool in any of the metrics paths returned from graphite)

**Comment by torkelo** [comment]
Try latest nightly build, might have been fixed in yesterdays big merge of a complete rewrite of the template variable system

**Comment by bodsch** [comment]
Oh sorry, my mistake! :(
I have more than one Templates with this failure.

Here comes the Part with MemoryPool:
```
curl 'http://admin:admin@monitoring-16-build/grafana/api/datasources/proxy/1/metrics/find/?query=*.*.*MemoryPool*' | json_pp

[
   {
      "allowChildren" : 1,
      "text" : "ADOBE_DRIVE_SERVER-MemoryPool-CMS_Old_Gen",
      "id" : "*.*.ADOBE_DRIVE_SERVER-MemoryPool-CMS_Old_Gen",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "expandable" : 1,
      "id" : "*.*.ADOBE_DRIVE_SERVER-MemoryPool-Code_Cache",
      "leaf" : 0,
      "text" : "ADOBE_DRIVE_SERVER-MemoryPool-Code_Cache",
      "allowChildren" : 1
   },
   {
      "text" : "ADOBE_DRIVE_SERVER-MemoryPool-Compressed_Class_Space",
      "allowChildren" : 1,
      "id" : "*.*.ADOBE_DRIVE_SERVER-MemoryPool-Compressed_Class_Space",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "allowChildren" : 1,
      "text" : "ADOBE_DRIVE_SERVER-MemoryPool-Metaspace",
      "id" : "*.*.ADOBE_DRIVE_SERVER-MemoryPool-Metaspace",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "id" : "*.*.ADOBE_DRIVE_SERVER-MemoryPool-Par_Eden_Space",
      "expandable" : 1,
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "ADOBE_DRIVE_SERVER-MemoryPool-Par_Eden_Space"
   },
   {
      "id" : "*.*.ADOBE_DRIVE_SERVER-MemoryPool-Par_Survivor_Space",
      "expandable" : 1,
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "ADOBE_DRIVE_SERVER-MemoryPool-Par_Survivor_Space"
   },
   {
      "text" : "CAE_LIVE-MemoryPool-CMS_Old_Gen",
      "allowChildren" : 1,
      "id" : "*.*.CAE_LIVE-MemoryPool-CMS_Old_Gen",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "text" : "CAE_LIVE-MemoryPool-Code_Cache",
      "allowChildren" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_LIVE-MemoryPool-Code_Cache",
      "expandable" : 1
   },
   {
      "id" : "*.*.CAE_LIVE-MemoryPool-Compressed_Class_Space",
      "expandable" : 1,
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-MemoryPool-Compressed_Class_Space"
   },
   {
      "leaf" : 0,
      "id" : "*.*.CAE_LIVE-MemoryPool-Metaspace",
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "CAE_LIVE-MemoryPool-Metaspace"
   },
   {
      "text" : "CAE_LIVE-MemoryPool-Par_Eden_Space",
      "allowChildren" : 1,
      "expandable" : 1,
      "id" : "*.*.CAE_LIVE-MemoryPool-Par_Eden_Space",
      "leaf" : 0
   },
   {
      "text" : "CAE_LIVE-MemoryPool-Par_Survivor_Space",
      "allowChildren" : 1,
      "leaf" : 0,
      "id" : "*.*.CAE_LIVE-MemoryPool-Par_Survivor_Space",
      "expandable" : 1
   },
   {
      "expandable" : 1,
      "id" : "*.*.CAE_PREV-MemoryPool-CMS_Old_Gen",
      "leaf" : 0,
      "text" : "CAE_PREV-MemoryPool-CMS_Old_Gen",
      "allowChildren" : 1
   },
   {
      "allowChildren" : 1,
      "text" : "CAE_PREV-MemoryPool-Code_Cache",
      "id" : "*.*.CAE_PREV-MemoryPool-Code_Cache",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "id" : "*.*.CAE_PREV-MemoryPool-Compressed_Class_Space",
      "leaf" : 0,
      "expandable" : 1,
      "text" : "CAE_PREV-MemoryPool-Compressed_Class_Space",
      "allowChildren" : 1
   },
   {
      "id" : "*.*.CAE_PREV-MemoryPool-Metaspace",
      "expandable" : 1,
      "leaf" : 0,
      "text" : "CAE_PREV-MemoryPool-Metaspace",
      "allowChildren" : 1
   },
   {
      "text" : "CAE_PREV-MemoryPool-Par_Eden_Space",
      "allowChildren" : 1,
      "id" : "*.*.CAE_PREV-MemoryPool-Par_Eden_Space",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "text" : "CAE_PREV-MemoryPool-Par_Survivor_Space",
      "allowChildren" : 1,
      "id" : "*.*.CAE_PREV-MemoryPool-Par_Survivor_Space",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "allowChildren" : 1,
      "text" : "CMS-MemoryPool-CMS_Old_Gen",
      "id" : "*.*.CMS-MemoryPool-CMS_Old_Gen",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "allowChildren" : 1,
      "text" : "CMS-MemoryPool-Code_Cache",
      "id" : "*.*.CMS-MemoryPool-Code_Cache",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "leaf" : 0,
      "id" : "*.*.CMS-MemoryPool-Compressed_Class_Space",
      "expandable" : 1,
      "text" : "CMS-MemoryPool-Compressed_Class_Space",
      "allowChildren" : 1
   },
   {
      "allowChildren" : 1,
      "text" : "CMS-MemoryPool-Metaspace",
      "id" : "*.*.CMS-MemoryPool-Metaspace",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "expandable" : 1,
      "id" : "*.*.CMS-MemoryPool-Par_Eden_Space",
      "leaf" : 0,
      "text" : "CMS-MemoryPool-Par_Eden_Space",
      "allowChildren" : 1
   },
   {
      "id" : "*.*.CMS-MemoryPool-Par_Survivor_Space",
      "leaf" : 0,
      "expandable" : 1,
      "text" : "CMS-MemoryPool-Par_Survivor_Space",
      "allowChildren" : 1
   },
   {
      "id" : "*.*.ELASTIC_WORKER-MemoryPool-CMS_Old_Gen",
      "leaf" : 0,
      "expandable" : 1,
      "text" : "ELASTIC_WORKER-MemoryPool-CMS_Old_Gen",
      "allowChildren" : 1
   },
   {
      "id" : "*.*.ELASTIC_WORKER-MemoryPool-Code_Cache",
      "expandable" : 1,
      "leaf" : 0,
      "text" : "ELASTIC_WORKER-MemoryPool-Code_Cache",
      "allowChildren" : 1
   },
   {
      "allowChildren" : 1,
      "text" : "ELASTIC_WORKER-MemoryPool-Compressed_Class_Space",
      "id" : "*.*.ELASTIC_WORKER-MemoryPool-Compressed_Class_Space",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "allowChildren" : 1,
      "text" : "ELASTIC_WORKER-MemoryPool-Metaspace",
      "leaf" : 0,
      "id" : "*.*.ELASTIC_WORKER-MemoryPool-Metaspace",
      "expandable" : 1
   },
   {
      "id" : "*.*.ELASTIC_WORKER-MemoryPool-Par_Eden_Space",
      "expandable" : 1,
      "leaf" : 0,
      "text" : "ELASTIC_WORKER-MemoryPool-Par_Eden_Space",
      "allowChildren" : 1
   },
   {
      "expandable" : 1,
      "id" : "*.*.ELASTIC_WORKER-MemoryPool-Par_Survivor_Space",
      "leaf" : 0,
      "text" : "ELASTIC_WORKER-MemoryPool-Par_Survivor_Space",
      "allowChildren" : 1
   },
   {
      "id" : "*.*.FEEDER_CONTENT-MemoryPool-CMS_Old_Gen",
      "leaf" : 0,
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "FEEDER_CONTENT-MemoryPool-CMS_Old_Gen"
   },
   {
      "id" : "*.*.FEEDER_CONTENT-MemoryPool-Code_Cache",
      "expandable" : 1,
      "leaf" : 0,
      "text" : "FEEDER_CONTENT-MemoryPool-Code_Cache",
      "allowChildren" : 1
   },
   {
      "id" : "*.*.FEEDER_CONTENT-MemoryPool-Compressed_Class_Space",
      "expandable" : 1,
      "leaf" : 0,
      "text" : "FEEDER_CONTENT-MemoryPool-Compressed_Class_Space",
      "allowChildren" : 1
   },
   {
      "allowChildren" : 1,
      "text" : "FEEDER_CONTENT-MemoryPool-Metaspace",
      "expandable" : 1,
      "id" : "*.*.FEEDER_CONTENT-MemoryPool-Metaspace",
      "leaf" : 0
   },
   {
      "id" : "*.*.FEEDER_CONTENT-MemoryPool-Par_Eden_Space",
      "expandable" : 1,
      "leaf" : 0,
      "text" : "FEEDER_CONTENT-MemoryPool-Par_Eden_Space",
      "allowChildren" : 1
   },
   {
      "id" : "*.*.FEEDER_CONTENT-MemoryPool-Par_Survivor_Space",
      "expandable" : 1,
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "FEEDER_CONTENT-MemoryPool-Par_Survivor_Space"
   },
   {
      "text" : "FEEDER_LIVE-MemoryPool-CMS_Old_Gen",
      "allowChildren" : 1,
      "id" : "*.*.FEEDER_LIVE-MemoryPool-CMS_Old_Gen",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "id" : "*.*.FEEDER_LIVE-MemoryPool-Code_Cache",
      "expandable" : 1,
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "FEEDER_LIVE-MemoryPool-Code_Cache"
   },
   {
      "id" : "*.*.FEEDER_LIVE-MemoryPool-Compressed_Class_Space",
      "expandable" : 1,
      "leaf" : 0,
      "text" : "FEEDER_LIVE-MemoryPool-Compressed_Class_Space",
      "allowChildren" : 1
   },
   {
      "leaf" : 0,
      "id" : "*.*.FEEDER_LIVE-MemoryPool-Metaspace",
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "FEEDER_LIVE-MemoryPool-Metaspace"
   },
   {
      "id" : "*.*.FEEDER_LIVE-MemoryPool-Par_Eden_Space",
      "expandable" : 1,
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "FEEDER_LIVE-MemoryPool-Par_Eden_Space"
   },
   {
      "leaf" : 0,
      "id" : "*.*.FEEDER_LIVE-MemoryPool-Par_Survivor_Space",
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "FEEDER_LIVE-MemoryPool-Par_Survivor_Space"
   },
   {
      "allowChildren" : 1,
      "text" : "FEEDER_PREV-MemoryPool-CMS_Old_Gen",
      "expandable" : 1,
      "id" : "*.*.FEEDER_PREV-MemoryPool-CMS_Old_Gen",
      "leaf" : 0
   },
   {
      "text" : "FEEDER_PREV-MemoryPool-Code_Cache",
      "allowChildren" : 1,
      "leaf" : 0,
      "id" : "*.*.FEEDER_PREV-MemoryPool-Code_Cache",
      "expandable" : 1
   },
   {
      "expandable" : 1,
      "id" : "*.*.FEEDER_PREV-MemoryPool-Compressed_Class_Space",
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "FEEDER_PREV-MemoryPool-Compressed_Class_Space"
   },
   {
      "id" : "*.*.FEEDER_PREV-MemoryPool-Metaspace",
      "expandable" : 1,
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "FEEDER_PREV-MemoryPool-Metaspace"
   },
   {
      "text" : "FEEDER_PREV-MemoryPool-Par_Eden_Space",
      "allowChildren" : 1,
      "id" : "*.*.FEEDER_PREV-MemoryPool-Par_Eden_Space",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "allowChildren" : 1,
      "text" : "FEEDER_PREV-MemoryPool-Par_Survivor_Space",
      "id" : "*.*.FEEDER_PREV-MemoryPool-Par_Survivor_Space",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "allowChildren" : 1,
      "text" : "MLS-MemoryPool-CMS_Old_Gen",
      "id" : "*.*.MLS-MemoryPool-CMS_Old_Gen",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "text" : "MLS-MemoryPool-Code_Cache",
      "allowChildren" : 1,
      "id" : "*.*.MLS-MemoryPool-Code_Cache",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "id" : "*.*.MLS-MemoryPool-Compressed_Class_Space",
      "leaf" : 0,
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "MLS-MemoryPool-Compressed_Class_Space"
   },
   {
      "allowChildren" : 1,
      "text" : "MLS-MemoryPool-Metaspace",
      "id" : "*.*.MLS-MemoryPool-Metaspace",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "leaf" : 0,
      "id" : "*.*.MLS-MemoryPool-Par_Eden_Space",
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "MLS-MemoryPool-Par_Eden_Space"
   },
   {
      "allowChildren" : 1,
      "text" : "MLS-MemoryPool-Par_Survivor_Space",
      "id" : "*.*.MLS-MemoryPool-Par_Survivor_Space",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "expandable" : 1,
      "id" : "*.*.RLS-MemoryPool-CMS_Old_Gen",
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "RLS-MemoryPool-CMS_Old_Gen"
   },
   {
      "allowChildren" : 1,
      "text" : "RLS-MemoryPool-Code_Cache",
      "id" : "*.*.RLS-MemoryPool-Code_Cache",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "text" : "RLS-MemoryPool-Compressed_Class_Space",
      "allowChildren" : 1,
      "id" : "*.*.RLS-MemoryPool-Compressed_Class_Space",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "text" : "RLS-MemoryPool-Metaspace",
      "allowChildren" : 1,
      "id" : "*.*.RLS-MemoryPool-Metaspace",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "text" : "RLS-MemoryPool-Par_Eden_Space",
      "allowChildren" : 1,
      "id" : "*.*.RLS-MemoryPool-Par_Eden_Space",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "text" : "RLS-MemoryPool-Par_Survivor_Space",
      "allowChildren" : 1,
      "leaf" : 0,
      "id" : "*.*.RLS-MemoryPool-Par_Survivor_Space",
      "expandable" : 1
   },
   {
      "id" : "*.*.SITEMANAGER-MemoryPool-CMS_Old_Gen",
      "expandable" : 1,
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "SITEMANAGER-MemoryPool-CMS_Old_Gen"
   },
   {
      "allowChildren" : 1,
      "text" : "SITEMANAGER-MemoryPool-Code_Cache",
      "expandable" : 1,
      "id" : "*.*.SITEMANAGER-MemoryPool-Code_Cache",
      "leaf" : 0
   },
   {
      "allowChildren" : 1,
      "text" : "SITEMANAGER-MemoryPool-Compressed_Class_Space",
      "id" : "*.*.SITEMANAGER-MemoryPool-Compressed_Class_Space",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "allowChildren" : 1,
      "text" : "SITEMANAGER-MemoryPool-Metaspace",
      "id" : "*.*.SITEMANAGER-MemoryPool-Metaspace",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "text" : "SITEMANAGER-MemoryPool-Par_Eden_Space",
      "allowChildren" : 1,
      "id" : "*.*.SITEMANAGER-MemoryPool-Par_Eden_Space",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "text" : "SITEMANAGER-MemoryPool-Par_Survivor_Space",
      "allowChildren" : 1,
      "expandable" : 1,
      "id" : "*.*.SITEMANAGER-MemoryPool-Par_Survivor_Space",
      "leaf" : 0
   },
   {
      "id" : "*.*.SOLR_MASTER-MemoryPool-CMS_Old_Gen",
      "expandable" : 1,
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "SOLR_MASTER-MemoryPool-CMS_Old_Gen"
   },
   {
      "allowChildren" : 1,
      "text" : "SOLR_MASTER-MemoryPool-Code_Cache",
      "id" : "*.*.SOLR_MASTER-MemoryPool-Code_Cache",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "allowChildren" : 1,
      "text" : "SOLR_MASTER-MemoryPool-Compressed_Class_Space",
      "id" : "*.*.SOLR_MASTER-MemoryPool-Compressed_Class_Space",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "allowChildren" : 1,
      "text" : "SOLR_MASTER-MemoryPool-Metaspace",
      "id" : "*.*.SOLR_MASTER-MemoryPool-Metaspace",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "id" : "*.*.SOLR_MASTER-MemoryPool-Par_Eden_Space",
      "expandable" : 1,
      "leaf" : 0,
      "text" : "SOLR_MASTER-MemoryPool-Par_Eden_Space",
      "allowChildren" : 1
   },
   {
      "leaf" : 0,
      "id" : "*.*.SOLR_MASTER-MemoryPool-Par_Survivor_Space",
      "expandable" : 1,
      "text" : "SOLR_MASTER-MemoryPool-Par_Survivor_Space",
      "allowChildren" : 1
   },
   {
      "id" : "*.*.STUDIO-MemoryPool-CMS_Old_Gen",
      "expandable" : 1,
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "STUDIO-MemoryPool-CMS_Old_Gen"
   },
   {
      "leaf" : 0,
      "id" : "*.*.STUDIO-MemoryPool-Code_Cache",
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "STUDIO-MemoryPool-Code_Cache"
   },
   {
      "allowChildren" : 1,
      "text" : "STUDIO-MemoryPool-Compressed_Class_Space",
      "expandable" : 1,
      "id" : "*.*.STUDIO-MemoryPool-Compressed_Class_Space",
      "leaf" : 0
   },
   {
      "text" : "STUDIO-MemoryPool-Metaspace",
      "allowChildren" : 1,
      "leaf" : 0,
      "id" : "*.*.STUDIO-MemoryPool-Metaspace",
      "expandable" : 1
   },
   {
      "expandable" : 1,
      "id" : "*.*.STUDIO-MemoryPool-Par_Eden_Space",
      "leaf" : 0,
      "text" : "STUDIO-MemoryPool-Par_Eden_Space",
      "allowChildren" : 1
   },
   {
      "allowChildren" : 1,
      "text" : "STUDIO-MemoryPool-Par_Survivor_Space",
      "id" : "*.*.STUDIO-MemoryPool-Par_Survivor_Space",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "allowChildren" : 1,
      "text" : "USER_CHANGES-MemoryPool-CMS_Old_Gen",
      "id" : "*.*.USER_CHANGES-MemoryPool-CMS_Old_Gen",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "allowChildren" : 1,
      "text" : "USER_CHANGES-MemoryPool-Code_Cache",
      "id" : "*.*.USER_CHANGES-MemoryPool-Code_Cache",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "allowChildren" : 1,
      "text" : "USER_CHANGES-MemoryPool-Compressed_Class_Space",
      "id" : "*.*.USER_CHANGES-MemoryPool-Compressed_Class_Space",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "allowChildren" : 1,
      "text" : "USER_CHANGES-MemoryPool-Metaspace",
      "id" : "*.*.USER_CHANGES-MemoryPool-Metaspace",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "text" : "USER_CHANGES-MemoryPool-Par_Eden_Space",
      "allowChildren" : 1,
      "id" : "*.*.USER_CHANGES-MemoryPool-Par_Eden_Space",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "allowChildren" : 1,
      "text" : "USER_CHANGES-MemoryPool-Par_Survivor_Space",
      "id" : "*.*.USER_CHANGES-MemoryPool-Par_Survivor_Space",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "leaf" : 0,
      "id" : "*.*.WEBDAV-MemoryPool-CMS_Old_Gen",
      "expandable" : 1,
      "text" : "WEBDAV-MemoryPool-CMS_Old_Gen",
      "allowChildren" : 1
   },
   {
      "allowChildren" : 1,
      "text" : "WEBDAV-MemoryPool-Code_Cache",
      "id" : "*.*.WEBDAV-MemoryPool-Code_Cache",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "text" : "WEBDAV-MemoryPool-Compressed_Class_Space",
      "allowChildren" : 1,
      "expandable" : 1,
      "id" : "*.*.WEBDAV-MemoryPool-Compressed_Class_Space",
      "leaf" : 0
   },
   {
      "id" : "*.*.WEBDAV-MemoryPool-Metaspace",
      "leaf" : 0,
      "expandable" : 1,
      "allowChildren" : 1,
      "text" : "WEBDAV-MemoryPool-Metaspace"
   },
   {
      "allowChildren" : 1,
      "text" : "WEBDAV-MemoryPool-Par_Eden_Space",
      "id" : "*.*.WEBDAV-MemoryPool-Par_Eden_Space",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "allowChildren" : 1,
      "text" : "WEBDAV-MemoryPool-Par_Survivor_Space",
      "id" : "*.*.WEBDAV-MemoryPool-Par_Survivor_Space",
      "expandable" : 1,
      "leaf" : 0
   },
   {
      "id" : "*.*.WFS-MemoryPool-CMS_Old_Gen",
      "expandable" : 1,
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "WFS-MemoryPool-CMS_Old_Gen"
   },
   {
      "leaf" : 0,
      "id" : "*.*.WFS-MemoryPool-Code_Cache",
      "expandable" : 1,
      "text" : "WFS-MemoryPool-Code_Cache",
      "allowChildren" : 1
   },
   {
      "id" : "*.*.WFS-MemoryPool-Compressed_Class_Space",
      "expandable" : 1,
      "leaf" : 0,
      "allowChildren" : 1,
      "text" : "WFS-MemoryPool-Compressed_Class_Space"
   },
   {
      "allowChildren" : 1,
      "text" : "WFS-MemoryPool-Metaspace",
      "expandable" : 1,
      "id" : "*.*.WFS-MemoryPool-Metaspace",
      "leaf" : 0
   },
   {
      "text" : "WFS-MemoryPool-Par_Eden_Space",
      "allowChildren" : 1,
      "id" : "*.*.WFS-MemoryPool-Par_Eden_Space",
      "leaf" : 0,
      "expandable" : 1
   },
   {
      "allowChildren" : 1,
      "text" : "WFS-MemoryPool-Par_Survivor_Space",
      "id" : "*.*.WFS-MemoryPool-Par_Survivor_Space",
      "expandable" : 1,
      "leaf" : 0
   }
]
```

**Comment by bodsch** [comment]
Thanks @torkelo i will rebuild my Container and test them.

**Comment by bodsch** [comment]
back again.

currently, i use this Version: version=4.0.0-pre1 commit=v3.1.0+859-gd0b75cd compiled=2016-09-21T11:38:59+0200
but the problem isnt resolved.

The other Question ... is my Query (and the Regex) wrong?
But why runs the same in an older grafana Version?

**Comment by torkelo** [comment]
thanks, was able to find and fix the bug!

**Comment by bodsch** [comment]
thanks, for your fast fixing! :)
:trophy:
