### ISSUE TITLE
iOS 16.3: Dashboard issues on mobile devices (iPhones)

### ISSUE THREAD

**Issue by jostrasser** [grafana/grafana#61915]
**What happened**: 
After updating iPhones to iOS 16.3 some fields are missing on Grafana 9.3.2. This issue can reproduced with multiple browsers: Safari, Chrome browsers (Google Chrome, Firefox and MS EDGE for iOS)

Dashboards on iPads and Macs are displayed correctly, this issue is only occurring on iPhones (smaller displays).

**What you expected to happen**: 
All parts of dashboards should be displayed correctly

**How to reproduce it (as minimally and precisely as possible)**: 
Upgrade iOS to 16.3, review dashboards. A downgrade of Grafana is partially restoring all parts of the dashboards but not completely (some panels missing, a 100% working dashboard only on iOS 16.2 or lower).

![SCR-20230123-iqx](https://user-images.githubusercontent.com/14274103/214039984-41684382-9e71-40aa-a3ba-6f256996faff.png)

**Anything else we need to know?**: 
After downgrading Grafana from 9.3.2 to 3.2.0 some fields are coming back again, but not all (see screenshots, Panels are still missing after downgrade of Grafana).

Tested with an iPhone 14 Pro on iOS 16.3. If I open the same dashboard with an iPhone 13 Pro on iOS 16.2 all fields are displayed correctly. Reproduced with multiple iPhones running on both iOS versions.

**Environment**:
- Grafana version: 9.3.2
- Data source type & version: InfluxDB 1.8.x
- OS Grafana is installed on: LXD / Ubuntu 20.04LTS
- User OS & Browser: iOS 16.3 / Safari
- Grafana plugins: N/A
- Others: N/A

**Comment by axelavargas** [comment]
Het @jostrasser 👋🏾 , thank you for reporting this problem, with the team we were able to reproduce it.  I will move it forward to be prioritized.

**Comment by jostrasser** [comment]
> Het @jostrasser 👋🏾 , thank you for reporting this problem, with the team we were able to reproduce it. I will move it forward to be prioritized.

Hi @axelavargas ! np, it was an honor ;)
thanks for your quick support!

**Comment by jostrasser** [comment]
> Het @jostrasser 👋🏾 , thank you for reporting this problem, with the team we were able to reproduce it.  I will move it forward to be prioritized. 

Hi @axelavargas 
do you have any infos in which version this issue will be addressed? Thanks!

**Comment by LotharRe** [comment]
For me, it looks like it's working in 8.4.1.

**Comment by jostrasser** [comment]
> For me, it looks like it's working in 8.4.1.

Not me not on 8.4.1. reproduced on multiple dashboards. Rolled back to 8.3.6.

**Comment by LotharRe** [comment]
> > For me, it looks like it's working in 8.4.1.
> 
> For me not on 8.4.1. reproduced on multiple dashboards. Rolled back to 8.3.6. 

Correct, after dashboard reload it is not working anymore.

**Comment by frepke** [comment]
It's still an issue in v9.4.3 😞

**Comment by jostrasser** [comment]
> It's still an issue in v9.4.3 😞

Should be addressed in 9.4.4

**Comment by jostrasser** [comment]
> It's still an issue in v9.4.3 😞

Can confirm this. No changes with the latest 9.4.x releases. :(

**Comment by jostrasser** [comment]
If you enable Flight Mode then it is maybe coming from your local cache where the data is still there.

**Comment by BertHH** [comment]
Thanks for your suggestions. I cleared the cache and used a pivate tab. Unfortunately, it does not solve the problem.

**Comment by jostrasser** [comment]
I think it will not solve the problem because we have to wait for a fix. But if you have nothing on the local cache you should experience the same behavior when you are online or offline.

**Comment by jrmelsha** [comment]
This is still present on the latest version of iOS (16.3.1) on Grafana 9.4.3. This makes viewing our Grafana panels on mobile impossible. Occurs with Firefox, Chrome, and Safari.

**Comment by jostrasser** [comment]
@kaydelaney is it possible to get an ETA for a fix?

**Comment by csmcolo** [comment]
> I experience the same issue after updating to iOS 16.3
> 
> When I click on the screen where the graph is supposed to be, it appears for a second but disappears again.

This behavior happens for me as well. A quick fix for it is to go to any 

> I experience the same issue after updating to iOS 16.3
> 
> When I click on the screen where the graph is supposed to be, it appears for a second but disappears again.

I have the same behavior. The way I work around it is to select any of the graphs/values that are showing on the dashboard and choose 'View' which opens up a larger version of that object. Once I hit the back arrow to go back to the main dashboard all the previously missing objects are now shown.

**Comment by izzycole** [comment]
Same here.

It seems to be connected to the CSS property -webkit-overflow-scrolling: touch;

As a dirty but easy to implement workaround, i add a text panel to the top of each dashboard, and override the css.

Panel Json:

```
{
  "id": 11,
  "gridPos": {
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "type": "text",
  "title": " ",
  "datasource": {
    "type": "datasource",
    "uid": "grafana"
  },
  "pluginVersion": "9.3.6",
  "options": {
    "mode": "html",
    "code": {
      "language": "plaintext",
      "showLineNumbers": false,
      "showMiniMap": false
    },
    "content": "<style type=\"text/css\">\n.scrollbar-view {\n-webkit-overflow-scrolling: auto !important;\n}\n</style>"
  },
  "transparent": true,
  "description": ""
}
```

**Comment by izzycole** [comment]
@polibb thanks for looking into it!

`-webkit-overflow-scrolling: touch;` seems to get applied as inline css to elements with class ".scrollbar-view" on iOS devices. I noticed it only by connecting my iPhone to the computer and inspecting the source with safari.

Im on Grafana v9.3.6 and iOS 16.3.1

<img width="1370" alt="Bildschirmfoto 2023-03-20 um 11 30 44" src="https://user-images.githubusercontent.com/12833273/226315939-7b02333f-6901-4527-a5f3-0291cb8710ad.png">

**Comment by jostrasser** [comment]
Same behavior with Grafana 9.4.7 on iOS 16.4.

**Comment by frepke** [comment]
> Same behavior with Grafana 9.4.7 on iOS 16.4.

+1

**Comment by axelavargas** [comment]
Hello folks 👋🏾, thank you for all the insights and patience regarding this issue. We've opened this [PR](https://github.com/grafana/grafana/pull/65542) to resolve the problem, targeting the 9.5 release. 🥳

**Comment by technolion** [comment]
>  targeting the 9.5 release. 🥳

Awesome. When can we expect the 9.5 release?

**Comment by DataKnox** [comment]
Also experiencing this issue and as someone already mentioned, viewing a panel and then navigating back to the dashboard is the workaround. Eagerly awaiting a new release

**Comment by jostrasser** [comment]
Grafana 9.5.1 released, fixing our issue!
https://github.com/grafana/grafana/releases/tag/v9.5.1
