### ISSUE TITLE
Status of Elasticsearch 5.0.0 support

### ISSUE THREAD

**Issue by john30** [grafana/grafana#6238]
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
4.0.0 latest (debian package from today)
- What datasource are you using?
elasticsearch with ES running 5.0.0-rc1
- What OS are you running grafana on?
CentOS 6.8
- What did you do?
Tried to add a graph panel with data source elasticsearch.
- What was the expected result?
Get the field list for a start and finally see the number of matched documents in a line graph.
- What happened instead?
An error ocurred:
`error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "No search type for [count]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "No search type for [count]"
  }`

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
query=client, metric=count, group by=date histogram on @timestamp, interval=auto (set to the last year)
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)
request was POST to http://127.0.0.1:3000/api/datasources/proxy/1/_msearch with these parameters:
`{"search_type":"count","ignore_unavailable":true,"index":"requests"}
{"size":0,"query":{"filtered":{"query":{"query_string":{"analyze_wildcard":true,"query":"client"}},"filter"
:{"bool":{"must":[{"range":{"@timestamp":{"gte":"1444570531424","lte":"1476192931426"}}}]}}}},"aggs"
:{"2":{"date_histogram":{"interval":"6h","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min"
:"1444570531424","max":"1476192931426"}},"aggs":{"1":{"sum":{"field":"select field"}}}}}}`
response was: 400 Bad Request with this body:
`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No search type for [count]"}]
,"type":"illegal_argument_exception","reason":"No search type for [count]"},"status":400}`

**Comment by torkelo** [comment]
dupe of https://github.com/grafana/grafana/issues/5740

**Comment by john30** [comment]
could you please add the datasource elasticsearch label to that issue? thanks :-)

**Comment by torkelo** [comment]
yes of course  :)

**Comment by john30** [comment]
thanks :)

**Comment by ToddZhao** [comment]
hi, this error is fixed in version 3.1.1?

**Comment by abravorus** [comment]
Could you please clarify the situation with support of ElasticSearch 5.0 in stable Grafana v3 and upcoming v4?

I have Grafana 3.1.1 and ElasticSearch 2.4.1 installed. For some Grafana dashboards I use ElasticSearch for announcements.
Today I upgraded ElasticSearch cluster to 5.0.0, it's up and running. But I immediatelly got "Announcement error" for the dashbords which use ElasticSearch data source.  And this is not a problem of some deprecated in ES 5.0 fields like "_timestamp" because I do not use them for a long time already.

Will be ES 5.0 support provided for Grafana v3 or is it planned to include such a support in v4 only?

Many thanks,
  Alexandr

**Comment by bergquist** [comment]
We wont add support for ES5 in grafana 3.x. We will add support for ES5 in some of the upcomming 4.x relases.

**Comment by abravorus** [comment]
Thanks for info.
Will mute ES data source temporary.

**Comment by Keeper-of-the-Keys** [comment]
As far as I can tell this still doesn't work with:
- Grafana 4.0.0 (tar release from 29/nov/2016)
- Elasticsearch 5.0.1

Any updates?

**Comment by abravorus** [comment]
The same for me. 
Just installed stable Grafana 4.0.0 released yesterday (thanks to developers!) and checked it against ElasticSearch 5.0.2 - doesn't work.

**Comment by mariotacke** [comment]
I'm in the same boat. ES-5.1.1, Grafana-4.0.2

**Comment by SaaldjorMike** [comment]
@mariotacke If you look at the changelog you'll see that ES 5.x is supported from 4.1.x which is only in beta as of this moment: https://github.com/grafana/grafana/blob/master/CHANGELOG.md

**Comment by mariotacke** [comment]
Awesome. Thanks for letting me know, i'll give it a spin. Can't wait for it to release.

**Comment by abravorus** [comment]
Last Grafana release 4.1.0 works fine with Elasticsearch 5.1.2
Thanks!

**Comment by IaNate83** [comment]
Im running Grafana 4.1.1 and elasticsearch 5.1.2 and am getting the following error as reported here
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "No search type for [count]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "No search type for [count]"
  },
  "status": 400
}
		
This is my third day using these components, is there a fix of any kind? An upgrade or downgrade? a change in the query? I've read through all these posts related tot his error and haven't found anything to help in fixing this issue.

**Comment by torkelo** [comment]
Have you specified ES version in the grafana datasource edit page?

**Comment by poohsen** [comment]
I can confirm the same problem as @IaNate83 with Grafana 4.0.2 and ES 5.1.2. I get it from the default query that's added to a graph when your data source is ES

**Comment by poohsen** [comment]
seems the count metric is deprecated: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/breaking_21_search_changes.html#_literal_search_type_count_literal_deprecated

**Comment by amdei** [comment]
Hit exactly the same issue with Grafana v4.1.2  and ES 5.2.0

**Comment by torkelo** [comment]
What issue? Did you go to datasource edit page and set ES version (so grafana know what version to build queries for)

**Comment by amdei** [comment]
What issue?

Trying to add a graph panel with data source elasticsearch.
Result:
    An error ocurred:
    "error": { "root_cause": [ { "type": "illegal_argument_exception", "reason": "No search type for [count]" } ], "type": "illegal_argument_exception", "reason": "No search type for [count]" }


    Did you go to datasource edit page and set ES version 
    (so grafana know what version to build queries for)

Yes, but I saw only 1.x and 2.x options:

![2017-02-14 20_53_14-grafana - home](https://cloud.githubusercontent.com/assets/11981676/22941731/b7959bb2-f2f7-11e6-92e0-048830e2ff3b.png)


This is on Debian 8.7 x64, installed today with via package repository.

**Comment by torkelo** [comment]
@amdei please upgrade to latest Grafana, ES 5 support was only in 4.1, you appear to use a much older version (3.x?)

**Comment by amdei** [comment]
@torkelo Ooops, indeed, by default grafana was installed from official Debian repository, and appears to be ancient 2.6.something.
When installed grafana from packagecoud, I saw '5.x' settings, and everything works like a charm!

Sorry for bothering you.
