### ISSUE TITLE
Problems with alert annotations after Unified Alerting migration

### ISSUE THREAD

**Issue by vincent-olivert-riera** [grafana/grafana#62761]
- Grafana version: 9.3.0
---
After the Unified Alerting migration I've noticed two problems with the alert annotations. I will try to explain both of them in detail.

**Problem 1 (not very important):**
After migrating to Unified Alerting, it seems that the migrated alert rules are given a new `alertId`.

From Grafana's UI, if I click the "Show state history" button to see all the annotations for an alert rule, the web browser does an HTTP request using the new `alertId`, and that returns the annotations for that rule from **after** the migration until now. Old annotations from **before** the migration are not returned.

A few screenshots to illustrate how the alert rule was given a new ID:

![image](https://user-images.githubusercontent.com/6151586/216296727-f6ad96bf-d0b1-4c29-9fde-81e5b9d87658.png)

Alert ID: 761 (Note the `rule_uid=AS1YTST4k` label).
Dashboard UID: z5qi8zd4z (I will use this in "Problem 2").

As I mentioned before, by checking the HTTP request that Grafana does I could obtain the new alert ID:

![image](https://user-images.githubusercontent.com/6151586/216298282-b2610264-cff9-480b-9cf4-55c955381823.png)

Alert ID: 5 (`rule_uid=AS1YTST4k` didn't change, so is the same rule with different ID).

**Problem 2 (important):**
When new annotations are automatically created after the migration (e.g, when an alert rule changes its state), not all the annotation fields are populated. For instance, `dashboardUID` is set to `null`, `dashboardId` is set to `0` and `panelId` is also set to `0`.

See the output of the following API request. Remember the new `alertId` after the migration was `5` (as illustrated in "problem 1"):

```
$ curl -s \
    -H "X-Grafana-Org-Id: ${ORG}" \
    -H "Authorization: Bearer ${KEY}" \
    "${GRAFANA_URL}/api/annotations?alertId=5&limit=1&type=alert" | jq
[
  {
    "id": 381524,
    "alertId": 5,
    "alertName": "",
    "dashboardId": 0,
    "dashboardUID": null, # Redacted: Note the dashboard fields not being populated
    "panelId": 0,
    "userId": 0,
    "newState": "Normal",
    "prevState": "Alerting",
    "created": 1675329306692, # Redacted: Thu Feb 02 2023 09:15:06 GMT+0000 (Migration was 28th Jan)
    "updated": 1675329306692,
    "time": 1675329300000,
    "timeEnd": 0,
    "text": "CPU usage alert {alertname=CPU usage alert, grafana_folder=NewFolder, rule_uid=AS1YTST4k} - ",
    "tags": [],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {
      "values": {}
    }
  }
]
```

Because of that, when I query the annotations API and filter by `dashboardUID=z5qi8zd4z` and `type=alert`, the only annotations returned are the ones created **before** the migration. The new ones are not returned because the filter on `dashboardUID` does not match.

See the output of this API request where I try to obtain the most recent alert annotation for the aforementioned dashboard:

```
$ curl -s \
    -H "X-Grafana-Org-Id: ${ORG}" \
    -H "Authorization: Bearer ${KEY}" \
    "${GRAFANA_URL}/api/annotations?dashboardUID=z5qi8zd4z&limit=1"  | jq
[
  {
    "id": 381397,
    "alertId": 761, # Redacted: Note the old alert ID from before the migration
    "alertName": "CPU usage alert",
    "dashboardId": 2380,
    "dashboardUID": "z5qi8zd4z", # Redacted: Note the dashboard fields correctly populated
    "panelId": 4,
    "userId": 0,
    "newState": "ok",
    "prevState": "pending",
    "created": 1673947300023, # Redacted: Tue Jan 17 2023 09:21:40 GMT+0000 (Migration was 28th Jan)
    "updated": 1673947300023,
    "time": 1673947300023,
    "timeEnd": 1673947300023,
    "text": "",
    "tags": [],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {}
  }
]
```

**Comment by alexmobo** [comment]
Hi @vincent-olivert-riera, thanks for the detailed issue.

- Problem 1 is low priority as state history does not have a long live span.
- Problem 2 is a bug that needs to be fixed.

**Comment by yuri-tceretian** [comment]
I think this was fixed in https://github.com/grafana/grafana/pull/60926. @vincent-olivert-riera can you please upgrade to the latest patch and see if you can reproduce it.

**Comment by vincent-olivert-riera** [comment]
> I think this was fixed in #60926. @vincent-olivert-riera can you please upgrade to the latest patch and see if you can reproduce it?

I can confirm that in 9.3.6 the new alert annotations do have the dashboard and panel fields correctly populated.

```
$ curl -s "${URL}/api/annotations?alertId=8&limit=1&type=alert" -H "Authorization: Bearer ${KEY}" | jq
[
  {
    "id": 381623,
    "alertId": 8,
    "alertName": "",
    "dashboardId": 2380,
    "dashboardUID": "z5qi8zd4z",
    "panelId": 4,
    "userId": 0,
    "newState": "Normal",
    "prevState": "Alerting",
    "created": 1676518388372,
    "updated": 1676518388372,
    "time": 1676518380000,
    "timeEnd": 0,
    "text": "vincent-cpu-usage-alert {alertname=vincent-cpu-usage-alert, grafana_folder=Vincent, instance=redacted:9100} - B=2.533333, C=0.000000",
    "tags": [],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {
      "values": {
        "B": 2.5333333325882705,
        "C": 0
      }
    }
  }
]
```

However, when querying the annotations API and filter by `dashboardUID` with a `limit` of results, I still do not obtain the latest annotations for that dashboard. If I remove the `limit`, I do obtain a full list of annotations and the new ones are in the list. I guess that's because the annotations on that list are not sorted by time but by some other criteria.

```
$ curl -s "${URL}/api/annotations?dashboardUID=z5qi8zd4z&limit=1" -H "Authorization: Bearer ${KEY}" | jq
[
  {
    "id": 381397,
    "alertId": 761,
    "alertName": "CPU usage alert",
    "dashboardId": 2380,
    "dashboardUID": "z5qi8zd4z",
    "panelId": 4,
    "userId": 0,
    "newState": "ok",
    "prevState": "pending",
    "created": 1673947300023,
    "updated": 1673947300023,
    "time": 1673947300023,
    "timeEnd": 1673947300023,
    "text": "",
    "tags": [],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {}
  }
]
```

Is that problem relevant for this issue?
Do you prefer me to report it in a different issue?
Is that not an issue at all, hence won't get "fixed"?

Please advice. Thank you!

**Comment by yuri-tceretian** [comment]
Oh, I forgot about that! It was another bug fixed in https://github.com/grafana/grafana/pull/60931.
As you know, the API you use takes the first 100 annotations sorted by `epoch_end` timestamp. Therefore annotations created when that bug was there have 0 timestamps and therefore go to the end of the sorted list, and thus, never appear in your results unless you have less than 100 old records. If you set up annotations' [automatic cleanup](https://github.com/grafana/grafana/blob/main/conf/defaults.ini#L1019-L1025), the problem will be fixed automatically after old data gets deleted.
The PR I refer to above, unfortunately, does not fix the "broken" data. So, if you did not set up annotation cleanup or want to see those 0-timestamped records immediately, I would recommend running a simple SQL 

```sql
UPDATE annotation SET epoch_end = epoch WHERE epoch_end = 0
```

also, if you want to fix annotations created without dashboardUID and panelID, you may use a query like this 

```sql
UPDATE annotation AS A
    INNER JOIN alert_rule AS R ON A.alert_id = R.id
    INNER JOIN dashboard AS D ON R.dashboard_uid = D.uid
SET 
    A.dashboard_id = D.id,
    A.panel_id = R.panel_id
WHERE A.dashboard_id = 0
```

**Disclosure** I did not test this query!

**Comment by vincent-olivert-riera** [comment]
> Oh, I forgot about that! It was another bug fixed in https://github.com/grafana/grafana/pull/60931.

Uhm..., are you sure that fix is included in 9.3.6?

> [...] annotations created when that bug was there have 0 timestamps

From what I see, annotations created in 9.3.6 **also** have a 0 `epoch_end` timestamp.
Look at the following SQL query. Rows without a `dashboard_id` are from **before** the 9.3.6 update (9.3.0 actually). Ros with a `dashboard_id` are from **after** the 9.3.6 update.
As you can see, all of them have a 0 `epoch_end`, which makes me think the bug fix was not included in 9.3.6.

```
MySQL [grafana]> select id,alert_id,dashboard_id,epoch,epoch_end from annotation where alert_id = '8' order by id desc;
+--------+----------+--------------+---------------+-----------+
| id     | alert_id | dashboard_id | epoch         | epoch_end |
+--------+----------+--------------+---------------+-----------+
| 381629 |        8 |         2380 | 1676521800000 |         0 |
| 381628 |        8 |         2380 | 1676521800000 |         0 |
| 381627 |        8 |         2380 | 1676521440000 |         0 |
| 381626 |        8 |         2380 | 1676521440000 |         0 |
| 381625 |        8 |         2380 | 1676521260000 |         0 |
| 381624 |        8 |         2380 | 1676521260000 |         0 |
| 381623 |        8 |         2380 | 1676518380000 |         0 |
| 381622 |        8 |         2380 | 1676518380000 |         0 |
| 381621 |        8 |         2380 | 1676518260000 |         0 |
| 381620 |        8 |         2380 | 1676518260000 |         0 |
| 381619 |        8 |         2380 | 1676518080000 |         0 |
| 381618 |        8 |         2380 | 1676518080000 |         0 |
| 381617 |        8 |            0 | 1676517060000 |         0 |
| 381616 |        8 |            0 | 1676517060000 |         0 |
| 381615 |        8 |            0 | 1676516940000 |         0 |
| 381614 |        8 |            0 | 1676516940000 |         0 |
| 381613 |        8 |            0 | 1676516760000 |         0 |
| 381612 |        8 |            0 | 1676516760000 |         0 |
+--------+----------+--------------+---------------+-----------+
18 rows in set (0.034 sec)
```

**Comment by yuri-tceretian** [comment]
You're right. The fix was backported to 9.3.x branch on Feb 8 but the latest patch release (9.3.6) was on Jan 26. Sorry. The next patch is expected on Feb 28.

**Comment by vincent-olivert-riera** [comment]
> You're right. The fix was backported to 9.3.x branch on Feb 8 but the latest patch release (9.3.6) was on Jan 26. Sorry. The next patch is expected on Feb 28.

Will wait for it. Thanks! 👍🏻

**Comment by yuri-tceretian** [comment]
In the meantime, I think the only way to mitigate this problem is to remove records with non-zero `epoch_end` with `alert_id != NULL` 
Effectively this will make the sorting fall back to `epoch`, which is populated correctly. https://github.com/grafana/grafana/blob/cc8c1380e22cd6f5840deada541d4aa269eee0fa/pkg/services/annotations/annotationsimpl/xorm_store.go#L307

**Comment by yuri-tceretian** [comment]
@vincent-olivert-riera the new patch for 9.3 has been released. Did you have a chance to upgrade and confirm that this problem stopped happening?

**Comment by armandgrillet** [comment]
https://github.com/grafana/grafana/pull/65950 should have solved this
