### ISSUE TITLE
Annotations API does not return Alert Annotations if `from` and `to` are specified.

### ISSUE THREAD

**Issue by Routhinator** [grafana/grafana#63130]
**What happened**: When a time range using `from` and `to` is passed to the Annotations API, Alert annotations are not returned. Only manually created annotations are returned.

**What you expected to happen**: All annotations relevant to the query should be returned, regardless of type.

**How to reproduce it (as minimally and precisely as possible)**: 

- Create a dashboard, with a panel that you want to annotate with Alert annotations.
- Create an alert and set Dashboard UID and Panel ID to the appropriate values.
- Create an instance where that alert fires.
- Go to the dashboard, although the heart (indicating theres an associated alert) will show on the panel, no alerts will fire.
- Open the network tab, look for the annotations API query the board is making, open this in a new tab.
- The returned array will be empty. Remove the `from` and `to` parameters from the query.
- The desired Alert annotations will be returned as expected.

**Anything else we need to know?**:
- This doesn't affect the "Status History" window as it only passes `alertId` and not any time range.
- Manually created annotations are returned with time range as expected.

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: Grafana, 9.3.6
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome for Mac
- Grafana plugins: None
- Others:

**Comment by Routhinator** [comment]
Will provide example queries an output in a moment, need to strip proprietary details from them.

**Comment by usmangt** [comment]
Hi @Routhinator,

Thanks for opening this issue.

Can you please point us to the API link which you are using for creating Alert Annotation? I cannot found it in the Documentation which is for creating Alert Annotation.

**Comment by vincent-olivert-riera** [comment]
@usmangt , I'm experiencing the same issue. Since the requester didn't provide the details yet, I will do it.

Here is an API query where two annotations are returned:

```
$ curl -s "${URL}/api/annotations?alertId=7&limit=2&type=alert" -H "Authorization: Bearer ${KEY}" | jq
[
  {
    "id": 381604,
    "alertId": 7,
    "alertName": "",
    "dashboardId": 0,
    "dashboardUID": null,
    "panelId": 0,
    "userId": 0,
    "newState": "Normal",
    "prevState": "Alerting",
    "created": 1676011263375,
    "updated": 1676011263375,
    "time": 1676011260000,
    "timeEnd": 0,
    "text": "vincent-cpu-usage-alert {alertname=vincent-cpu-usage-alert, grafana_folder=Vincent} - ",
    "tags": [],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {
      "values": {}
    }
  },
  {
    "id": 381605,
    "alertId": 7,
    "alertName": "",
    "dashboardId": 0,
    "dashboardUID": null,
    "panelId": 0,
    "userId": 0,
    "newState": "Normal",
    "prevState": "Alerting",
    "created": 1676011268352,
    "updated": 1676011268352,
    "time": 1676011260000,
    "timeEnd": 0,
    "text": "vincent-cpu-usage-alert {alertname=vincent-cpu-usage-alert, grafana_folder=Vincent} - ",
    "tags": [],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {
      "values": {}
    }
  }
]
```

Taking those `created` values as a reference, here is another query that should include those two annotations. However, because `from` and `to` are used at the same time, the result is an empty list:

```
$ curl -s "${URL}/api/annotations?alertId=7&limit=2&type=alert&from=1676011263374&to=1676011268353" -H "Authorization: Bearer ${KEY}" | jq
[]
```

Also, if only one of `from` or `to` are used (not both at the same time), the query returns annotations, however it seems the `from` or `to` parameter is completely ignored. For instance, here is a query that should **not** return an annotation created **before** 1676011263376:

```
$ curl -s "${URL}/api/annotations?alertId=7&limit=2&type=alert&from=1676011263376" -H "Authorization: Bearer ${KEY}" | jq
[
  {
    "id": 381604,
    "alertId": 7,
    "alertName": "",
    "dashboardId": 0,
    "dashboardUID": null,
    "panelId": 0,
    "userId": 0,
    "newState": "Normal",
    "prevState": "Alerting",
    "created": 1676011263375,  # REDACTED: this alert should not be in the list
    "updated": 1676011263375,
    "time": 1676011260000,
    "timeEnd": 0,
    "text": "vincent-cpu-usage-alert {alertname=vincent-cpu-usage-alert, grafana_folder=Vincent} - ",
    "tags": [],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {
      "values": {}
    }
  },
  {
    "id": 381605,
    "alertId": 7,
    "alertName": "",
    "dashboardId": 0,
    "dashboardUID": null,
    "panelId": 0,
    "userId": 0,
    "newState": "Normal",
    "prevState": "Alerting",
    "created": 1676011268352,
    "updated": 1676011268352,
    "time": 1676011260000,
    "timeEnd": 0,
    "text": "vincent-cpu-usage-alert {alertname=vincent-cpu-usage-alert, grafana_folder=Vincent} - ",
    "tags": [],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {
      "values": {}
    }
  }
]
```

**Comment by Routhinator** [comment]
Apologies @usmangt  - sickness derailed me. However, the behaviour we see is identical to the outputs provided by @vincent-olivert-riera

**Comment by Routhinator** [comment]
> Can you please point us to the API link which you are using for creating Alert Annotation? I cannot found it in the Documentation which is for creating Alert Annotation. 

Also @usmangt - flagging that you've misunderstood the issue based on this comment. We are not creating the alert annotations manually - this is a function of the grafana alerting system. 

Manually created annotations work as expected.

**Comment by papagian** [comment]
I'm unable to reproduce it in main:

```
% curl "http://<user>:<password>@localhost:3000/api/annotations?from=1677215949370&to=1677237549370&limit=100&matchAny=false&dashboardUID=f7f331cb-2a94-4d31-b82f-2355ecf0ba17" |jq 
[
  {
    "id": 3,
    "alertId": 1,
    "alertName": "",
    "dashboardId": 127,
    "dashboardUID": "f7f331cb-2a94-4d31-b82f-2355ecf0ba17",
    "panelId": 2,
    "userId": 0,
    "newState": "Alerting",
    "prevState": "Pending",
    "created": 1677237200052,
    "updated": 1677237200052,
    "time": 1677237200000,
    "timeEnd": 1677237200000,
    "text": "#63130 alert rule {alertname=#63130 alert rule, grafana_folder=alerts} - B=0.000000, C=1.000000",
    "tags": [],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {
      "values": {
        "B": 0,
        "C": 1
      }
    }
  },
  {
    "id": 2,
    "alertId": 1,
    "alertName": "",
    "dashboardId": 127,
    "dashboardUID": "f7f331cb-2a94-4d31-b82f-2355ecf0ba17",
    "panelId": 2,
    "userId": 0,
    "newState": "Pending",
    "prevState": "Normal",
    "created": 1677237190051,
    "updated": 1677237190051,
    "time": 1677237190000,
    "timeEnd": 1677237190000,
    "text": "#63130 alert rule {alertname=#63130 alert rule, grafana_folder=alerts} - B=0.000000, C=1.000000",
    "tags": [],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {
      "values": {
        "B": 0,
        "C": 1
      }
    }
  },
  {
    "id": 1,
    "alertId": 1,
    "alertName": "",
    "dashboardId": 127,
    "dashboardUID": "f7f331cb-2a94-4d31-b82f-2355ecf0ba17",
    "panelId": 2,
    "userId": 0,
    "newState": "Normal (Updated)",
    "prevState": "Normal",
    "created": 1677237184543,
    "updated": 1677237184543,
    "time": 1677237184542,
    "timeEnd": 1677237184542,
    "text": "#63130 alert rule {alertname=#63130 alert rule, grafana_folder=alerts} - ",
    "tags": [],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {
      "values": {}
    }
  }
]
```

I keep investigating.

**Comment by papagian** [comment]
I managed to reproduce using grafana `v9.3.6` (but it seems that in main commit: 9cae3f43ed3aa60f3b2c2537fe9fe02e8f84e309 is fixed) and I noticed that the annotations created were missing `epoch_end`:

```
mysql> select id, alert_id, dashboard_id, epoch, epoch_end from annotation;
+----+----------+--------------+---------------+-----------+
| id | alert_id | dashboard_id | epoch         | epoch_end |
+----+----------+--------------+---------------+-----------+
|  1 |        1 |          103 | 1677249590000 |         0 |
|  2 |        1 |          103 | 1677249600000 |         0 |
+----+----------+--------------+---------------+-----------+
2 rows in set (0.00 sec)
```
The query checks for:
`AND a.epoch <= ?  AND a.epoch_end >= ?` therefore if the `epoch_end` is missing then there are no results.

I have noticed that there was a [fix](https://github.com/grafana/grafana/pull/60931) for a similar problem. 
@grafana/alerting-squad-backend Can it be related?

**Comment by Routhinator** [comment]
FWIW - it's great to hear this might be fixed.. but if the query is not returning annotations because they *don't end in the given range of the query* - I consider that broken as well. 

If it's started OR ended in the range being queried, it should be returned. Being explicit, if `epoch` or `epoch_end` land within the query range, they should be being returned. Otherwise you're not providing a complete picture.

**Comment by papagian** [comment]
> FWIW - it's great to hear this might be fixed.. but if the query is not returning annotations because they _don't end in the given range of the query_ - I consider that broken as well.
> 
> If it's started OR ended in the range being queried, it should be returned. Being explicit, if `epoch` or `epoch_end` land within the query range, they should be being returned. Otherwise you're not providing a complete picture.

I agree, that makes sense: I will prepare a fix
thank you for reporting it

**Comment by papagian** [comment]
> Any update on priority here? This is a pretty big deal for alert triage with our self-hosted instance. It's important for engineers responding to pages late at night to have the alert firing period annotated across graphs to catch things more easily.
> 
> I note that this is still in triage inspite of being triaged?

sorry I didn't get time to work on that due to other priorities
however, the problem seems to be fixed in later grafana versions `v9.4.x` and the problematic annotations will be cleaned up
have you tried upgrading to a more recent version? do you still face the problem?

**Comment by vincent-olivert-riera** [comment]
> have you tried upgrading to a more recent version?

Yes, I am using 9.5.3.

```
curl -s "${URL}/api/health"
{
  "commit": "916d9793aa",
  "database": "ok",
  "version": "9.5.3"
}
```

> do you still face the problem?

Yes, the problem still persists.

Querying the last two annotations:

```
$ curl -s "${URL}/api/annotations?alertId=8&limit=2&type=alert" -H "Authorization: Bearer ${KEY}" | jq
[
  {
    "id": 381954,
    "alertId": 8,
    "alertName": "",
    "dashboardId": 2380,
    "dashboardUID": "z5qi8zd4z",
    "panelId": 4,
    "userId": 0,
    "newState": "Normal",
    "prevState": "Alerting",
    "created": 1686280926462,
    "updated": 1686280926462,
    "time": 1686280920000,
    "timeEnd": 1686280920000,
    "text": "vincent-cpu-usage-alert {alertname=vincent-cpu-usage-alert, grafana_folder=Vincent, instance=redacted:9100} - C=0.000000, CPU Load=3.433333",
    "tags": [],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {
      "values": {
        "C": 0,
        "CPU Load": 3.4333333373069763
      }
    }
  },
  {
    "id": 381953,
    "alertId": 8,
    "alertName": "",
    "dashboardId": 2380,
    "dashboardUID": "z5qi8zd4z",
    "panelId": 4,
    "userId": 0,
    "newState": "Normal",
    "prevState": "Alerting",
    "created": 1686280926443,
    "updated": 1686280926443,
    "time": 1686280920000,
    "timeEnd": 1686280920000,
    "text": "vincent-cpu-usage-alert {alertname=vincent-cpu-usage-alert, grafana_folder=Vincent, instance=redacted:9100} - C=0.000000, CPU Load=3.433333",
    "tags": [],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {
      "values": {
        "C": 0,
        "CPU Load": 3.4333333373069763
      }
    }
  }
]
```

Note the `created` timestamps: `1686280926443` and `1686280926462`.
Running a query with both `from=1686280926442` and `to=1686280926463` should include both annotations. Let's see.

```
$ curl -s "${URL}/api/annotations?alertId=8&limit=2&type=alert&from=1686280926442&to=1686280926463" -H "Authorization: Bearer ${KEY}" | jq
[]
```

Same problem: when using both `from` and `to` at the same time, an empty list is returned.

Now I will run a query with just `from=1686280926444`, trying to exclude the alert with a `1686280926443` timestamp.

```
$ curl -s "${URL}/api/annotations?alertId=8&limit=2&type=alert&from=1686280926444" -H "Authorization: Bearer ${KEY}" | jq
[
  {
    "id": 381954,
    "alertId": 8,
    "alertName": "",
    "dashboardId": 2380,
    "dashboardUID": "z5qi8zd4z",
    "panelId": 4,
    "userId": 0,
    "newState": "Normal",
    "prevState": "Alerting",
    "created": 1686280926462,
    "updated": 1686280926462,
    "time": 1686280920000,
    "timeEnd": 1686280920000,
    "text": "vincent-cpu-usage-alert {alertname=vincent-cpu-usage-alert, grafana_folder=Vincent, instance=redacted:9100} - C=0.000000, CPU Load=3.433333",
    "tags": [],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {
      "values": {
        "C": 0,
        "CPU Load": 3.4333333373069763
      }
    }
  },
  {
    "id": 381953,
    "alertId": 8,
    "alertName": "",
    "dashboardId": 2380,
    "dashboardUID": "z5qi8zd4z",
    "panelId": 4,
    "userId": 0,
    "newState": "Normal",
    "prevState": "Alerting",
    "created": 1686280926443,
    "updated": 1686280926443,
    "time": 1686280920000,
    "timeEnd": 1686280920000,
    "text": "vincent-cpu-usage-alert {alertname=vincent-cpu-usage-alert, grafana_folder=Vincent, instance=redacted:9100} - C=0.000000, CPU Load=3.433333",
    "tags": [],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {
      "values": {
        "C": 0,
        "CPU Load": 3.4333333373069763
      }
    }
  }
]
```

As you can see, it did not work.

**Comment by Routhinator** [comment]
This seems to be fixed on Grafana Cloud, it is not fixed on open source.

**Comment by Routhinator** [comment]
There's no workaround I found, and I can confirm this fix has made it to Grafana Cloud, but not seeing it work in OSS.

**Comment by saketbairoliya2** [comment]
@usmangt  / @papagian  - Following up on @Routhinator 's message. Do we've any plans to get the fix to OSS?

**Comment by saketbairoliya2** [comment]
@usmangt  / @papagian  - Any updated here on this?

**Comment by vincent-olivert-riera** [comment]
> this fix has made it to Grafana Cloud, but not seeing it work in OSS.
> [...]
> Do we've any plans to get the fix to OSS?

@usmangt / @papagian - Any updated on this?

**Comment by papagian** [comment]
> > this fix has made it to Grafana Cloud, but not seeing it work in OSS.
> > [...]
> > Do we've any plans to get the fix to OSS?
> 
> @usmangt / @papagian - Any update on this?

which version of grafana do you use? @grafana/alerting-squad can you have a look? is the fix backport-ed?

**Comment by gillesdemey** [comment]
Grafana Cloud uses [Loki for its Alert State Hisotry](https://grafana.com/docs/grafana/latest/alerting/set-up/configure-alert-state-history/) which may explain why it appears "fixed" in Cloud but not OSS (as these are very separate code paths) – can you confirm if you are using the legacy annotations for Alerting or the newer Loki Alert State History?

**Comment by Routhinator** [comment]
Not stale

**Comment by vincent-olivert-riera** [comment]
Not stale.
