### ISSUE TITLE
Hide Alerting tab for users without permissions / anonymous users

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#67300]
## What happened:
I use Grafana with anonymous access turned on to share my dashboard to the public (I cannot use public dashboards feature for now, as they do not support library panels & template variables).
I have noticed that every user can access alerting tab and see all the alerts and contact points.

## What you expected to happen:
It should be possible to restrict access to alerting tab, so users without proper permissions won't see it.

## How to reproduce it (as minimally and precisely as possible):
1. Enable unified alerting
2. Enable Grafana anonymous access
3. Open Grafana when not logged in

## Environment:
- Grafana version: 9.5.1

**Comment by mellieA** [comment]
Related to https://github.com/grafana/grafana/issues/26815

**Comment by jdmaloney** [comment]
I second this, we noticed this today.  With Grafana v8 (classic alerts), anonymous users couldn't see anything related to alerting.  On Grafana v9 (unified alerting), anonymous users can see contact points, silences, notification policies, etc. 

I don't see a way to prevent this though I'm happy to hear if I'm missing something

**Comment by armandgrillet** [comment]
We would need the API to stop returning the list of objects and hide the "Alerting" tab in Grafana when this is the case. This behavior is a regression.

**Comment by yuri-tceretian** [comment]
In 8.5.0 anonymous access was actually broken (https://github.com/grafana/grafana/issues/48731), and was fixed in https://github.com/grafana/grafana/pull/49203. 
I can see the usefulness in this feature but currently, it is expected behavior. My proposal is to add a new option to `[auth.anonymous]` setting and let admins control the access to alerting for anonymous users.

**Comment by mimizone** [comment]
I would like something like the requested feature to be able to at least hide the Contact Points webhook URI endpoint from anonymous/Viewer roles.
Should be considered a secret as much as the credentials etc...

**Comment by dginhoux** [comment]
Hi agree, 

For our guests, it's necessary to hide everything that is not dashbaord/panels

**Comment by d1nuc0m** [comment]
Are there any news on this? The behavior is still present in v12.3.0
