### ISSUE TITLE
[Bug] v4.0.1 legend as table always gives vertical scroll bar

### ISSUE THREAD

**Issue by dutchiechris** [grafana/grafana#6828]
In v4.0.1 using legend as table always gives a vertical scrollbar.  If I make the panel larger, even full screen, the scroll bar does not go away.  In 3.1.1 I did not observe this behavior; the vertical scroll bar was only shown when really needed.

Easy to reproduce, here is a screenshot from play.grafana.org:
![image](https://cloud.githubusercontent.com/assets/917241/20884004/3f33c130-bae9-11e6-82a8-5e68de4693c0.png)

I edited the panel on the left to have a table with values below so you can see the issue occurs if table is below or on right side

**Comment by torkelo** [comment]
strange, looks to be some kind of bug in chrome 54, cannot replicate in any other browser. Tried to find the cause / change some css but everything looks to be in order. Very strange.

**Comment by lindsayleeds** [comment]
Also getting this same bug in Chrome 49.

**Comment by adamcstephens** [comment]
I'm getting this in Chrome 54/55 and Firefox 50. Its worse in Firefox because its not picking up the scrollbar style so it can overlap the metric text.

Chrome
<img width="629" alt="screen shot 2016-12-05 at 2 05 09 pm" src="https://cloud.githubusercontent.com/assets/2071575/20898334/ec33b2aa-baf3-11e6-9803-e0762a745994.png">

Firefox
<img width="782" alt="screen shot 2016-12-05 at 2 04 55 pm" src="https://cloud.githubusercontent.com/assets/2071575/20898339/f460e7ea-baf3-11e6-82d6-2a725ab8eb55.png">

**Comment by torkelo** [comment]
been troubleshooting this, no idea why this started showing and all my attempts to get rid of scroll bar so far has not worked :(

**Comment by lindsayleeds** [comment]
Thanks for looking at it @torkelo .   It seems like such a little thing, but I have downgraded to 3.x until it gets resolved because of the mess it makes of the visual appearance of my graphs.  I hope you are able to figure it out.

**Comment by benrubson** [comment]
Issue in Chrome 55.
No issue in Safari 10.0.2 / Firefox 51.

**Comment by trevorndodds** [comment]
@torkelo the scrollbar is now gone, but the legend is no longer scroll-able it just increases the legend height, is this intended?

![image](https://cloud.githubusercontent.com/assets/10899305/21655056/4cdd5c24-d286-11e6-8930-9531e16a9d65.png)

**Comment by torkelo** [comment]
fixed in https://github.com/grafana/grafana/commit/44b7a26119e66644e62ca60a4eb7e796efc08679

**Comment by trevorndodds** [comment]
@torkelo Thanks, will this be added to 4.1.1? I tried 4.1.0 (Windows) but it seems it was built yesterday.

**Comment by bergquist** [comment]
@trevorndodds Yesterdays windows release of 4.1.0 was a misstake.. (and never announced) Sorry about that. The latest build contains the fix for this issue.

**Comment by bergquist** [comment]
Or not... Looks like we will have to make a 4.1.1

**Comment by trevorndodds** [comment]
thanks, 4.1.1 fixes the growing table but the original issue of the scrollbars being present is still present in this update.

![image](https://cloud.githubusercontent.com/assets/10899305/21891648/b3d080d4-d8a1-11e6-95cf-1363f1a4a715.png)

**Comment by torkelo** [comment]
seems impossible to get rid of it.

**Comment by torkelo** [comment]
Was gone on chrome on mac when we tested yesterday. But I do see it on chrome on linux

**Comment by adamcstephens** [comment]
So we're considering this closed as unfixable?

I'm still getting this on Chrome/Firefox on Mac.

**Comment by cezarsa** [comment]
Running 4.1.1 I was able to "fix" the unwanted scrollbars showing up adding the following style:
```
$('head').append($('<style>.graph-legend-table > tbody { padding-bottom: 1px; }</style>'))
```

I'm not sure why this extra pixel is needed though.

**Comment by torkelo** [comment]
@cezarsa thanks, that strangely fixes it, without any logic but :)
