### ISSUE TITLE
Feature request: Send Public Image URL & clickable links to VictorOps

### ISSUE THREAD

**Issue by wick02** [grafana/grafana#6858]
I saw that VictorOps integration was added with #6421 and I've been playing around with it.

I tested it out and it works great as alerting, but I didn't see an option to send an image and I've seen Victorops being able to handle images in their alerting

I also see URL being passed, but not able to be a clickable link. 

Any chance to add these in? 

![grafanavictor](https://cloud.githubusercontent.com/assets/1821715/20949953/3f38c066-bbd1-11e6-833d-d64be5f4b97c.png)
![newrelic](https://cloud.githubusercontent.com/assets/1821715/20949952/3f37ccd8-bbd1-11e6-833c-5a09ebb0987a.png)
![imageurl](https://cloud.githubusercontent.com/assets/1821715/20949954/3f3d019e-bbd1-11e6-8f9b-f8288226bc6e.png)

**Comment by torkelo** [comment]
@utkarshcmu do you use VictorOps ? I know you tested the PR

**Comment by utkarshcmu** [comment]
@torkelo No, I dont use VictorOps. I just reviewed and tested the PR. @ichekrygin might be able to help here!

**Comment by wick02** [comment]
@utkarshcmu I didn't see anything as well. 

What I do know is that links that are sent using the timeline, the images do render inside the timeline. 

If I get some time and learn go, I'm willing to try and make these changes.

**Comment by ichekrygin** [comment]
@wick02, just to clarify, are you looking for any arbitrary image, or a graph image specifically.

**Comment by ichekrygin** [comment]
@wick02, as for the clickable link, it appears VOps does not detect URL inside the `state_message` field. It also appears that in your example you're using `STATUS URL` field. Is `STATUS URL` a custom field or standard VOps field?

**Comment by ichekrygin** [comment]
for both, image url and clickable link which field should they map in VOps http://victorops.force.com/knowledgebase/articles/Integration/Alert-Ingestion-API-Documentation/

**Comment by wick02** [comment]
Hmmm ya doesn't look like they have anything like that enabled, I see it with their other integrations where they have API keys given out. 

The NewRelic integration was the example I gave before that had the `STATUS URL` field, maybe it's something custom where they have the company work with them to enable that extra layer of functionality.

I'll contact their support and see if there is a field not shown on their REST endpoint documentation, otherwise it might only be solved with them working directly with you guys to setup a key.

**Comment by ichekrygin** [comment]
After poking around, it appears we can use `alert_url` field (appears tobe undocumented) to show the `LINK`.
As for the image, still not quite sure. @wick02 do you have VOps timeline example w/ image?

**Comment by wick02** [comment]
@ichekrygin Yes my third image with the original post shows the example. I blocked out the privy info, but the source was the S3 bucket endpoint posted as a user on the victorops timeline.

**Comment by ichekrygin** [comment]
@wick02, ah... got it. Do you now what does NewRelic use to send the alert, is it EMAIL or API?

**Comment by ichekrygin** [comment]
Yeah... found it. This looks likes VOps provided integration for NewRelic (among others)
![image](https://cloud.githubusercontent.com/assets/324803/20983418/3e6ac7b0-bc71-11e6-9c41-a240f3098523.png)

**Comment by ichekrygin** [comment]
We can 'hack' into it and try to use some additional (undocumented) fields in VOps, but I'd rather not to (since we cannot guarantee that next VOps release won't break our changes). Instead, it would be nice if someone from VOps chime in on this topic.

**Comment by wick02** [comment]
I'll see if I can get someone, the company I'm at has a pretty good rapport with VictorOps.

**Comment by wagner-victorops** [comment]
Hi Fellas.  Eric from VictorOps here.

As long as you include the required fields (message_type, entity_id), you can add any additional fields you like and they will be included in the body of the incident in VictorOps.  This functionality is not going anywhere, so no need to worry about us breaking this with future changes.

{
   "message_type":"critical",
   "entity_id":"Name of the problem",
   "state_message":"Verbose description of the problem",
   "grafana_image":"URL link to image here",
   "this_field":"whatever you want",
   "that_field":"whatever else you want"
}

Let us know if you have any questions ==> support@victorops.com
Or you can contact our integrations guys directly: nate@victorops.com

**Comment by wick02** [comment]
To piggy back on @wagner-victorops he setup a transmogrifier on our account to create an image link to what the ${{state_message}} is

![screenshot 2016-12-07 12 12 30](https://cloud.githubusercontent.com/assets/1821715/20984853/d663281e-bc76-11e6-87eb-bee9250e07e2.png)

**Comment by ichekrygin** [comment]
@wick02 nice, I will play with adding URL and IMAGE fields and post the update.
Speaking of IMAGE, in the issue description it appears you're pulling graph images from S3, do you have a separate process that renders graph's images and saves them on S3?

**Comment by wick02** [comment]
Nope, that's already built in grafana. 

Just define it in the grafana.ini file under the External Image Storage

**Comment by ichekrygin** [comment]
@wagner-victorops It appears there is something else is going on with VictorOps integrations, i.e. there seems to be a "secret sauce" in VOps provided integration plugins to display URL links and Images. I tried to replicate the same functionality using `REST` API and it seems I cannot.

Here is an example of using App Dynamics integration (provided by VictorOps)

Expanded view:
![image](https://cloud.githubusercontent.com/assets/324803/21112915/69d9e216-c05c-11e6-8dd6-29e4e90115ba.png)

Collapsed view:
![image](https://cloud.githubusercontent.com/assets/324803/21112838/27f7abda-c05c-11e6-9d07-3238a0300a96.png)
