### ISSUE TITLE
NetworkError when switching organization

### ISSUE THREAD

**Issue by stevmei** [grafana/grafana#72501]
### What happened?

Error: NetworkError when attempting to fetch resource.

![grafik](https://github.com/grafana/grafana/assets/13609443/3671a36c-1491-40b0-839d-acdf8b30055d)

This happens when switching from a organization with a default dashboard set to another organization. If both organizations have default dashboards set, this error is displayed each time. If none of them has a default dashboard, the error does not occur.

If the same dashboard is reloaded (i.e. F5) the error does not occur.

Maybe helpful JS stack:
```
TypeError: NetworkError when attempting to fetch resource. 7362.acb44db65e8b744c275b.js:26:20566
	Z https://mygrafanainstall.com:3000/public/build/7362.acb44db65e8b744c275b.js:26
	re https://mygrafanainstall.com:3000/public/build/7362.acb44db65e8b744c275b.js:26
	Lr https://mygrafanainstall.com:3000/public/build/5226.48dbd59a341e1b9072d3.js:37
	Zt https://mygrafanainstall.com:3000/public/build/5226.48dbd59a341e1b9072d3.js:175
	initDashboard https://mygrafanainstall.com:3000/public/build/6281.b9f076aaf49d7d0d7d60.js:391
	componentDidMount https://mygrafanainstall.com:3000/public/build/6281.b9f076aaf49d7d0d7d60.js:391
	_c https://mygrafanainstall.com:3000/public/build/5226.48dbd59a341e1b9072d3.js:156
	Kc https://mygrafanainstall.com:3000/public/build/5226.48dbd59a341e1b9072d3.js:156
	Kc https://mygrafanainstall.com:3000/public/build/5226.48dbd59a341e1b9072d3.js:156
	uc https://mygrafanainstall.com:3000/public/build/5226.48dbd59a341e1b9072d3.js:156
	Bh https://mygrafanainstall.com:3000/public/build/5226.48dbd59a341e1b9072d3.js:156
	Xd https://mygrafanainstall.com:3000/public/build/5226.48dbd59a341e1b9072d3.js:156
	Hl https://mygrafanainstall.com:3000/public/build/5226.48dbd59a341e1b9072d3.js:156
	gl https://mygrafanainstall.com:3000/public/build/5226.48dbd59a341e1b9072d3.js:154
	rd https://mygrafanainstall.com:3000/public/build/5226.48dbd59a341e1b9072d3.js:156
	(Async: VoidFunction)
```

### What did you expect to happen?

No error.

### Did this work before?

I cannot tell about older versions because it is a fresh new installation.

### How do we reproduce it?

1. Create 2 organizations
2. Create a simple dashboard with data visualisation
3. Set those dashboards as default dashboard for each organization
4. Switch between those organizations

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: 10.0.3
OS: Ubuntu 22.04.2
Browser: Firefox 115.0.2 (64-Bit)

### Grafana platform?

A downloaded binary

**Comment by ama9910** [comment]
I'm seeing this in Safari on MacOS as well. In Safari the error message is "Load failed". OK on Chrome. 
I'm running grafana/grafana:10.0.3 docker image connected to Postgres 15 DB (also occurs on 10.0.2). Brand new deployment and easily reproducible.

**Comment by usmangt** [comment]
Hi @stevmei,

Thanks for opening this issue.

We will take a look into it and will get update you soon.

**Comment by usmangt** [comment]
Hi @stevmei and @ama9910 

I could reproduce it on my machine but the steps are a bit different as when I was switching among Org, I got that "Network error".

As it is not v.clear as how you created the dashboard i.e. from the "admin" account OR you created it like this:

1- Login to UI as Org=1
2- Create a new Dashboard and name it Test123
3- select org1 and create a dashboard and under Administration -> Default preferences ->  Default dashboard to be "Test123"
4- Switch to Org=2
5- Repeat step 2 and 3
6- Then start switching among Orgs?

**Comment by usmangt** [comment]
As I was able to reproduce this also on Firefox browser, For me it happened as soon as bookmarked the 1st dashboard as default in Org1 and switch to Org2 and then again switch to Org1 (a bit tricky but reproducible)

**Comment by ama9910** [comment]
Yes setting any dashboard as default will cause the error to occur when switching back into that org from another org.

**Comment by dprokop** [comment]
This seems to me like a JS resource loading error.
1. Can you please clean your browser network cache and see if the problem persist?
2.  Can you please have a look at Network tab in developer tools and see if there are any API requests failing? 

FYI - I have not managed to reproduce this problem.

**Comment by jacksongoode** [comment]
I see this as well with the outline steps above.

**Comment by natellium** [comment]
👋 I wasn't able to reproduce this in 10.2. Seeing this might be related to https://github.com/grafana/grafana/issues/76723, are you able to reproduce this issue in that version? Thanks!

**Comment by tobhv** [comment]
as is described in https://github.com/grafana/grafana/issues/76723 only a very short appearance of the error is there when i used firefox. are there plans to backport this to 9.5.x ?

**Comment by natellium** [comment]
@grafana/grafana-frontend-platform passing this over as it seems may be a leftover from #76723

**Comment by ashharrison90** [comment]
hi 👋 believe this has been fixed - i cannot reproduce in any version of chrome/safari/firefox, even the "very short appearance" mentioned. shout if you have a reliable reproduction on grafana v10.2.x versions and i'll reopen

> as is described in #76723 only a very short appearance of the error is there when i used firefox. are there plans to backport this to 9.5.x ?

no plans to backport this to 9.5.x. we generally only backport critical/security fixes to the previous major branch 👍

**Comment by SonuJain7** [comment]
Hi @ashharrison90 and Team,

We were under the impression that this issue had been resolved in the 10.2.x release. However, we recently validated the behavior with Grafana 12.3.4 using Firefox 148.0, and the issue still appears to be reproducible.

Therefore, we are reopening this issue and would appreciate your assistance in investigating the behavior and confirming whether any additional fix or configuration is required.

**Steps to Reproduce**

1. Open Grafana using Firefox 148.0.
2. From the left navigation panel, select any navigation item, for example: 
     - Dashboards
     - User and access
3. Use the Organization switcher in the UI to switch to a different organization.

**Expected Behavior**
The organization switch should complete successfully without any errors, and the corresponding page/dashboard should load as expected.

**Actual Behavior**
An error popup/dialog is displayed after switching the organization:

- Failed to load dashboard
- Network Error when attempting to fetch resource

The issue appears to be specific to Firefox based on our current observation. 

Thank you for your assistance.
