### ISSUE TITLE
Unable to import the grafana dashboard in Grafana Version 3.1.1

### ISSUE THREAD

**Issue by kapil514** [grafana/grafana#7915]
Hi All,

I tried to export grafana dashboard  with ManageSetting => View Json and I imported same json with import option in grafana UI it was throwing error :  "JSON.parse: unexpected character at line 1 column 1 of the JSON data" 

I also tried to exported the dashboard via curl and imported the same json via curl and it was throwing below error.

 curl -k -X POST http://HOSTNAME/api/dashboards/db -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Authorization: Bearer XXXXXX' -d FileJson.json 

[{"classification":"DeserializationError","message":"invalid character '/' looking for beginning of value"},{"fieldNames":["Dashboard"],"classification":"RequiredError","message":"Required"}]

Any idea what is the issue and how can I resolve this

**Comment by torkelo** [comment]
First the first import paste JSON.parse error fixed in later versions (4.x) 

For the second error if your using the api you need to wrap the dashboard json model in a dashboard property: 
http://docs.grafana.org/http_api/dashboard/

**Comment by MahadevG** [comment]
I am trying to import dashboard using grafna API. But I get error as below.
[{"fieldNames":["Dashboard"],"classification":"RequiredError","message":"Required"}]
Please any one help me to solve this error.
Please include this information:
What Grafana version are you using?

5.1.3
What datasource are you using?

Influx
What OS are you running grafana on?

Windows
What did you do?

Here is my python code
import requests

headers = {
'Content-Type': 'application/json;charset=UTF-8',
}

data = open('C:/Users/Mahadev/Desktop/Dashboard.json', 'rb').read()
response = requests.post('http://admin:admin@localhost:3000/api/dashboards/db', headers=headers, data=data)
print (response.text)

And cURL -
curl --user admin:admin "http://localhost:3000/api/dashboards/db" -X POST -H "Content-Type:application/json;charset=UTF-8" --data-binary @c:/Users/Mahadev/Desktop/Dashboard.json

**Comment by marefr** [comment]
@MahadevG you've already created an issue for this. Please don't hijack other closed issues!

**Comment by yanhongwang** [comment]
Hi @torkelo 

I use grafana:5.0.4. I could import dashboard json to grafana by **Web UI** successfully.

But when I tried to import dashboard json to grafana by **curl rest api**, I still get the **second error** message like this original post.

curl --silent --user admin:admin --request 'POST' http://IP/api/dashboards/db --header 'Content-Type: application/json' --data-binary ./development.json | jq .
[
  {
    "classification": "DeserializationError",
    "message": "invalid character '.' looking for beginning of value"
  },
  {
    "fieldNames": [
      "Dashboard"
    ],
    "classification": "RequiredError",
    "message": "Required"
  }
]

And http://docs.grafana.org/http_api/dashboard/ seems not mention 'import dashboard', right?

Thanks very much.

**Comment by yanhongwang** [comment]
Hi @marefr 

Thanks for response.

I made export and import available right now.

But, I need to do some patch with appending 'dashboard' this field to exported json file.
And then import it by curl successfully.

**Comment by marefr** [comment]
@yanhongwang Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

**Comment by nicolasps** [comment]
Just for information. Regarding the original question  of @kapil514.
``
He was getting this error because he was typing:
`curl -k -X POST http://HOSTNAME/api/dashboards/db -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Authorization: Bearer XXXXXX' **-d FileJson.json**`

instead of doing something like:
`curl -k -X POST http://HOSTNAME/api/dashboards/db -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Authorization: Bearer XXXXXX' **-d "$(cat FileJson.json)"**`

**Comment by itaydj** [comment]
Thanks @nicolasps for your last comment, saved my day
