### ISSUE TITLE
Dashboard list doesn't update with Custom Variables

### ISSUE THREAD

**Issue by Jumper2105** [grafana/grafana#79402]
### What happened?

Changed a custom variable with the Options "yes" and "no".
Dashboard list URL doesn't update.
![Bug](https://github.com/grafana/grafana/assets/59748956/58e340a3-6287-4f13-9bd4-50359f1de3d9)

### What did you expect to happen?

Dashboard list URL updated with new custom variable value

### Did this work before?

Don't know, but with other variables it works.

### How do we reproduce it?

1. Create a Custom Variable 
2. Edit the dashboard list panel and enable the "Include current template variable values" option

![Variable](https://github.com/grafana/grafana/assets/59748956/e1bc74dc-b21c-4d0b-a568-2f3e9f6ecb79)
![Dashboard](https://github.com/grafana/grafana/assets/59748956/866f45ed-690f-4193-8039-e20e2559045d)
3. Change Variable and hover over a page to show the URL
4. The new value selected from the var drop-down menu does not pass down to the URL 

### Environment (with versions)?

Grafana: v10.2.2 
OS: Windows 10 Pro
Browser: 120.0 (64-Bit)

### Grafana platform?

Docker

**Comment by Jumper2105** [comment]
Sometimes also doesn't work with Query Variables

**Comment by tonypowa** [comment]
hi @Jumper2105 

Thank you for opening this issue

I could reproduce it in v.10.2.2. | FIrefox 121.0 (64-bit)

Adding issue to Frontend platform team's board

**Comment by L-M-K-B** [comment]
Hi @Jumper2105, I tried to reproduce the issue locally (Grafana v10.3.0 | 121.0 (64-bit)) but always got the right values in the URL. However I will consult with my team and come back to you later this week.

**Comment by joshhunt** [comment]
I believe we fixed this in https://github.com/grafana/grafana/pull/77850 

Not sure where this has been released yet.

**Comment by L-M-K-B** [comment]
According to the PR's milestone it got released with v10.2.3 about 3 weeks ago. @Jumper2105 could you please update your version of Grafana and check whether the bug is gone?

**Comment by joshhunt** [comment]
Tested myself, confirmed it's a dupe of https://github.com/grafana/grafana/issues/76800 and was fixed in 10.2.3.

@Jumper2105 If you're still having problems after testing with the latest version of grafana, please comment tagging one us so we can investigate. A sample dashboard (Share > Export > Export for sharing externally) would be appreciated!

**Comment by Hackmeat** [comment]
hello, as of today, i am working with grafana 11.3.0 this exact issue still exsists
