### ISSUE TITLE
Panels show's PromQL warnings

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#84636]
### What happened?

When PromQL is unhappy with your metrics name, it generates a warning. This warning now ends up on the panel
![image](https://github.com/grafana/grafana/assets/2118079/4a86519e-876a-46a7-a70f-a256961be866)

### What did you expect to happen?

This kind of warning should not appear on a panel, or at least have an option to disable

### Did this work before?

yes

### How do we reproduce it?

1. add a panel using the Prometheus and use a rate on a metric that does not ends with total, sum, count or bucket
2.
3.

### Is the bug inside a dashboard panel?

| Key | Value |
|--|--|
| Panel | stat @ 10.4.0 |
| Grafana | 10.4.0 (03f502a94d17f7dc4e6c34acdf8428aedd986e4c) // Open Source |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "class": "small_stat",
      "fieldConfig": {
        "defaults": {
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              }
            ]
          },
          "decimals": 1,
          "unit": "si:"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "reduceOptions": {
          "values": false,
          "calcs": [
            "last"
          ],
          "fields": ""
        },
        "orientation": "auto",
        "textMode": "auto",
        "wideLayout": true,
        "colorMode": "value",
        "graphMode": "none",
        "justifyMode": "auto",
        "showPercentChange": false
      },
      "pluginVersion": "10.4.0",
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "type": "numeric-multi",
                  "typeVersion": [
                    0,
                    1
                  ],
                  "custom": {
                    "resultType": "vector"
                  },
                  "notices": [
                    {
                      "severity": "warning",
                      "text": "PromQL info: metric might not be a counter, name does not end in _total/_sum/_count/_bucket: \"scylla_alternator_operation\" (1:10)"
                    }
                  ],
                  "executedQueryString": "Expr: sum(rate(scylla_alternator_operation{instance=~\".*\",cluster=\"\", dc=~\".*\", shard=~\".*\"}[60s]))\nStep: 15s",
                  "preferredVisualisationType": "graph"
                },
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time"
                    },
                    "config": {
                      "interval": 15000
                    }
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64"
                    },
                    "labels": {},
                    "config": {
                      "displayNameFromDS": "sum(rate(scylla_alternator_operation{instance=~\".*\",cluster=\"\", dc=~\".*\", shard=~\".*\"}[60s]))"
                    }
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1710684428180
                  ],
                  [
                    23105.07499999999
                  ]
                ]
              }
            }
          ]
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Reproduced with embedded data",
      "type": "stat"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >stat @ 10.4.0</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[prometheus]</td>\n    </tr>\n    \n    <tr><th>Data</th><td> 1 frames, 2 fields, 1 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>10.4.0 (03f502a94d17f7dc4e6c34acdf8428aedd986e4c) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"datasource\": {\n    \"uid\": \"P1809F7CD0C75ACF3\",\n    \"type\": \"prometheus\"\n  },\n  \"class\": \"small_stat\",\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"color\": \"green\",\n            \"value\": null\n          }\n        ]\n      },\n      \"decimals\": 1,\n      \"unit\": \"si:\"\n    },\n    \"overrides\": []\n  },\n  \"gridPos\": {\n    \"h\": 4,\n    \"w\": 3,\n    \"x\": 17,\n    \"y\": 5\n  },\n  \"id\": 15,\n  \"options\": {\n    \"reduceOptions\": {\n      \"values\": false,\n      \"calcs\": [\n        \"last\"\n      ],\n      \"fields\": \"\"\n    },\n    \"orientation\": \"auto\",\n    \"textMode\": \"auto\",\n    \"wideLayout\": true,\n    \"colorMode\": \"value\",\n    \"graphMode\": \"none\",\n    \"justifyMode\": \"auto\",\n    \"showPercentChange\": false\n  },\n  \"pluginVersion\": \"10.4.0\",\n  \"targets\": [\n    {\n      \"expr\": \"sum(rate(scylla_alternator_operation{instance=~\\\"[[node]]\\\",cluster=\\\"$cluster\\\", dc=~\\\"$dc\\\", shard=~\\\"[[shard]]\\\"}[60s]))\",\n      \"instant\": true,\n      \"intervalFactor\": 1,\n      \"refId\": \"A\",\n      \"step\": 40,\n      \"datasource\": {\n        \"uid\": \"P1809F7CD0C75ACF3\",\n        \"type\": \"prometheus\"\n      }\n    }\n  ],\n  \"timeFrom\": null,\n  \"timeShift\": null,\n  \"title\": \"Operations/s\",\n  \"type\": \"stat\"\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: Operations/s // 2024-03-18 12:03:27",
  "tags": [
    "debug",
    "debug-stat"
  ],
  "time": {
    "from": "2024-03-17T13:08:35.733Z",
    "to": "2024-03-17T14:07:08.180Z"
  }
}
```
</details>

### Environment (with versions)?

Grafana: 10.4.0
OS: Docker
Browser: chrome

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

**Comment by devsecops-pe** [comment]
Hi, same issue here

**Comment by svmaris** [comment]
I believe this feature was introduced in [this PR](https://github.com/grafana/grafana/pull/79146)

**Comment by usmangt** [comment]
Hi @svmaris 

Thanks for referencing the PR. @amnonh I can see that the PR is now fixed and therefore closing this. If incase it is still causing problems then kindly let me know so that I can repoen it again

**Comment by agido-malter** [comment]
Please make this configurable. We use a lot of counter which shows now the notice triangle

**Comment by Matt-UKTX** [comment]
Same issue here.  Please fix.

**Comment by mnorrsken** [comment]
This is annoying, all metrics from SNMP causes these warnings. Do these warning icons really have to be on the grafana panels?

**Comment by StremCipher** [comment]
I have checked multiple versions of Grafana because [this comment](https://github.com/ChainSafe/lodestar/issues/6627#issuecomment-2266680213) mentions that the issue was fixed in one of them. I tested the following versions, but the issue still persists
grafana : 8.4.6
grafana : 10.4.2
grafana : 11.1.4
grafana : 11.1.3
I just wanted to confirm if this is a valid bug or not.

**Comment by a-abella** [comment]
My Nginx Ingress Controller dashboards have become an avalanche of warning symbols.

**Comment by justinfx** [comment]
Just hit this after a grafana upgrade. Please make configurable.

**Comment by Notedop** [comment]
I agree that this should be configurable via panel general options. When in panel edit mode the warning is useful, but please don't propagate it to the dashboard user interface itself.

**Comment by StremCipher** [comment]
> Looks like this got fixed/reverted in Grafana Cloud within the last couple days, FYI
@a-abella  can you tell me which version exactly 
because I can still see this in the latest version: 11.2.0

**Comment by briend** [comment]
A global configuration option would be great

**Comment by data-dude** [comment]
probably 99% of people don't want this feature.  why would you put it there?

**Comment by phyber** [comment]
Just noticed this since I was creating a new dashboard which uses a lot of SNMP via Prometheus and SNMP Exporter. An option to disable it for specific queries would be appreciated.

**Comment by walirazzaq** [comment]
+1

**Comment by StremCipher** [comment]
Just and FYI : if you are using prometheus as underlying data source then updating the prometheus version might fix this 
it worked for me : 
- grafana version : 11.4.0
- prometheus version : v2.55.1(previously it was v2.52.0)

**Comment by pcgeek86** [comment]
I'm having the same problem, where an SNMP `counter` query is showing a warning, when I use the `rate()` function to calculate the difference over each period.
I posted about it on the forums: https://community.grafana.com/t/dashboard-query-warning-metric-might-not-be-a-counter/153754

The error is:

> metric might not be a counter

My Prometheus service version is `2.53.5`.

![Image](https://github.com/user-attachments/assets/6d1f0214-ce3e-42b8-a5ce-3ff2317ba6c5)

**Comment by davidje994** [comment]
Still an issue on  Grafana v12.2.1
