### ISSUE TITLE
Log scale looks weird in 4.4.1 

### ISSUE THREAD

**Issue by PhantomPhreak** [grafana/grafana#8835]
After updating to Grafana 4.3 axes with log scale (base 2) looks wierd on my graphs:
![logscale](https://user-images.githubusercontent.com/8307692/28102510-e236adae-66f9-11e7-8783-1eda5c76193c.png)

I'm using auto Y-min and Y-max there.

Problem was reported in #8244 but still not fixed in 4.4.1

**Comment by torkelo** [comment]
looks like the  decimal issue has been fixed in 4.4

<img width="277" alt="screen shot 2017-07-12 at 07 21 02" src="https://user-images.githubusercontent.com/10999/28102929-ebb2eba8-66d2-11e7-9955-f15d32b41383.png">

**Comment by PhantomPhreak** [comment]
Wait-wait, i'm using 4.4.1 and still have this problem! It wasn't fixed in 4.4!

**Comment by torkelo** [comment]
You said 
> After updating to Grafana 4.3 

Strange, unable to replicate the it here.

**Comment by PhantomPhreak** [comment]
Right, problem appeared after upgrading to 4.3, and still exist in 4.4.1
You can try to put some metrics on the graph in wider range (as i did, for example)
