### ISSUE TITLE
Geomap: Fit to data not working following recent update

### ISSUE THREAD

**Issue by lucyjstephenson** [grafana/grafana#89777]
### What happened?

Maps will now stay zoomed out to the baselayer instead of zooming to fit data as it used to with the below settings: 
![image](https://github.com/grafana/grafana/assets/112892956/98342fa1-5ed7-4b36-ad06-accf21fdf299)
I assume this has something to do with the update allowing keyboard interaction with maps for zooming in and out. 

### What did you expect to happen?

You would expect the map to zoom to just fit data in the layers we have added to the map

### Did this work before?

Yes, Grafana 11 worked

### How do we reproduce it?

1. Have a Geomap panel with a baselayer and at least one other layer - our layer is a 'route' type. 
2. Configure the settings as shown above to fit to data

### Environment (with versions)?

Grafana: 11.1
OS:
Browser: Chrome

### Grafana platform?

None

**Comment by lucyjstephenson** [comment]
From further investigation it looks like the feature of zooming in/out using the keyboard doesn't work either. It zooms out to around 1.2x the whole map of the world but will not zoom in.

**Comment by jutkko** [comment]
@lucyjstephenson  Thanks for reporting, I am seeing this problem as well.

**Comment by jutkko** [comment]
Looks like this issue should be fixed in the next patch release, it's already merged here https://github.com/grafana/grafana/pull/89248.

**Comment by lux4rd0** [comment]
I just discovered the same after upgrading to Grafana v11.1.0 (5b85c4c2fc) - thanks for the quick upcoming fix!!

**Comment by tonypowa** [comment]
>Looks like this issue should be fixed in the next patch release, it's already merged here https://github.com/grafana/grafana/pull/89248.

thanks for sharing the fix @jutkko 

closing the issue
feel free to comment if the issue persisted after the upgrade

**Comment by chrisella** [comment]
I'm on 11.1.3 and seem to be experiencing the same issue still.

![image](https://github.com/user-attachments/assets/86c1cd0d-a873-45b2-a470-35fc100daf91)

**Comment by tonypowa** [comment]
FYI @drew08t

**Comment by mampersat** [comment]
+1

**Comment by DEEJCUK** [comment]
last working version seems to be 11.0.0

**Comment by hobias** [comment]
I have the same issue. Unfortunately not working in Grafana v11.1.4 (13173c9874)

**Comment by drew08t** [comment]
> FYI @drew08t

Thanks for the mention! We are looking into this and should have a fix soon.

**Comment by swiffer** [comment]
@drew08t any update on this one? We have been hoping for a fix in 11.2.1.

**Comment by zanoii** [comment]
Since the issue only affects route type layers, this workaround works until a fix has been released:

- Create a new map layer, using the same data as your route layer but with layer type "Markers".
- Set color of the new layer to fixed color and select transparent.
- Make sure initial zoom takes all layers into account: Map View -> Data -> All layers.

Initial zoom should now work as intended.

**Comment by TheBepps** [comment]
> Since the issue only affects route type layers, this workaround works until a fix has been released:
> 
> * Create a new map layer, using the same data as your route layer but with layer type "Markers".
> * Set color of the new layer to fixed color and select transparent.
> * Disable Legend and Tooltip on the dummy layer.
> * Make sure initial zoom takes all layers into account: Map View -> Data -> All layers.
> 
> Initial zoom should now work as intended.

Thanks for the workaround, @zanoii ! It works perfectly as a temporary solution until a proper fix is released.

**Comment by Donixon** [comment]
> Since the issue only affects route type layers, this workaround works until a fix has been released:
> 
>     * Create a new map layer, using the same data as your route layer but with layer type "Markers".
> 
>     * Set color of the new layer to fixed color and select transparent.
> 
>     * Disable Legend and Tooltip on the dummy layer.
> 
>     * Make sure initial zoom takes all layers into account: Map View -> Data -> All layers.
> 
> 
> Initial zoom should now work as intended.

This works well if you have lot's of data about position. I have a GPS module connected by LORA. Not so much data is generated, so it wont plot a route with markers, just some random dots :^)

Looking forward to the fix of this issue.

**Comment by swiffer** [comment]
the markers layer is only used for positioning, the route layer should still exist.

**Comment by MatinF** [comment]
We also verified that the work-around works, but it is highly impractical to implement for end users. We have a very hundreds of companies using the router layer for GPS position visualization in Grafana Cloud, so it is vital that this is resolved. We really hope this gets prioritized for an upcoming patch

**Comment by MatinF** [comment]
Any updates on this?

**Comment by drew08t** [comment]
> Any updates on this?

Sorry for the delay. I have a PR up to address this!
