### ISSUE TITLE
Dashboard Panels: in v11 hidden queries executed with "mixed" datasource

### ISSUE THREAD

**Issue by k-meister** [grafana/grafana#92969]
### What happened?

On Dashboard Panel, hidden queries get executed, if panel uses "Mixed" datasource.

### What did you expect to happen?

Hidden queries not being executed

### Did this work before?

Yes. Versions before v11 are OK, v11+ are affected

### How do we reproduce it?

1. Find a panel with multiple queries, say [this one](https://play.grafana.org/d/e3351884-c207-4689-ad34-dfef36330b50/kube-state-metrics-pods-by-namespace?var-datasource=grafanacloud-prom&var-cluster=play-db-cluster&var-lokids=$__all&var-namespace=kube-system&from=now-30m&to=now&timezone=UTC&editPanel=7&tab=queries)
2. Change panel datasource to "Mixed"
3. Hide one of the queries
4a. Introduce a syntax error in that query. Panel goes red and displays datasource error (expected behavior: nothing happens)
4b. Go to query inspector & explore request data. Hidden query is sent to datasource (expected behavior: only active queries executed)

### Is the bug inside a dashboard panel?

Yes. "How to reproduce" section should be sufficient

### Environment (with versions)?

Grafana: v11+
OS: Sonoma 14.2.1
Browser: Chrome 124.0.6367.210 arm64, Safari 17.2.1 (19617.1.17.11.12) (presumably any browser)

### Grafana platform?

I don't know

### Datasource(s)?

Mixed

**Comment by TimSimmons** [comment]
I can confirm this is happening for me as well and is very disruptive.

**Comment by nishkrishnan** [comment]
This is happening to me as well. Any ETA to get this fixed?

**Comment by axelavargas** [comment]
@k-meister, thank you for reporting this; I think it's fixed in https://github.com/grafana/grafana/pull/100370.

Would any of you—@TimSimmons, @nishkrishnan, or yourself—confirm whether the latest Grafana version fixes the issue?

**Comment by axelavargas** [comment]
Thanks @k-meister, I could reproduce the issue!

**Comment by TimSimmons** [comment]
<img width="1966" height="1181" alt="Image" src="https://github.com/user-attachments/assets/0df1c57b-24e9-4f6d-a2c3-1ccaf4655e74" />

this appears to still be an issue (from play.grafana.org)

**Comment by shivanshsharma13** [comment]
Hi Guys, Greetings! 

I've been looking into this issue and found the root cause. The `MixedDataSource` query method filters out self-referencing queries but never checks whether a query is hidden before batching and executing them. This is why hidden queries still get sent to the datasource despite the eye icon being toggled off.
Verified the fix locally, hidden queries no longer execute and a panel with a broken hidden query no longer goes red. Opening a PR shortly.

**Comment by ifrost** [comment]
> This is why hidden queries still get sent to the datasource despite the eye icon being toggled off.

Are queries sent to only Grafana Backend or they reach all the way through to Prometheus? 🤔
