### ISSUE TITLE
Grafana fails to start after upgrade to v10.4.11

### ISSUE THREAD

**Issue by rda0** [grafana/grafana#95219]
### What happened?

Grafana fails to start after upgrade to v10.4.11.

Error with db migrations (`Executing migration failed`, `You have an error in your SQL syntax;`):

```
logger=settings t=2024-10-23T08:06:14.635605662+02:00 level=info msg="Starting Grafana" version=10.4.11 commit=a40fee9162ae895de857f0e095401c76a4771188 branch=HEAD compiled=2024-10-23T08:06:14+02:00 
logger=settings t=2024-10-23T08:06:14.635925405+02:00 level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini 
logger=settings t=2024-10-23T08:06:14.635957585+02:00 level=info msg="Config loaded from" file=/etc/grafana/grafana.ini 
logger=settings t=2024-10-23T08:06:14.635970578+02:00 level=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana" 
logger=settings t=2024-10-23T08:06:14.635980671+02:00 level=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana" 
logger=settings t=2024-10-23T08:06:14.63599288+02:00 level=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins" 
logger=settings t=2024-10-23T08:06:14.636005952+02:00 level=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning" 
logger=settings t=2024-10-23T08:06:14.636030541+02:00 level=info msg=Target target=[all] 
logger=settings t=2024-10-23T08:06:14.636062617+02:00 level=info msg="Path Home" path=/usr/share/grafana 
logger=settings t=2024-10-23T08:06:14.636075266+02:00 level=info msg="Path Data" path=/var/lib/grafana 
logger=settings t=2024-10-23T08:06:14.636087346+02:00 level=info msg="Path Logs" path=/var/log/grafana 
logger=settings t=2024-10-23T08:06:14.636099561+02:00 level=info msg="Path Plugins" path=/var/lib/grafana/plugins 
logger=settings t=2024-10-23T08:06:14.636111834+02:00 level=info msg="Path Provisioning" path=/etc/grafana/provisioning 
logger=settings t=2024-10-23T08:06:14.636124047+02:00 level=info msg="App mode production" 
logger=sqlstore t=2024-10-23T08:06:14.636418719+02:00 level=info msg="Connecting to DB" dbtype=mysql 
logger=migrator t=2024-10-23T08:06:14.638238135+02:00 level=info msg="Starting DB migrations" 
logger=migrator t=2024-10-23T08:06:14.653272202+02:00 level=info msg="Executing migration" id="delete orphaned service account permissions" 
logger=migrator t=2024-10-23T08:06:14.663927288+02:00 level=error msg="Executing migration failed" id="delete orphaned service account permissions" error="failed to delete orphaned service accounts: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS p WHERE p.kind = 'serviceaccounts' AND p.identifier IN(?,?,?)' at line 1" duration=10.650119ms 
logger=migrator t=2024-10-23T08:06:14.663991423+02:00 level=error msg="Exec failed" error="failed to delete orphaned service accounts: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS p WHERE p.kind = 'serviceaccounts' AND p.identifier IN(?,?,?)' at line 1" sql="code migration" 
```

I was able to downgrade to v10.4.10 again.

### What did you expect to happen?

No error

### Did this work before?

Yes

### How do we reproduce it?

1. Upgrade
2. REstart

### Environment (with versions)?

Grafana: 10.4.11
OS: Debian GNU/Linux 12 (bookworm)
Browser: FF

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by kalleep** [comment]
Hey, what database are you using for grafana?

**Comment by rda0** [comment]
> Hey, what database are you using for grafana?

Sorry for missing that info.

DB Server: `mariadb-server/stable,now 1:10.11.6-0+deb12u1 amd64 [installed]`

**Comment by kalleep** [comment]
Yeah so then https://github.com/grafana/grafana/pull/95226 should fix it.

I wrote this in the pr but I will repeat it here. MariaDB is not an officially supported database to use with grafana, the full list can be viewed here: https://grafana.com/docs/grafana/latest/setup-grafana/installation/#supported-databases

In most cases a database such as MariaDB should work but we don't do any integration testing with it. So I highly encourage you to switch to one from that list so you are not affected by something similar in the future. I have backported the fix so it should be included of the next release of whatever version you are using from v10.4.x until latest version

**Comment by greenmotion** [comment]
Same issue with 11.3.0.  After upgrading to 11.3.0, my installation failed with:

```
logger=migrator t=2024-10-23T09:55:17.084219127-05:00 level=info msg="Starting DB migrations"
logger=migrator t=2024-10-23T09:55:17.094025855-05:00 level=info msg="Executing migration" id="delete orphaned service account permissions"
logger=migrator t=2024-10-23T09:55:17.09540959-05:00 level=error msg="Executing migration failed" id="delete orphaned service account permissions" error="failed to delete orphaned service accounts: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS p WHERE p.kind = 'serviceaccounts' AND p.identifier IN(?)' at line 1" duration=1.382495ms
logger=migrator t=2024-10-23T09:55:17.095460844-05:00 level=error msg="Exec failed" error="failed to delete orphaned service accounts: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS p WHERE p.kind = 'serviceaccounts' AND p.identifier IN(?)' at line 1" sql="code migration"
logger=migrator t=2024-10-23T09:55:17.096592077-05:00 level=info msg="Unlocking database"
```

I had to roll back to the previous version. :(

**Comment by melroy89** [comment]
Same here.. with Grafana 11.3 using MariaDB. It just breaks... I hope this can be prevented in the future my incorporating MariaDB is your tests.

**Comment by rda0** [comment]
@kall@kalleep You write in https://github.com/grafana/grafana/pull/95226 about a new feature of MariaDB `v11.6` which a is bleeding edge Release Candidate version. And that Debian 12 Bookworm (stable) ships MariaDB `v10.11`.

Could it be that you misread the Debian package version format: `mariadb-server/stable,now 1:10.11.6-0+deb12u1`?
`11.6` looks quite similar to `10.11.6`.

On Debian we will not have `11.6` for a long time. Currently `11.4` is being tested in the unstable releases, see: https://packages.debian.org/search?keywords=mariadb-server

Since Grafana [officially supports Debian](https://grafana.com/docs/grafana/latest/setup-grafana/installation/#supported-operating-systems) it would be very wishful to support it with the Debian shipped default MySQL server:

```
+phd-test-bookworm:~# apt show default-mysql-server
Package: default-mysql-server
Version: 1.1.0
Priority: optional
Section: database
Source: mysql-defaults
Maintainer: Debian MySQL Maintainers <pkg-mysql-maint@lists.alioth.debian.org>
Installed-Size: 9,216 B
Depends: mariadb-server
Breaks: mysql-server (<< 5.7)
Download-Size: 2,860 B
APT-Sources: http://debian.ethz.ch/debian bookworm/main amd64 Packages
Description: MySQL database server binaries and system database setup (metapackage)
 MySQL is a fast, stable and true multi-user, multi-threaded SQL database
 server. SQL (Structured Query Language) is the most popular database query
 language in the world. The main goals of MySQL are speed, robustness and
 ease of use.
 .
 This package depends on the default implementation of all the infrastructure
 needed to setup system databases.
```

After MySQL was bought by Oracle in 2009, Debian switched to the [fork MariaDB](https://en.wikipedia.org/wiki/MariaDB). And we have no possibility or desire to use Oracle MySQL.

We are using Grafana since way before 5.0 and have always been using MySQL/MariaDB as database for it. We also have way more experience and infrastructure for MariaDB as for PostgreSQL and would prefer if we do not have to change the DB server due to that change.

It looks like this started between [20220625](https://web.archive.org/web/20220625022922/https://grafana.com/docs/grafana/latest/setup-grafana/installation/):

![Image](https://github.com/user-attachments/assets/e4d7031c-fa16-4b4c-beab-33e77302b811)

and [20220831](https://web.archive.org/web/20220831101944/https://grafana.com/docs/grafana/latest/setup-grafana/installation/):

![Image](https://github.com/user-attachments/assets/932b9929-a6b0-47ee-b046-16284db52c9f)

and then [20241002](https://web.archive.org/web/20241002184936/https://grafana.com/docs/grafana/latest/setup-grafana/installation/):

![Image](https://github.com/user-attachments/assets/4e8bb594-3b31-4178-ad93-5b1567a6f1dd)

I could not find anything mentioning this change or requirement in any release notes since Grafana version 5.

By the way, do you have a git repository of the documentation?

**Comment by cr0c0dylus** [comment]
My Grafana also broke during migration, and the issue was resolved by forcing it to version 11.1.0. The database version hasn’t changed (10.6.19+maria~ubu2204). Here’s the log:

`
logger=settings t=2024-10-30T15:40:59.840498591Z level=info msg="Starting Grafana" version=11.3.0 commit=d9455ff7db73b694db7d412e49a68bec767f2b5a branch=HEAD compiled=2024-10-30T15:40:59Z
...
logger=sqlstore t=2024-10-30T15:40:59.841135621Z level=info msg="Connecting to DB" dbtype=mysql
logger=migrator t=2024-10-30T15:40:59.844117187Z level=info msg="Locking database"
logger=migrator t=2024-10-30T15:40:59.844956542Z level=info msg="Starting DB migrations"
logger=migrator t=2024-10-30T15:40:59.855544613Z level=info msg="Executing migration" id="delete orphaned service account permissions"
logger=migrator t=2024-10-30T15:40:59.858459893Z level=error msg="Executing migration failed" id="delete orphaned service account permissions" error="failed to delete orphaned service accounts: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS p WHERE p.kind = 'serviceaccounts' AND p.identifier IN(?)' at line 1" duration=2.91496ms
logger=migrator t=2024-10-30T15:40:59.858477577Z level=error msg="Exec failed" error="failed to delete orphaned service accounts: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS p WHERE p.kind = 'serviceaccounts' AND p.identifier IN(?)' at line 1" sql="code migration"
logger=migrator t=2024-10-30T15:40:59.859839916Z level=info msg="Unlocking database"
Error: ✗ migration failed (id = delete orphaned service account permissions): failed to delete orphaned service accounts: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS p WHERE p.kind = 'serviceaccounts' AND p.identifier IN(?)' at line 1
`

**Comment by kalleep** [comment]
As I stated in my previous comment https://github.com/grafana/grafana/pull/95226 fixes the issue and will included in the next 10.4.x, 11.0.x, 11.1.x, 11.2.x and 11.3.x.

@rda0 Regarding using MariaDB instead of any of the databases listed here https://grafana.com/docs/grafana/latest/setup-grafana/installation/#supported-databases (or unsupported version e.g. Mysql 5.7) that is up to you. What I am saying is that we are not running any integration tests against it so it is easy to use some feature that it does not support

**Comment by melroy89** [comment]
> What I am saying is that we are not running any integration tests against it so it is easy to use some feature that it does not support

And I'm saying, include mariadb to your tests. To avoid regression. But I didn't get any response to that. Adding mariadb to the tests isn't that complex I think.

Debian defaults to MariaDB. And soon with Ubuntu 25 MariaDB will also become the default replacement of mysql.

**Comment by evgenijtrapecija** [comment]
looks like this issue is still here
`logger=migrator t=2024-11-04T15:51:15.653374005Z level=info msg="Starting DB migrations"
logger=migrator t=2024-11-04T15:51:15.659832037Z level=info msg="Executing migration" id="delete orphaned service account permissions"
logger=migrator t=2024-11-04T15:51:15.840713961Z level=error msg="Executing migration failed" id="delete orphaned service account permissions" error="failed to delete orphaned service accounts: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS p WHERE p.kind = 'serviceaccounts' AND p.identifier IN(?,?)' at line 1" duration=180.879693ms
logger=migrator t=2024-11-04T15:51:15.840739992Z level=error msg="Exec failed" error="failed to delete orphaned service accounts: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS p WHERE p.kind = 'serviceaccounts' AND p.identifier IN(?,?)' at line 1" sql="code migration"
Error: ✗ migration failed (id = delete orphaned service account permissions): failed to delete orphaned service accounts: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS p WHERE p.kind = 'serviceaccounts' AND p.identifier IN(?,?)' at line 1`

during upgrade from 10.4.10 to 10.4.11
mariadb version 11.4

**Comment by melroy89** [comment]
It's still there yes, because they still need to create a new Grafana release which includes the fix.

**Comment by rda0** [comment]
Upgrade to v10.4.12 still fails, see #96252

**Comment by melroy89** [comment]
v11.3.1 release now contain the fix for this migration regression issue for **MariaDB** .... 

**I just really really hope Grafana will include MariaDB validation within their test suite.**
