### ISSUE TITLE
Ensure Grafana supports Prometheus 3.0.1 and OpenTelemetry data

### ISSUE THREAD

**Issue by kago-dk** [grafana/grafana#97445]
### What happened?

When utilizing Prometheus 3.0.1 and OTLP receiver with the translation strategy NoUTF8EscapingWithSuffixes, you have labels such as cloud.region and container.name. When trying to use the label values as variables in Grafana 11.3.2, it fails - both when using GET or POST in the Prometheus data source, as seen in the screenshot.
![Image](https://github.com/user-attachments/assets/90985c28-8304-4e3e-b54a-e916f8b696f1)

The Prometheus team recommends setting the translation strategy to NoUTF8EscapingWithSuffixes. 

**Background**
https://grafana.com/blog/2024/11/06/prometheus-3.0-and-opentelemetry-a-practical-guide-to-storing-and-querying-otel-data/
https://prometheus.io/docs/guides/opentelemetry/

### What did you expect to happen?

Support for Prometheus 3.0.1 and OpenTelemetry data

### Did this work before?

N/A

### How do we reproduce it?

N/A

### Environment (with versions)?

Grafana: 11.3.2
Browser: Chrome 131.0.6778.109 

### Grafana platform?

None

**Comment by NWRichmond** [comment]
Hi! I believe this is part of https://github.com/grafana/grafana/issues/91253, and should be resolved by https://github.com/grafana/grafana/pull/96244.

**Comment by itsmylife** [comment]
It will be resolved with this issue https://github.com/grafana/grafana/issues/98245 and the PR https://github.com/grafana/grafana/pull/98345

**Comment by ywwg** [comment]
Note that these changes will require Prometheus 3.1 to work properly because of some bugs in 3.0.1

**Comment by itsmylife** [comment]
The necessary PRs are merged into the main. Please make sure you use Prometheus v3.1.0 and the latest Grafana (v11.5.0 which is going to be released soon)

Epic: https://github.com/grafana/grafana/issues/91253

**Comment by kago-dk** [comment]
@itsmylife Was the fixes part of Grafana V11.5? I ask because I am still getting the same error using Prometheus V3.1.0 and Grafana v11.5.0

**Comment by itsmylife** [comment]
@kago-dk yes it is. Could you please share a .HAR file that captures the error? Also the prometheus build info?

**Comment by kago-dk** [comment]
Prometheus Build
<img width="1025" alt="Image" src="https://github.com/user-attachments/assets/3ef9e4fb-d72f-44eb-abec-5a8078d833b2" />

Grafana Build
<img width="266" alt="Image" src="https://github.com/user-attachments/assets/0ed3c69f-ef2c-4a89-a650-f6ad912c2967" />

**Comment by kago-dk** [comment]
@itsmylife , did it help you understand the issue?

**Comment by ryanseipp** [comment]
Hello, I am also experiencing this issue. I am running the following versions via the corresponding docker images:
* Prometheus: 3.1.0
  * quay.io/prometheus/prometheus:3.1.0@sha256:6559acbd5d770b15bb3c954629ce190ac3cbbdb2b7f1c30f0385c4e05104e218
* Grafana: 11.5.1
  * grafana/grafana:11.5.1@sha256:5781759b3d27734d4d548fcbaf60b1180dbf4290e708f01f292faa6ae764c5e6

I have Prometheus configured with `translation_strategy: NoUTF8EscapingWithSuffixes` and can view metrics and labels with UTF-8 names, but selecting them in the metrics explorer, query builder, or variable query as described above do not properly format & escape the variable into the utf-8 syntax Prometheus expects.

Am I missing a feature toggle, or some piece of information Grafana expects from the datasource configuration in order to enable this transformation? To expedite, here's my datasource configuration:
```yaml
apiVersion: 1                                                                                                                                                                                                                                                     
datasources:                                                                                                                                                                                                                                                                  
- name: "Prometheus"
  type: prometheus
  uid: prometheus
  url: http://prometheus-stack-chart-kub-prometheus.observability:9090/
  access: proxy
  isDefault: true
  jsonData:
    httpMethod: POST
    timeInterval: 30s
```

I also tried specifying `jsonData.prometheusVersion: 3.1.0` but that had no effect.

**Comment by itsmylife** [comment]
I found the problem. This issue initially resolved with this PR https://github.com/grafana/grafana/pull/98345
But I merged that PR one day after we created `v11.5.x` minor release. So that PR has missed to release date. (I was tricked by the milestone on the PR. Clearly that setting is not working perfectly)
That's why it's not working for your case. It will be definitely in `v11.6.x` release. Unfortunately we have to wait till 11th of March. So I'd kindly ask for waiting `v11.6.0`
